// 確保全域變數存在，以便合併多冊字庫
if (typeof window.englishDb === 'undefined') { window.englishDb = {}; }
if (!window.englishDb["翰林"]) { window.englishDb["翰林"] = {}; }

// ==========================================
// 翰林版 2下 (Book 4) 完整字庫 (全單字 + 完整中文翻譯例句)
// ==========================================
window.englishDb["翰林"]["二下"] = {
    "Lesson 1": [
        { word: "foreign", translate: "外國的", sentence: "Tom likes foreign music. He often listens to K-pop and French songs. (湯姆喜歡外國音樂。他經常聽K-pop和法文歌。)" },
        { word: "than", translate: "比", sentence: "I am taller than my sister. (我比我妹妹高。)" },
        { word: "friendly", translate: "友善的", sentence: "Everyone likes Emily because she is always friendly to people. (每個人都喜歡艾蜜莉，因為她對人總是友善。)" },
        { word: "convenient", translate: "便利的", sentence: "It is convenient to go around Taipei by Taipei Metro. (搭乘台北捷運遊覽台北很便利。)" },
        { word: "pork", translate: "豬肉", sentence: "Can you buy some pork from the supermarket? (你可以從超市買些豬肉嗎？)" },
        { word: "beef", translate: "牛肉", sentence: "Many people in India don't eat beef. (印度很多人不吃牛肉。)" },
        { word: "delicious", translate: "美味的", sentence: "Alice treated me to a delicious meal at a nice restaurant. (愛麗絲在一家不錯的餐廳請我吃了一頓美味的飯。)" },
        { word: "feel", translate: "感到", sentence: "I felt tired after working all day long. (工作了一整天後我感到疲累。)" },
        { word: "steak", translate: "牛排;肉排", sentence: "Steak is Andy's favorite food. (牛排是安迪最喜歡的食物。)" },
        { word: "menu", translate: "菜單", sentence: "Do you have sandwiches on the menu? (你們的菜單上有三明治嗎？)" },
        { word: "waitress", translate: "女服務生", sentence: "I asked the waitress for a cup of tea. (我向女服務生要了一杯茶。)" },
        { word: "ham", translate: "火腿", sentence: "I had a ham sandwich for breakfast this morning. (我今天早上吃了一個火腿三明治當早餐。)" },
        { word: "butter", translate: "奶油", sentence: "Fiona makes delicious butter cookies. (費歐娜做美味的奶油餅乾。)" },
        { word: "medium", translate: "五分熟;中等的", sentence: "I like my steak medium. (我喜歡我的牛排五分熟。)" },
        { word: "meat", translate: "肉", sentence: "Tim loves meat. Beef is his favorite. (提姆熱愛肉類。牛肉是他的最愛。)" },
        { word: "smell", translate: "聞起來;氣味", sentence: "What are you cooking? It smells so good. (你在煮什麼？聞起來好香。)" },
        { word: "taste", translate: "嚐起來;味道", sentence: "The coffee cost me eighty dollars. And it tasted terrible. (這杯咖啡花了我八十元。而且嚐起來糟透了。)" },
        { word: "as...as...", translate: "如同...一樣...", sentence: "The ten-year-old boy is as tall as his father. (這個十歲的男孩和他爸爸一樣高。)" },
        { word: "get around", translate: "各處旅行", sentence: "We got around the village by bike. (我們騎腳踏車在村子裡各處遊覽。)" },
        { word: "dish", translate: "菜餚", sentence: "My mom makes delicious chicken soup. It's my favorite dish. (我媽媽做美味的雞湯。這是我最喜歡的菜餚。)" },
        { word: "more", translate: "更...", sentence: "To many students, math is more difficult than English. (對許多學生來說，數學比英文更困難。)" },
        { word: "get", translate: "變成", sentence: "Mike got healthier by doing lots of exercise. (麥克藉由做很多運動變得更健康。)" },
        { word: "sound", translate: "聽起來", sentence: "Did the story sound interesting to you? (這個故事你聽起來覺得有趣嗎？)" },
        { word: "top", translate: "頂部(的)", sentence: "A bird sat on the top of the house. (一隻鳥停在房子的頂部。)" },
        { word: "fries", translate: "薯條", sentence: "Don't always eat fries. It's bad for your health. (不要總是吃薯條。這對你的健康不好。)" },
        { word: "knife", translate: "刀子", sentence: "Be careful! The bad guy has a knife in his right hand. (小心！那個壞人右手拿著一把刀。)" },
        { word: "fork", translate: "叉子", sentence: "The man is using a fork to eat the noodles. (那個男人正在用叉子吃麵。)" },
        { word: "noodle", translate: "麵", sentence: "Taiwan is famous for beef noodles. (台灣以牛肉麵聞名。)" },
        { word: "chopsticks", translate: "筷子", sentence: "My friend from the USA cannot use chopsticks to eat. (我來自美國的朋友不會用筷子吃飯。)" },
        { word: "spoon", translate: "湯匙", sentence: "I ate the soup with a spoon. (我用湯匙喝湯。)" },
        { word: "fried chicken", translate: "炸雞", sentence: "We had fried chicken at the party. (我們在派對上吃了炸雞。)" },
        { word: "waiter", translate: "男服務生", sentence: "It is lunch time, and the waiters are busy taking orders. (現在是午餐時間，男服務生們正忙著點餐。)" },
        { word: "strawberry", translate: "草莓", sentence: "The strawberry pie looks more delicious than the pumpkin pie. (這個草莓派看起來比南瓜派更美味。)" },
        { word: "bun", translate: "小圓麵包", sentence: "My mom took a bun to make a hamburger. (我媽媽拿了一個小圓麵包來做漢堡。)" },
        { word: "earth", translate: "地球", sentence: "How many people are there on earth? (地球上有多少人？)" },
        { word: "bring", translate: "帶來;攜帶", sentence: "Please bring your books to class tomorrow. (明天請把你們的書帶來上課。)" },
        { word: "smile", translate: "微笑", sentence: "Ms. Lee gave me a big smile. (李老師給了我一個大大的微笑。)" },
        { word: "land", translate: "陸地;落地", sentence: "The land is very green in spring. (這片土地在春天非常翠綠。)" },
        { word: "rock", translate: "岩石", sentence: "We sat on the rock to watch the clouds. (我們坐在岩石上看雲。)" },
        { word: "shape", translate: "形狀", sentence: "The cookie is in the shape of an umbrella. (這塊餅乾是雨傘的形狀。)" },
        { word: "clear", translate: "晴朗的;清楚的", sentence: "The sky is clear today. There are no clouds. (今天天空很晴朗。沒有雲。)" },
        { word: "comfortable", translate: "舒適的;自在的", sentence: "This sofa is really comfortable. Let's buy it. (這張沙發真的很舒服。我們買下來吧。)" },
        { word: "fill", translate: "充滿;裝滿", sentence: "The students filled their bottles with water. (學生們把他們的水瓶裝滿了水。)" },
        { word: "pack", translate: "打包;塞進", sentence: "Eric is packing his clothes for the trip. (艾瑞克正在為旅行打包衣服。)" }
    ],
    "Lesson 2": [
        { word: "grass", translate: "草地", sentence: "We sat on the grass and had a picnic on a sunny day. (在一個晴朗的日子，我們坐在草地上野餐。)" },
        { word: "red fire ant", translate: "紅火蟻", sentence: "Be careful. There are red fire ants in this park. (小心。這個公園裡有紅火蟻。)" },
        { word: "dangerous", translate: "危險的", sentence: "Stop playing on the road. It's dangerous. (不要在馬路上玩。那很危險。)" },
        { word: "bite", translate: "咬;咬(傷)", sentence: "The dog bit the little boy on the arm. (那隻狗咬了小男孩的手臂。)" },
        { word: "death", translate: "死亡", sentence: "Nicole is really sad about her pet cat's death. (妮可對她寵物貓的死亡感到非常傷心。)" },
        { word: "kick", translate: "踢", sentence: "Jeff kicked the ball in the classroom and broke the window. (傑夫在教室裡踢球，打破了窗戶。)" },
        { word: "themselves", translate: "他們自己", sentence: "Do your kids go to school by themselves? (你的孩子們自己去上學嗎？)" },
        { word: "kill", translate: "殺死", sentence: "The terrible fire killed many factory workers. (那場可怕的火災奪走了許多工廠工人的生命。)" },
        { word: "stay away from", translate: "遠離...", sentence: "Stay away from that man. He may hurt you. (遠離那個男人。他可能會傷害你。)" },
        { word: "agree", translate: "同意", sentence: "Everyone in the class agrees with Jim's idea. (班上每個人都同意吉姆的想法。)" },
        { word: "circle", translate: "圓圈;畫圈", sentence: "The students sat in a circle and played games. (學生們圍成一個圓圈玩遊戲。)" },
        { word: "myself", translate: "我自己", sentence: "A: Who made this delicious cake? B: I made it by myself. (A: 誰做了這個美味的蛋糕？B: 我自己做的。)" },
        { word: "snake", translate: "蛇", sentence: "Many people are scared of snakes. (許多人害怕蛇。)" },
        { word: "wet", translate: "潮濕的", sentence: "It is cold and wet in Taipei in winter. (台北的冬天又冷又潮濕。)" },
        { word: "scary", translate: "令人害怕的", sentence: "I never watch scary movies. (我從不看恐怖電影。)" },
        { word: "deep", translate: "深的", sentence: "The river is deep. Don't swim in it. (這條河很深。不要在裡面游泳。)" },
        { word: "true", translate: "真實的", sentence: "You're moving to India. Is it true? (你要搬到印度了。是真的嗎？)" },
        { word: "most", translate: "最;最多的", sentence: "English is the most interesting subject to me. (英文對我來說是最有趣的科目。)" },
        { word: "give... a hand", translate: "幫助...", sentence: "Could you give me a hand with the homework? It's difficult. (你能幫我做功課嗎？這很困難。)" },
        { word: "spider", translate: "蜘蛛", sentence: "Help! There's a big spider in my bedroom. (救命！我的臥室裡有一隻大蜘蛛。)" },
        { word: "gram", translate: "公克", sentence: "How many grams of flour do you need? (你需要多少公克的麵粉？)" },
        { word: "insect", translate: "昆蟲", sentence: "Red fire ants are dangerous insects. (紅火蟻是危險的昆蟲。)" },
        { word: "bee", translate: "蜜蜂", sentence: "Bees are flying around the flowers. (蜜蜂在花朵周圍飛舞。)" },
        { word: "inch", translate: "吋", sentence: "An inch is about 2.5 centimeters. (一吋大約是2.5公分。)" },
        { word: "wide", translate: "寬的", sentence: "We can't get the table into the room. The door is not wide enough. (我們無法把桌子搬進房間。門不夠寬。)" },
        { word: "kilogram", translate: "公斤", sentence: "Debby is thin; she's only 40 kilograms. (黛比很瘦；她只有40公斤。)" },
        { word: "nature", translate: "大自然", sentence: "I love walking in nature on weekends. (我喜歡在週末走在大自然中。)" },
        { word: "below", translate: "在...之下;在下面", sentence: "When we stood on the top of the hill, the houses below looked so small. (當我們站在山丘頂上時，下面的房子看起來好小。)" },
        { word: "sea level", translate: "海平面", sentence: "The top of that mountain is about eight thousand meters above sea level. (那座山頂大約在海平面以上八千公尺。)" },
        { word: "mile", translate: "英里", sentence: "My grandma walks ten miles a day to keep healthy. (我奶奶每天走十英里來保持健康。)" },
        { word: "feet", translate: "英尺", sentence: "The bus station is only fifty feet from my house. (公車站離我家只有五十英尺。)" },
        { word: "smart", translate: "聰明的", sentence: "That was a smart way to fix the problem. (那是一個解決問題的聰明方法。)" },
        { word: "traffic", translate: "交通;車流", sentence: "The traffic was very slow today because there was a car accident. (今天的交通非常緩慢，因為發生了車禍。)" },
        { word: "appear", translate: "似乎", sentence: "Harry appears mad, but he's just thinking. (哈利似乎很生氣，但他只是在思考。)" },
        { word: "air", translate: "空中;空氣", sentence: "You can smell the flowers in the air. (你可以在空氣中聞到花香。)" },
        { word: "far", translate: "遠", sentence: "How far is it from your house to school? (從你家到學校有多遠？)" },
        { word: "slow", translate: "放慢;慢的", sentence: "The bus slowed down at the corner. (公車在轉角處放慢了速度。)" },
        { word: "light", translate: "燈;光", sentence: "Cars go when the traffic lights turn green. (當交通號誌燈變綠時，車子就可以走了。)" },
        { word: "cross", translate: "穿越", sentence: "Look both ways before you cross the street. (過馬路前要看兩邊。)" }
    ],
    "Lesson 3": [
        { word: "loudly", translate: "大聲地", sentence: "The kids sang loudly at the party. (孩子們在派對上大聲唱歌。)" },
        { word: "hard", translate: "努力地;困難的", sentence: "Albert worked hard and made a lot of money. (阿爾伯特努力工作，賺了很多錢。)" },
        { word: "well", translate: "好地", sentence: "Dad is old, and he can't hear very well. (爸爸年紀大了，他聽不太清楚。)" },
        { word: "share", translate: "分享", sentence: "I would like to share my stories about my days in Australia. (我想分享我在澳洲日子的故事。)" },
        { word: "weak", translate: "虚弱的", sentence: "He felt weak when he traveled to India for vacation. (他去印度度假時感到身體虛弱。)" },
        { word: "hen", translate: "母雞", sentence: "Mr. Parker is feeding his hens. (派克先生正在餵他的母雞。)" },
        { word: "dirty", translate: "髒的", sentence: "Our hands, feet, and clothes were dirty after we played soccer. (我們踢完足球後，手、腳和衣服都很髒。)" },
        { word: "bow", translate: "鞠躬", sentence: "The singer bowed and thanked his friends for coming to his show. (歌手鞠躬感謝他的朋友們來看他的表演。)" },
        { word: "without", translate: "沒有;無", sentence: "I left school without an umbrella, so I got wet when it rained. (我離開學校時沒有帶傘，所以下雨時我淋濕了。)" },
        { word: "quickly", translate: "快地", sentence: "Bob, don't eat so quickly. It's bad for your health. (鮑伯，不要吃得這麼快。這對你的健康不好。)" },
        { word: "web page", translate: "網頁", sentence: "This web page looks terrible. There are too many colors. (這個網頁看起來糟透了。有太多顏色了。)" },
        { word: "service", translate: "服務", sentence: "The hotel provides good service. (這家飯店提供良好的服務。)" },
        { word: "wise", translate: "明智的", sentence: "It is wise to think twice before you decide to do anything big. (在決定做任何大事前三思是明智的。)" },
        { word: "cheer", translate: "歡呼", sentence: "The fans cheer for their team at the game. (球迷們在比賽中為他們的隊伍歡呼。)" },
        { word: "celebrate", translate: "慶祝", sentence: "My friends and I always get together to celebrate Thanksgiving. (我的朋友和我總是聚在一起慶祝感恩節。)" },
        { word: "mean", translate: "刻薄的;兇惡的", sentence: "Cinderella's sisters are mean to her. (灰姑娘的姊姊們對她很刻薄。)" },
        { word: "make", translate: "要...做...;使...", sentence: "Mom made my brother mop the floor and wipe the tables. (媽媽要我哥哥拖地和擦桌子。)" },
        { word: "break", translate: "休息", sentence: "At break, we usually share some snacks with each other. (休息時間，我們通常會互相分享一些點心。)" },
        { word: "over", translate: "超過", sentence: "Yesterday, Jerry worked for over twelve hours. He looked really tired. (昨天，傑瑞工作了超過十二小時。他看起來真的很累。)" },
        { word: "treat", translate: "對待", sentence: "Our teacher treats all the students the same. (我們的老師對待所有學生都一樣。)" },
        { word: "have", translate: "使...", sentence: "I'll have my secretary give you a call in ten minutes. (我會讓我的秘書在十分鐘後打電話給你。)" },
        { word: "grape", translate: "葡萄", sentence: "Dad bought me a cheeseburger and a bottle of grape juice for breakfast. (爸爸買了一個起司漢堡和一瓶葡萄汁給我當早餐。)" },
        { word: "goose", translate: "鵝", sentence: "The snow goose is dancing beautifully on the lake. (雪鵝正在湖面上優美地跳舞。)" },
        { word: "duck", translate: "鴨", sentence: "We were fishing by the lake when some ducks swam past. (我們正在湖邊釣魚時，幾隻鴨子游了過去。)" },
        { word: "goat", translate: "山羊", sentence: "There are goats living in the mountains behind my house. (我家後面的山裡住著山羊。)" },
        { word: "sheep", translate: "綿羊", sentence: "The sheep are eating grass. (綿羊正在吃草。)" },
        { word: "peach", translate: "桃子", sentence: "I would like some peaches and cream for my afternoon tea. (我的下午茶想要一些桃子和鮮奶油。)" },
        { word: "turtle", translate: "烏龜", sentence: "Julie is feeding a baby turtle some vegetables. (茱莉正在餵一隻小烏龜吃一些蔬菜。)" },
        { word: "pear", translate: "梨子", sentence: "Last year, Melody planted a pear tree in front of her house. (去年，美樂蒂在她家門前種了一棵梨樹。)" },
        { word: "papaya", translate: "木瓜", sentence: "Jacky loves drinking papaya milk when he gets home from school. (傑克放學回家後很喜歡喝木瓜牛奶。)" },
        { word: "vegetable", translate: "蔬菜", sentence: "Growing fruit and vegetables is Mr. Depp's job. (種植水果和蔬菜是戴普先生的工作。)" },
        { word: "guava", translate: "芭樂", sentence: "These guava trees are about six meters tall. (這些芭樂樹大約有六公尺高。)" },
        { word: "tomato", translate: "番茄", sentence: "I love egg and tomato sandwiches. (我喜歡雞蛋番茄三明治。)" },
        { word: "watermelon", translate: "西瓜", sentence: "You can buy a bottle of watermelon juice at a very low price at the night market. (你可以在夜市以非常低的價格買到一瓶西瓜汁。)" },
        { word: "American", translate: "美國人", sentence: "Jack's wife is an American. (傑克的妻子是美國人。)" },
        { word: "million", translate: "百萬", sentence: "There are about 23 million people in Taiwan. (台灣大約有兩千三百萬人。)" },
        { word: "pound", translate: "磅", sentence: "The pork is on sale this week. It costs only two dollars a pound. (這週豬肉在特價。一磅只要兩元。)" },
        { word: "pick", translate: "採摘;撿拾", sentence: "When we climbed up the mountain, we picked some flowers along the way. (當我們爬山時，我們沿路摘了一些花。)" },
        { word: "bean", translate: "豆", sentence: "Chicken with green beans is the best dish at this restaurant. (青豆雞肉是這家餐廳最棒的菜。)" },
        { word: "cent", translate: "美分", sentence: "He works very hard, but he only gets 80 cents an hour. (他工作非常努力，但他一小時只得到80美分。)" },
        { word: "chance", translate: "機會", sentence: "These kids are poor. They don't even have a chance to go to school. (這些孩子很窮。他們甚至沒有機會去上學。)" },
        { word: "choose", translate: "選擇", sentence: "Teresa chose a red dress for the Christmas party. (泰瑞莎為聖誕派對選擇了一件紅色的洋裝。)" }
    ],
    "Lesson 4": [
        { word: "typhoon", translate: "颱風", sentence: "The typhoon season falls between July and September in Taiwan. (在台灣，颱風季落在七月到九月之間。)" },
        { word: "blow", translate: "吹", sentence: "The strong wind blew down a tall tree. (強風吹倒了一棵大樹。)" },
        { word: "rose", translate: "玫瑰花", sentence: "On Valentine's Day, Judy's husband gave her a red rose and a card. (情人節那天，茱蒂的丈夫給了她一朵紅玫瑰和一張卡片。)" },
        { word: "balcony", translate: "陽台", sentence: "She is hanging the clothes on the balcony. (她正在陽台上晾衣服。)" },
        { word: "must", translate: "必須;一定", sentence: "For your own safety, you must follow the rules when driving. (為了你自己的安全，你開車時必須遵守規則。)" },
        { word: "prepare", translate: "準備", sentence: "She is preparing sandwiches, hamburgers, and orange juice for the picnic. (她正在為野餐準備三明治、漢堡和柳橙汁。)" },
        { word: "should", translate: "應該", sentence: "You should wash your hands before you eat. (你吃東西前應該洗手。)" },
        { word: "candle", translate: "蠟燭", sentence: "The wind is really strong. It blew out the candle. (風真的很強。它吹熄了蠟燭。)" },
        { word: "radio", translate: "收音機;廣播", sentence: "I sat in my car and turned on the radio. (我坐在車裡，打開了收音機。)" },
        { word: "news", translate: "新聞;消息", sentence: "There was news on the big earthquake last night. (昨晚有關於大地震的新聞。)" },
        { word: "if", translate: "如果", sentence: "If you come home late, I'll have dinner by myself. (如果你晚回家，我就自己吃晚餐。)" },
        { word: "or", translate: "否則", sentence: "We should leave now, or we'll be late for the movie. (我們現在應該離開了，否則我們看電影會遲到。)" },
        { word: "have to", translate: "必須", sentence: "Before the typhoon comes, we have to prepare enough food and water. (颱風來臨前，我們必須準備足夠的食物和水。)" },
        { word: "go out", translate: "熄滅", sentence: "The fire finally went out with the help of the rescue team. (在救援隊的幫助下，火終於熄滅了。)" },
        { word: "train", translate: "訓練", sentence: "She trained hard to be a successful basketball player. (她努力訓練以成為一名成功的籃球員。)" },
        { word: "face", translate: "面對", sentence: "Ron, you have to face the fear of spiders. (榮恩，你必須面對對蜘蛛的恐懼。)" },
        { word: "try one's best", translate: "盡力而為", sentence: "The doctor tried her best to save the dying man. (醫生盡了她最大的努力去拯救那個垂死的人。)" },
        { word: "turn on", translate: "打開(電源)", sentence: "The boy turned on the TV right after he got back home. (男孩一回到家就打開了電視。)" },
        { word: "latest", translate: "最新的", sentence: "The reporter is reporting the latest news on TV. (記者正在電視上報導最新的新聞。)" },
        { word: "star", translate: "星星", sentence: "Look up at the sky now! There are thousands of bright stars. (現在抬頭看看天空！有成千上萬顆明亮的星星。)" },
        { word: "shine", translate: "閃耀;照耀", sentence: "The sun is shining brightly. It's a nice sunny day. (太陽明亮地照耀著。這是個美好的晴天。)" },
        { word: "giant", translate: "巨大的", sentence: "The giant turtle moves very slowly on the beach. (這隻巨大的海龜在海灘上移動得非常緩慢。)" },
        { word: "wave", translate: "浪", sentence: "The boat moved with the waves. (小船隨著波浪移動。)" },
        { word: "rainbow", translate: "彩虹", sentence: "A rainbow came out after the heavy rain. (下過大雨後出現了一道彩虹。)" },
        { word: "pretty", translate: "漂亮的", sentence: "The singer looks very pretty. (那位歌手看起來非常漂亮。)" },
        { word: "garden", translate: "花園", sentence: "Aunt Tracy grows many flowers in her garden. (崔西阿姨在她的花園裡種了許多花。)" },
        { word: "frog", translate: "青蛙", sentence: "You can find frogs easily by a pond in summer. (夏天時你可以很容易地在池塘邊找到青蛙。)" },
        { word: "noise", translate: "聲響;噪音", sentence: "I couldn't study because people around me made too much noise. (我無法讀書，因為周圍的人製造了太多噪音。)" },
        { word: "pond", translate: "池塘", sentence: "Fish, turtles, and ducks live in the pond. (魚、烏龜和鴨子住在池塘裡。)" },
        { word: "noisy", translate: "嘈雜的", sentence: "The street is noisy because of the cars. (這條街因為車子而很嘈雜。)" },
        { word: "earthquake", translate: "地震", sentence: "The big earthquake killed many people. (那場大地震奪走了許多人的生命。)" },
        { word: "bravely", translate: "勇敢地", sentence: "The soldiers fight bravely for their country. (士兵們勇敢地為他們的國家戰鬥。)" },
        { word: "sharp", translate: "尖銳的", sentence: "Be careful of the sharp knife. You may get hurt. (小心那把鋒利的刀。你可能會受傷。)" },
        { word: "reach", translate: "到達", sentence: "They climbed up the mountain and reached the top. (他們爬上山並到達了山頂。)" },
        { word: "space", translate: "空間", sentence: "The concert was full of people. There was no space for more. (演唱會擠滿了人。沒有空間容納更多人了。)" },
        { word: "size", translate: "大小;尺寸", sentence: "We wore the same size T-shirt. (我們穿一樣尺寸的T恤。)" },
        { word: "as", translate: "作為;如同", sentence: "Danny's father works as a taxi driver. (丹尼的父親擔任計程車司機。)" },
        { word: "times", translate: "倍", sentence: "Ms. Johnson makes five times more money than Mr. Johnson. (強森女士賺的錢是強森先生的五倍。)" }
    ],
    "Lesson 5": [
        { word: "although", translate: "雖然", sentence: "Although Mr. Mills didn't feel good, he still came to work today. (雖然密爾斯先生覺得不舒服，他今天還是來上班了。)" },
        { word: "matter", translate: "問題;事件", sentence: "A: What's the matter? You look tired. B: I didn't sleep well last night. (A: 怎麼了？你看起來很累。B: 我昨晚沒睡好。)" },
        { word: "sore throat", translate: "喉嚨痛", sentence: "You should see a doctor when you have a sore throat. (你喉嚨痛時應該去看醫生。)" },
        { word: "explain", translate: "解釋", sentence: "It's difficult for me to explain the problem clearly. (對我來說，要清楚解釋這個問題很困難。)" },
        { word: "cough", translate: "咳嗽", sentence: "My grandma has a bad cough. She's taking some medicine now. (我奶奶咳得很厲害。她現在正在吃藥。)" },
        { word: "probably", translate: "很可能;大概", sentence: "If you still have problems with the math homework, you should probably go ask the teacher. (如果你對數學作業還有問題，你也許應該去問老師。)" },
        { word: "take care of", translate: "照顧", sentence: "The nurses take good care of the mother and the baby. (護士們把媽媽和嬰兒照顧得很好。)" },
        { word: "noon", translate: "中午", sentence: "My mom goes to work at night and comes back home before noon. (我媽媽晚上去上班，在中午前回家。)" },
        { word: "both", translate: "兩者(都)", sentence: "I have two brothers. Both of them are on the baseball team. (我有兩個哥哥。他們兩個都在棒球隊。)" },
        { word: "medicine", translate: "藥", sentence: "Children don't like to take medicine. (小孩子不喜歡吃藥。)" },
        { word: "honey", translate: "蜂蜜", sentence: "I would like to have some honey for my lemon tea. (我想在我的檸檬茶裡加些蜂蜜。)" },
        { word: "lemon", translate: "檸檬", sentence: "Jessica stopped at a cake shop and looked at the lemon cake in the window. (潔西卡停在一家蛋糕店前，看著櫥窗裡的檸檬蛋糕。)" },
        { word: "useful", translate: "有用的", sentence: "I got some useful books on science from my dad. (我從我爸爸那裡得到了一些有用的科學書。)" },
        { word: "stand", translate: "攤位", sentence: "There's an ice cream stand in the park. It sells my favorite ice cream. (公園裡有一個冰淇淋攤。它賣我最喜歡的冰淇淋。)" },
        { word: "feel like", translate: "想要", sentence: "I don't feel like cooking. Can we just go out for dinner? (我不想煮飯。我們可以出去吃晚餐嗎？)" },
        { word: "cold", translate: "感冒", sentence: "Some people catch a cold when seasons change. (有些人在季節變換時會感冒。)" },
        { word: "well", translate: "健康的", sentence: "I'm not feeling well. My stomach hurts. (我覺得不舒服。我的胃好痛。)" },
        { word: "treat", translate: "治療", sentence: "The medicine couldn't treat her headache. (這藥無法治療她的頭痛。)" },
        { word: "head", translate: "頭", sentence: "The baby fell off the bed and hurt its head. (嬰兒從床上摔下來傷到了頭。)" },
        { word: "headache", translate: "頭痛", sentence: "I didn't sleep well last night, so I have a headache now. (我昨晚沒睡好，所以我現在頭痛。)" },
        { word: "stomachache", translate: "胃痛", sentence: "You might get a stomachache if you eat too much or too fast. (如果你吃太多或太快，你可能會胃痛。)" },
        { word: "fever", translate: "發燒", sentence: "The girl has a high fever. (這個女孩發高燒。)" },
        { word: "runny nose", translate: "流鼻水", sentence: "A: Do you know any way to stop a runny nose? B: Yes. Try some hot lemon drinks. (A: 你知道有什麼方法可以止住流鼻水嗎？B: 是的。試試熱檸檬飲料。)" },
        { word: "knee", translate: "膝蓋", sentence: "I hurt my knee during PE class. (我在體育課時弄傷了膝蓋。)" },
        { word: "nail", translate: "指甲", sentence: "The man bites his nails when he is nervous. (這個男人緊張時會咬指甲。)" },
        { word: "finger", translate: "手指", sentence: "Bella has beautiful hands. Her fingers are long and thin. (貝拉有雙美麗的手。她的手指又長又細。)" },
        { word: "neck", translate: "脖子", sentence: "I can't turn my head because my neck hurts. (我無法轉頭，因為我的脖子很痛。)" },
        { word: "shoulder", translate: "肩膀", sentence: "There's a bird resting on your left shoulder. (有一隻鳥停在你的左肩上。)" },
        { word: "bakery", translate: "麵包店", sentence: "We bought the bread from the bakery. (我們從麵包店買了麵包。)" },
        { word: "common", translate: "常見的;共同的", sentence: "Forest fires are common in Australia in late January and early February. (在澳洲，一月下旬和二月上旬森林大火是很常見的。)" },
        { word: "actually", translate: "實際上;事實上", sentence: "The store looks small, but it's actually big inside. (這家店看起來很小，但裡面實際上很大。)" },
        { word: "helpful", translate: "有幫助的", sentence: "Thanks for your idea. It's really helpful. (謝謝你的點子。這真的很有幫助。)" },
        { word: "root", translate: "根;根源", sentence: "The roots of a tree can go deep into the ground. (樹的根可以深入地下。)" },
        { word: "reason", translate: "原因;理由", sentence: "The woman sometimes feels sad for no reason. (這個女人有時候會無緣無故地感到悲傷。)" },
        { word: "power up", translate: "增強力量", sentence: "A good lunch can power you up for the afternoon. (一頓美好的午餐可以為你下午增強體力。)" },
        { word: "sweet", translate: "甜食", sentence: "My cousin loves eating sweets like candy and chocolate. (我表弟喜歡吃像糖果和巧克力這樣的甜食。)" },
        { word: "sharp", translate: "敏銳的", sentence: "She has a sharp memory and can remember things from years ago. (她有著敏銳的記憶力，能記住幾年前的事情。)" }
    ],
    "Lesson 6": [
        { word: "pass", translate: "傳遞;通過", sentence: "Could you pass the salt, please? (請你把鹽遞給我好嗎？)" },
        { word: "throw", translate: "丟;投擲", sentence: "The little boy threw something out of the window. (那個小男孩把東西丟出窗外。)" },
        { word: "point", translate: "得分", sentence: "David got the most points in the game. (大衛在比賽中得到最高分。)" },
        { word: "win", translate: "贏;獲勝", sentence: "I believe that we'll win the game if we practice harder. (我相信如果我們更努力練習，我們就會贏得比賽。)" },
        { word: "until", translate: "直到", sentence: "John didn't clean his room until his mom got mad. (約翰直到他媽媽生氣了才打掃他的房間。)" },
        { word: "member", translate: "成員", sentence: "Sammy is a member of the mountain climbing club. (山米是登山社的成員。)" },
        { word: "group", translate: "團體", sentence: "Lily and I are in the same group in the English club. (莉莉和我在英語社的同一個小組。)" },
        { word: "fail", translate: "考不及格;失敗", sentence: "Many of the students in my class failed math. (我班上很多學生數學不及格。)" },
        { word: "test", translate: "考試", sentence: "Tiffany studied hard for the test. (蒂芬妮為了考試很用功讀書。)" },
        { word: "afraid", translate: "害怕的;擔憂的", sentence: "Rita is afraid of speaking in front of people. (瑞塔害怕在人群面前說話。)" },
        { word: "forget", translate: "忘記", sentence: "My teacher was mad because I forgot to do my homework. (我的老師很生氣，因為我忘記做作業了。)" },
        { word: "fresh", translate: "新的;新鮮的", sentence: "I opened the window for some fresh air. (我打開窗戶呼吸一些新鮮空氣。)" },
        { word: "count... in", translate: "算...參加一份", sentence: "A: We plan to go to the library later. Would you like to join us? B: Sure. Count me in. (A: 我們打算待會去圖書館。你想加入我們嗎？B: 當然。算我一份。)" },
        { word: "begin", translate: "開始", sentence: "Ted began learning English two years ago. (泰德兩年前開始學英文。)" },
        { word: "meeting", translate: "會議;會面", sentence: "We'll have a meeting with the boss this afternoon. (我們今天下午將和老闆開會。)" },
        { word: "come on", translate: "快點;少來了", sentence: "Come on, Sandy. Show me your work. (快點，珊迪。給我看你的作品。)" },
        { word: "excuse", translate: "藉口;理由", sentence: "Don't make an excuse for your mistake. (不要為你的錯誤找藉口。)" },
        { word: "around the corner", translate: "即將來臨;在附近", sentence: "Christmas is around the corner. (聖誕節即將來臨。)" },
        { word: "grade", translate: "成績", sentence: "Joe always gets good grades in science. (喬的自然科學成績總是很好。)" },
        { word: "hold back", translate: "阻礙", sentence: "Don't worry. I believe nothing can hold you back. (別擔心。我相信沒有什麼能阻礙你。)" },
        { word: "few", translate: "很少(的)", sentence: "Few students in the class like math. (班上很少有學生喜歡數學。)" },
        { word: "simple", translate: "簡單的", sentence: "That's a simple question. Even a five-year-old child can answer it. (那是個簡單的問題。甚至一個五歲的小孩都能回答。)" },
        { word: "expect", translate: "預計;期望", sentence: "I didn't expect to see you at Frank's party. Aren't you busy at work? (我沒想到會在法蘭克的派對上看到你。你工作不忙嗎？)" },
        { word: "mistake", translate: "錯誤", sentence: "People sometimes learn from mistakes. (人們有時候從錯誤中學習。)" },
        { word: "angle", translate: "立場;角度", sentence: "He always sees things from a different angle. (他總是從不同的角度看事情。)" },
        { word: "allow", translate: "允許", sentence: "Some parents don't allow their children to play video games. (有些父母不允許他們的孩子打電動。)" },
        { word: "laugh", translate: "笑;笑聲", sentence: "We laughed when we heard Jack's story about his experience in Indonesia. (當我們聽到傑克在印尼經歷的故事時，我們都笑了。)" },
        { word: "keep in mind", translate: "記住", sentence: "Keep in mind that you have to take the medicine after meals, or you might get a stomachache. (記住你必須在飯後吃藥，否則你可能會胃痛。)" },
        { word: "honest", translate: "誠實的;可信的", sentence: "To be honest, the writer's new book is worse than the last one. (老實說，這位作家的新書比上一本還糟。)" },
        { word: "lead to", translate: "導致", sentence: "Eating too much fast food may lead to health problems. (吃太多速食可能會導致健康問題。)" },
        { word: "push", translate: "迫使;推動", sentence: "The boss pushed the workers to work for long hours. (老闆迫使工人們長時間工作。)" },
        { word: "excellent", translate: "優秀的;極佳的", sentence: "Michael Phelps is an excellent swimmer. (麥可·菲爾普斯是一位優秀的游泳選手。)" },
        { word: "be able to", translate: "能夠", sentence: "I wasn't able to go to the party yesterday because I was sick. (我昨天沒辦法去派 party，因為我生病了。)" },
        { word: "define", translate: "下定義;界定", sentence: "Don't let others define you. Just be yourself. (不要讓別人定義你。做你自己就好。)" },
        { word: "matter", translate: "要緊;重要", sentence: "A: What did you want to tell me this morning? B: It doesn't matter now. (A: 你今天早上想告訴我什麼？B: 現在不重要了。)" },
        { word: "picture", translate: "想像", sentence: "Try to picture that you are in a rainforest. What do you see there? (試著想像你在雨林裡。你在那裡看到了什麼？)" },
        { word: "as for", translate: "至於", sentence: "The food in this restaurant is good. As for the service, it's bad. (這家餐廳的食物很好。至於服務，就很差。)" },
        { word: "to the full", translate: "盡可能", sentence: "Life is short. You should enjoy it to the full. (人生短暫。你應該盡可能地去享受它。)" }
    ]
};