// 確保全域變數存在，以便合併多版本、多冊的字庫
if (typeof window.englishDb === 'undefined') {
    window.englishDb = {};
}
if (!window.englishDb["南一"]) {
    window.englishDb["南一"] = {};
}

// ==========================================
// 南一版 3下 (Book 6) 完整字庫 (全單字 + 完整中文翻譯例句)
// ==========================================
window.englishDb["南一"]["三下"] = {
    "Lesson 1": [
        { word: "sir", translate: "先生", sentence: "What would you like to order, sir? (先生，您想要點什麼？)" },
        { word: "rule", translate: "規則", sentence: "Before you start, you need to know the rules of the game. (在你開始之前，你需要知道遊戲規則。)" },
        { word: "floor", translate: "樓層", sentence: "I live on the first floor because I am afraid of heights. (我住在一樓，因為我怕高。)" },
        { word: "thick", translate: "濃厚的", sentence: "Thick black smoke was coming out of the burning house. (濃濃的黑煙正從燃燒的房子裡冒出來。)" },
        { word: "enter", translate: "進入", sentence: "Ted entered the restaurant and sat down by the window. (泰德進入餐廳並在窗邊坐下。)" },
        { word: "balcony", translate: "陽臺", sentence: "We can see a beautiful garden from the balcony. (我們可以從陽臺看到一個美麗的花園。)" },
        { word: "mistake", translate: "錯誤;過失", sentence: "Tom didn't make any mistakes on his English test. (湯姆在他的英文考試中沒有犯任何錯誤。)" },
        { word: "firefighter", translate: "消防隊員", sentence: "A firefighter puts out fires and saves people from danger. (消防隊員撲滅火災並拯救處於危險中的人們。)" },
        { word: "exam", translate: "考試", sentence: "The teacher gave us a math exam. (老師給我們考了一次數學考試。)" },
        { word: "strength", translate: "體力", sentence: "Cherry is weak. She doesn't even have the strength to stand up. (雪莉很虛弱。她甚至沒有站起來的體力。)" },
        { word: "safety", translate: "安全", sentence: "For your own safety, please drive slowly on rainy days. (為了你自己的安全，下雨天請開慢點。)" },
        { word: "building", translate: "建築物", sentence: "Taipei 101 is the tallest building in Taipei. (臺北101是臺北最高的建築物。)" },
        { word: "appliance", translate: "家用電器", sentence: "A refrigerator is a kitchen appliance. (冰箱是一種廚房家用電器。)" },
        { word: "stove", translate: "爐灶", sentence: "Dad put the pot on the stove. (爸爸把鍋子放在爐灶上。)" },
        { word: "not only ... but also ...", translate: "不但...而且...", sentence: "I not only had to study for it but also had to learn many new skills. (我不但必須為此學習，還必須學習許多新技能。)" },
        { word: "build up", translate: "使...健康或強壯", sentence: "I had to build up my body strength, too. (我也必須增強我的體力。)" },
        { word: "deal with", translate: "處理", sentence: "They help me deal with different problems when I'm out on a call. (當我出勤時，他們幫我處理不同的問題。)" },
        { word: "put out", translate: "撲滅", sentence: "We put out fires and save people who are in danger. (我們撲滅火災並拯救處於危險中的人們。)" },
        { word: "repeat", translate: "重複", sentence: "Sorry, could you repeat your question, please? (抱歉，請你重複你的問題好嗎？)" },
        { word: "shower", translate: "淋浴", sentence: "Daniel always takes cold showers in the summer. (丹尼爾在夏天總是沖冷水澡。)" },
        { word: "tidy up", translate: "使...整潔", sentence: "Tidy up your room. Don't leave your books on the floor. (把你的房間整理乾淨。不要把你的書留在地板上。)" },
        { word: "fry", translate: "油炸;油煎", sentence: "Bill fried eggs and pork for breakfast this morning. (比爾今天早上煎了雞蛋和豬肉當早餐。)" },
        { word: "medium", translate: "中等的", sentence: "Gina is of medium height, so it's easy for her to buy clothes. (吉娜是中等身高，所以她很容易買衣服。)" },
        { word: "heat", translate: "高溫;熱度", sentence: "Jenny always wears a jacket, even in the heat of summer. (珍妮總是穿著一件夾克，即使在炎熱的夏天。)" },
        { word: "fill", translate: "充滿", sentence: "Sally felt sad, and her eyes were filled with tears. (莎莉感到悲傷，她的眼睛充滿了淚水。)" },
        { word: "mop", translate: "拖把", sentence: "Please give me a mop. I need to clean the floor. (請給我一把拖把。我需要清理地板。)" },
        { word: "cause", translate: "導致", sentence: "I hope I haven't caused you too much trouble. (我希望我沒有給你造成太大的麻煩。)" },
        { word: "lid", translate: "蓋子", sentence: "Put the lid on the pot to keep the food warm. (把蓋子蓋在鍋上以保持食物溫暖。)" },
        { word: "break out", translate: "突然發生", sentence: "Suddenly, BOOM! A fire broke out. (突然，砰！一場火災發生了。)" },
        { word: "refrigerator", translate: "冰箱", sentence: "You can put the food in the refrigerator to keep it fresh. (你可以把食物放進冰箱裡以保持新鮮。)" },
        { word: "stranger", translate: "陌生人", sentence: "I don't know the man in front of the store. He is a stranger to me. (我不認識店前面的那個男人。對我來說他是個陌生人。)" },
        { word: "either ... or ...", translate: "不是...就是...", sentence: "I'm not sure where Helen is. She is either at home or in her office. (我不確定海倫在哪裡。她不是在家就是在她的辦公室。)" },
        { word: "neither ... nor ...", translate: "既不...也不...", sentence: "Matt can play neither badminton nor baseball. (麥特既不會打羽毛球也不會打棒球。)" },
        { word: "replace", translate: "替換;取代", sentence: "The car that my dad drives to work has broken down many times. He now wants to replace it. (我爸爸開去上班的車已經拋錨過很多次了。他現在想換掉它。)" }
    ],
    "Lesson 2": [
        { word: "widely", translate: "廣泛地", sentence: "The design has been widely used for years. You can see it everywhere. (這個設計已經被廣泛使用了多年。你到處都可以看到它。)" },
        { word: "top", translate: "頂尖的", sentence: "Which school is the top in the whole world? (哪所學校是全世界頂尖的？)" },
        { word: "string", translate: "弦;線", sentence: "My dad taught me how to choose string for my badminton racket yesterday. (我爸爸昨天教我如何為我的羽毛球拍選擇線。)" },
        { word: "exercise", translate: "運動", sentence: "Jasper exercises in the gym every evening after work. / Playing badminton is my favorite exercise. (賈斯柏每天下班後在健身房運動。 / 打羽毛球是我最喜歡的運動。)" },
        { word: "high-quality", translate: "高品質的", sentence: "Masks made in Taiwan are very high-quality and popular around the world. (臺灣製造的口罩品質非常高，在世界各地都很受歡迎。)" },
        { word: "product", translate: "產品", sentence: "These ten products are the most popular in Japan, and now we can also buy them in Taiwan. (這十項產品在日本最受歡迎，現在我們在臺灣也買得到。)" },
        { word: "electronic", translate: "電子的", sentence: "I need to buy a new electronic device for my home office. (我需要為我的家庭辦公室買一個新的電子裝置。)" },
        { word: "racket", translate: "球拍", sentence: "Randy bought a new tennis racket for the big game. (蘭迪為了這場重要比賽買了一把新的網球拍。)" },
        { word: "brand", translate: "品牌", sentence: "I couldn't find my favorite brand of pen at the bookstore, so I didn't buy one. (我在書店找不到我最喜歡的鋼筆品牌，所以我沒買。)" },
        { word: "microchip", translate: "晶片", sentence: "The vet scanned the lost dog's microchip to find its owner. (獸醫掃描了走失狗的晶片以尋找牠的主人。)" },
        { word: "device", translate: "裝置", sentence: "The GPS device in the car helps us find our way to new places. (車上的GPS裝置幫助我們找到去新地方的路。)" },
        { word: "local", translate: "當地人", sentence: "Sara loves to make friends with the locals when she travels to a foreign land. (莎拉去外國旅行時喜歡結交當地人為友。)" },
        { word: "world-class", translate: "世界級的", sentence: "Its products are widely used by many world-class players. (它的產品被許多世界級的選手廣泛使用。)" },
        { word: "on the other hand", translate: "另一方面", sentence: "It was a sad story, but on the other hand, people can still learn from it. (這是個悲傷的故事，但另一方面，人們仍然可以從中學習。)" },
        { word: "glasses", translate: "眼鏡", sentence: "I am still trying to get used to my new pair of glasses. They are heavier than the other pair. (我還在努力習慣我的新眼鏡。它們比另一副重。)" },
        { word: "item", translate: "品項", sentence: "There are a lot of items to choose from on the menu. So, it's difficult to decide what to eat. (菜單上有很多品項可以選擇。所以很難決定要吃什麼。)" },
        { word: "space", translate: "空間", sentence: "Stop buying more new clothes! There isn't any more space to store them in your bedroom. (不要再買新衣服了！你的臥室裡沒有更多空間存放它們了。)" },
        { word: "decide", translate: "決定", sentence: "Kelly decided to go jogging with Ken this weekend. (凱莉決定這個週末和肯一起去慢跑。)" },
        { word: "middle", translate: "中間", sentence: "Mandy, please stand in the middle of the room when I take the picture. (曼蒂，我拍照時請站在房間中間。)" },
        { word: "download", translate: "下載", sentence: "You can download the files you need from the website. (你可以從網站上下載你需要的檔案。)" },
        { word: "file", translate: "檔案", sentence: "Don't forget to save the file or you will have to do it again. (別忘了儲存檔案，否則你得重做一次。)" },
        { word: "error", translate: "錯誤", sentence: "Make sure there are no spelling errors before you turn in your report. (交報告前確保沒有拼字錯誤。)" },
        { word: "traffic", translate: "交通", sentence: "Drive carefully. There is a lot of traffic on the road. (小心駕駛。路上有很多車流。)" },
        { word: "crash", translate: "當機", sentence: "My laptop crashed again this morning. Now, I cannot type my report. (我的筆記型電腦今天早上又當機了。現在我無法打我的報告。)" },
        { word: "while", translate: "在...的時候", sentence: "Kelly got a message from one of her LINE groups while she was watching TV. (凱莉看電視時收到了一個她LINE群組的訊息。)" }
    ],
    "Lesson 3": [
        { word: "Easter", translate: "復活節", sentence: "Easter usually falls on a Sunday between 22 March and 25 April. (復活節通常落在3月22日至4月25日之間的星期日。)" },
        { word: "reach", translate: "抵達;觸及", sentence: "As soon as Stephen reached Tokyo, his brother came to pick him up. (史蒂芬一抵達東京，他哥哥就來接他。)" },
        { word: "dot", translate: "分佈;點", sentence: "The big lake is dotted with many colorful boats. / A plane looks like a dot when it is flying in the sky. (這座大湖上點綴著許多色彩繽紛的小船。 / 飛機在天空中飛行時看起來像個小點。)" },
        { word: "center", translate: "中心", sentence: "There are a lot of shops, offices, and banks in the center of town. (鎮中心有很多商店、辦公室和銀行。)" },
        { word: "business", translate: "商業", sentence: "Ever since Mark started his business at the age of 25, he has been rich. (自從馬克25歲創業以來，他一直很富有。)" },
        { word: "mysterious", translate: "神秘的", sentence: "The island is one of the most mysterious places in the world. (這座島嶼是世界上最神秘的地方之一。)" },
        { word: "ancestor", translate: "祖先", sentence: "People in Mexico show respect to their ancestors on the Day of the Dead. (墨西哥人在亡靈節對他們的祖先表示敬意。)" },
        { word: "respect", translate: "尊重", sentence: "I have a lot of respect for my teacher. / I respect Tom because he is not afraid to speak up for what's right. (我非常尊重我的老師。 / 我尊重湯姆，因為他不害怕為正確的事情發聲。)" },
        { word: "guest", translate: "客人", sentence: "The guests were invited to Mr. Wang's birthday party. (客人們被邀請參加王先生的生日派對。)" },
        { word: "culture", translate: "文化", sentence: "Eating rice is a key part of Taiwanese food culture. (吃米飯是臺灣飲食文化的重要部分。)" },
        { word: "faraway", translate: "遙遠的", sentence: "Although it is not easy to reach, the famous and mysterious moai on this faraway island have made it one of the most popular World Heritage Sites. (雖然不容易抵達，這座遙遠島嶼上著名且神祕的摩艾石像，使其成為最受歡迎的世界遺產之一。)" },
        { word: "honor", translate: "向...致敬", sentence: "Some people believe that moai were built to honor the islanders' ancestors or other important people. (有些人相信建造摩艾石像是為了向島民的祖先或其他重要人物致敬。)" },
        { word: "watch over", translate: "保護;照顧", sentence: "The Rapa Nui believe that moai watch over and protect them. (拉帕努伊人相信摩艾石像看守並保護著他們。)" },
        { word: "on top of that", translate: "除...之外", sentence: "On top of that, some tourists have climbed on the statues and even damaged them. (除此之外，有些遊客爬上雕像甚至破壞了它們。)" },
        { word: "local", translate: "當地的", sentence: "So, it is important to respect the local culture. (因此，尊重當地文化是很重要的。)" },
        { word: "R.O.C.", translate: "中華民國", sentence: "The postcard was sent to Taiwan, R.O.C. (這張明信片被寄到中華民國臺灣。)" },
        { word: "stamp", translate: "郵票", sentence: "Annie likes to collect stamps, and so does David. (安妮喜歡收集郵票，大衛也是。)" },
        { word: "paste", translate: "黏貼", sentence: "The notice that was pasted on the wall this morning is now gone. (今天早上黏在牆上的通知現在不見了。)" },
        { word: "package", translate: "包裹", sentence: "Jimmy got a big package on his birthday. Inside the package was a teddy bear. (吉米在生日時收到一個大包裹。包裹裡面有一隻泰迪熊。)" },
        { word: "size", translate: "尺寸", sentence: "This pair of shoes is too small. Do you have a bigger size? (這雙鞋太小了。你們有大一點的尺寸嗎？)" },
        { word: "sentence", translate: "句子", sentence: "Could you please say the last sentence again? (能請你把最後一個句子再說一次嗎？)" },
        { word: "language", translate: "語言", sentence: "Tom is very smart. He could speak five languages at the age of twelve. (湯姆非常聰明。他在十二歲時就會說五種語言。)" },
        { word: "note", translate: "說明;筆記", sentence: "Students who know how to take notes usually do better on tests. (知道如何做筆記的學生通常在考試中表現得更好。)" }
    ],
    "Lesson 4": [
        { word: "gate", translate: "大門", sentence: "Who left the gate open? My puppy got out. (誰讓大門開著？我的小狗跑出去了。)" },
        { word: "blank", translate: "空白的", sentence: "Please write your name and phone number in the blank space on the paper. (請把你的名字和電話號碼寫在紙上的空白處。)" },
        { word: "pocket money", translate: "零用錢", sentence: "Sara saved all of her pocket money because she wanted to buy an expensive gift. (莎拉存下了她所有的零用錢，因為她想買一個昂貴的禮物。)" },
        { word: "bake", translate: "烘焙", sentence: "Do you know how to bake a cake? (你知道如何烘焙蛋糕嗎？)" },
        { word: "gram", translate: "公克", sentence: "Put 125 grams of sugar in a bowl of water. (把125公克的糖放入一碗水中。)" },
        { word: "bite", translate: "一口之量", sentence: "Can I have a bite of your bread? (我可以咬一口你的麵包嗎？)" },
        { word: "joke", translate: "玩笑", sentence: "I hope these jokes will cheer you up. (我希望這些笑話能讓你振作起來。)" },
        { word: "fail", translate: "失敗;未能做到", sentence: "Sara failed math but passed all of her other subjects. (莎拉數學不及格，但其他所有科目都及格了。)" },
        { word: "until", translate: "直到", sentence: "Mark was up until 1 a.m. because he was busy doing his homework. (馬克熬夜直到凌晨一點，因為他忙著做功課。)" },
        { word: "hobby", translate: "嗜好", sentence: "Reading has been a hobby of mine since I was a teenager. (從我十幾歲起，閱讀就是我的一個嗜好。)" },
        { word: "seat", translate: "座椅;座位", sentence: "Sir, have a seat, please. Your drinks will be ready in a minute. (先生，請坐。您的飲料馬上就準備好。)" },
        { word: "fix", translate: "修理", sentence: "My computer is broken. I need to have someone fix it ASAP. (我的電腦壞了。我需要找人盡快修理它。)" },
        { word: "graduate", translate: "畢業", sentence: "What are you going to do in the summer after you graduate? (你畢業後的夏天打算做什麼？)" },
        { word: "bulletin board", translate: "佈告欄", sentence: "Miss Lee wrote an important notice on the bulletin board. (李老師在佈告欄上寫了一個重要的通知。)" },
        { word: "weird", translate: "奇怪的", sentence: "My dad's car makes a weird sound when he drives it. (我爸爸開車時，車子會發出奇怪的聲音。)" },
        { word: "support", translate: "支持", sentence: "I would like to say thank you to everyone who supported me. (我想對每一個支持我的人說聲謝謝。)" },
        { word: "root", translate: "根源;原因", sentence: "Staying up late is the root of your health problem. (熬夜是你健康問題的根源。)" },
        { word: "What's the matter?", translate: "怎麼了?", sentence: "What's the matter? You don't look well. (怎麼了？你看起來不太好。)" },
        { word: "knowledge", translate: "知識", sentence: "To my knowledge, no one has ever climbed to the top of that mountain. (據我所知，從來沒有人爬到那座山頂過。)" },
        { word: "define", translate: "定義", sentence: "Please define this word in the sentence and explain it to your classmates. (請定義這個字在句子中的意思並向你的同班同學解釋。)" },
        { word: "bow", translate: "鞠躬", sentence: "People bow to the gods while they are praying in the temple. (人們在寺廟裡祈禱時會向神明鞠躬。)" },
        { word: "fix", translate: "解決(問題)", sentence: "You helped us to get to the root of our problems, and you also helped us fix them. (你幫助我們找到了問題的根源，你也幫助我們解決了它們。)" }
    ]
};