// 確保全域變數存在
if (typeof window.englishDb === 'undefined') { window.englishDb = {}; }
if (!window.englishDb["康軒"]) { window.englishDb["康軒"] = {}; }

// ==========================================
// 康軒 2下 (L1~L6) 完整字庫 (全單字 + 完整中文翻譯例句)
// ==========================================
window.englishDb["康軒"]["二下"] = {
    "Lesson 1": [
        { word: "dress", translate: "洋裝", sentence: "Amy bought a fashionable dress for her birthday party. (艾美為了她的生日派對買了一件時尚的洋裝。)" },
        { word: "on sale", translate: "特價", sentence: "The clothes in this shop are on sale, so they're cheaper now. (這家店的衣服在特價，所以現在比較便宜。)" },
        { word: "shirt", translate: "襯衫", sentence: "Matthew is wearing a blue shirt to work. (馬修穿著一件藍色襯衫去上班。)" },
        { word: "shorts", translate: "短褲", sentence: "Larry usually wears shorts in the summer. (賴瑞夏天通常穿短褲。)" },
        { word: "jeans", translate: "牛仔褲", sentence: "Nick spent three thousand NT dollars on this pair of jeans. (尼克花了三千台幣買這件牛仔褲。)" },
        { word: "sweater", translate: "毛衣", sentence: "Jennifer is wearing jeans and a sweater today. (珍妮佛今天穿著牛仔褲和毛衣。)" },
        { word: "jacket", translate: "夾克", sentence: "It's cold outside. Put on your jacket. (外面很冷。穿上你的夾克吧。)" },
        { word: "skirt", translate: "裙子", sentence: "This skirt comes in three colors: red, black, and brown. (這件裙子有三種顏色：紅色、黑色和棕色。)" },
        { word: "ring", translate: "戒指", sentence: "Patty is wearing a ring on her middle finger. (佩蒂的中指上戴著一枚戒指。)" },
        { word: "sock", translate: "襪子", sentence: "Lisa never wears shoes without socks. (麗莎從不穿鞋不穿襪子。)" },
        { word: "cap", translate: "帽子", sentence: "The man is wearing a black cap. (那個男人戴著一頂黑色的帽子。)" },
        { word: "tie", translate: "領帶", sentence: "Michael has to wear a shirt and tie at work. (麥可上班時必須穿襯衫打領帶。)" },
        { word: "belt", translate: "腰帶", sentence: "Ivy bought her father a belt as his birthday gift. (艾薇買了一條腰帶給她爸爸當生日禮物。)" },
        { word: "pants", translate: "長褲", sentence: "These pants were too long for me, so I didn't buy them. (這件長褲對我來說太長了，所以我沒買。)" },
        { word: "wallet", translate: "錢包", sentence: "Jason had only twenty NT dollars in his wallet. (傑森的錢包裡只有二十元台幣。)" },
        { word: "a pair of", translate: "一件;一雙", sentence: "I bought a pair of pants on the Internet last week. (我上週在網路上買了一件長褲。)" },
        { word: "glove", translate: "手套", sentence: "Emily bought a pair of gloves in the department store. (艾蜜莉在百貨公司買了一雙手套。)" },
        { word: "try on", translate: "試穿", sentence: "This jacket is too big. Can I try on a smaller one? (這件夾克太大了。我可以試穿小一點的嗎？)" },
        { word: "take off", translate: "脱下", sentence: "Please take off your hat when you go into the building. (進入建築物時請脫帽。)" },
        { word: "be full of", translate: "充滿", sentence: "This restaurant is really popular, so it's always full of people. (這家餐廳很受歡迎，所以總是充滿了人。)" },
        { word: "fashionable", translate: "流行的;時尚的", sentence: "Your jeans are so fashionable. Where did you get them? (你的牛仔褲好時尚。你從哪裡買的？)" },
        { word: "as... as...", translate: "如同...一樣地", sentence: "Exercise is as important as a good night's sleep. (運動和一夜好眠一樣重要。)" },
        { word: "than", translate: "比;比較", sentence: "Your bag is heavier than mine. What did you put in it? (你的包包比我的重。你裡面放了什麼？)" },
        { word: "already", translate: "已經", sentence: "Mia wants to buy more shoes, but she already has 50 pairs. (米亞想買更多鞋子，但她已經有50雙了。)" },
        { word: "fashion", translate: "流行;時尚", sentence: "Short hair is in fashion for girls now. (短髮現在在女孩中很流行。)" },
        { word: "medium", translate: "中等尺寸;中等的", sentence: "Ann: What size do you wear? Ben: I wear a medium. (安：你穿什麼尺寸？班：我穿中號。)" },
        { word: "fitting room", translate: "試衣間", sentence: "Paul is trying on the jeans in the fitting room. (保羅正在試衣間試穿牛仔褲。)" },
        { word: "agree", translate: "同意", sentence: "Jay: Eric is kind and always helps others. Ed: I agree. He is a nice person. (傑：艾瑞克很親切，總是幫助別人。艾德：我同意。他是個好人。)" },
        { word: "comfortable", translate: "舒服的", sentence: "I am not comfortable in these shoes. They are too small. (我穿這雙鞋不舒服。它們太小了。)" },
        { word: "light", translate: "輕薄的", sentence: "This jacket is really light and comfortable. I'll take it. (這件夾克非常輕薄舒適。我要買它。)" },
        { word: "recycle", translate: "回收", sentence: "Can you recycle old clothes? (你可以回收舊衣服嗎？)" },
        { word: "planet", translate: "星球", sentence: "Is there life on other planets? (其他星球上有生命嗎？)" },
        { word: "business", translate: "公司;生意", sentence: "Helen started a new business with her friends. (海倫和她的朋友們創辦了一家新公司。)" },
        { word: "customer", translate: "顧客", sentence: "The department store is full of customers. (百貨公司裡充滿了顧客。)" },
        { word: "actually", translate: "實際上", sentence: "Actually, I have a test tomorrow and can't go to the party. (實際上，我明天有考試，不能去派對。)" },
        { word: "owner", translate: "所有人", sentence: "Mars is the owner of this white car. (馬斯是這輛白車的車主。)" },
        { word: "item", translate: "項目", sentence: "The restaurant has a long menu of about 60 items. (這家餐廳有大約60個品項的長菜單。)" },
        { word: "fresh", translate: "新鮮的", sentence: "Would you like some fresh strawberries? (你想要一些新鮮的草莓嗎？)" },
        { word: "mean", translate: "意指", sentence: "Larry: What does 'clever' mean? Berry: It means 'smart.' (賴瑞：'clever' 是什麼意思？貝瑞：意思是 '聰明'。)" },
        { word: "Earth", translate: "地球", sentence: "There are many beautiful animals on Earth. (地球上有許多美麗的動物。)" },
        { word: "turn into", translate: "成為...", sentence: "The woman turned the old coat into a new bag. (這個女人把舊外套變成了一個新包包。)" }
    ],
    "Lesson 2": [
        { word: "sofa", translate: "沙發", sentence: "My pet cat is under the sofa. (我的寵物貓在沙發底下。)" },
        { word: "lamp", translate: "燈", sentence: "Turn on the desk lamp before you start reading. (開始閱讀前請打開檯燈。)" },
        { word: "piano", translate: "鋼琴", sentence: "Rebecca practices the piano every night. (蕾貝卡每天晚上練習鋼琴。)" },
        { word: "radio", translate: "收音機", sentence: "My grandpa used to listen to the radio every morning. (我爺爺以前每天早上都會聽收音機。)" },
        { word: "washing machine", translate: "洗衣機", sentence: "Nick put his dirty clothes in the washing machine. (尼克把他的髒衣服放進洗衣機裡。)" },
        { word: "refrigerator", translate: "冰箱", sentence: "We put milk in the refrigerator to stop it from going bad. (我們把牛奶放進冰箱以防它變壞。)" },
        { word: "violin", translate: "小提琴", sentence: "It is not easy to learn to play the violin. (學習拉小提琴並不容易。)" },
        { word: "bow", translate: "琴弓", sentence: "The seller showed us the best bow in his store. (賣家向我們展示了他店裡最好的琴弓。)" },
        { word: "tape", translate: "膠帶", sentence: "I need some tape to fix my broken book. (我需要一些膠帶修補我破損的書。)" },
        { word: "concert", translate: "演唱會;音樂會", sentence: "I'll play the piano at the concert next Saturday. (下週六我將在音樂會上彈鋼琴。)" },
        { word: "turn on", translate: "打開(電器)", sentence: "I turned on the TV to watch my favorite show. (我打開電視看我最喜歡的節目。)" },
        { word: "turn off", translate: "關上(電器)", sentence: "Remember to turn off the lamp before you leave the room. (離開房間前記得關燈。)" },
        { word: "screen", translate: "螢幕", sentence: "The photo on your cellphone screen is beautiful. (你手機螢幕上的照片很美。)" },
        { word: "power bank", translate: "行動電源", sentence: "Dave: My phone is out. Fred: Don't worry. You can use my power bank. (戴夫：我手機沒電了。弗雷德：別擔心。你可以用我的行動電源。)" },
        { word: "out of order", translate: "故障的", sentence: "The toilet is out of order. We can't use it now. (馬桶故障了。我們現在不能用。)" },
        { word: "sweet", translate: "甜的;甜蜜的", sentence: "For Debbie, being a mother is the sweetest thing in the world. (對黛比來說，當媽媽是世界上最甜蜜的事。)" },
        { word: "most", translate: "最;最多的", sentence: "Emma is the most popular student in my class. (艾瑪是我班上最受歡迎的學生。)" },
        { word: "envelope", translate: "信封", sentence: "I wrote a letter to my mom and put it in an envelope. (我寫了一封信給媽媽並把它放進信封裡。)" },
        { word: "used to", translate: "過去經常", sentence: "I used to take photos with a camera, but now I use my smartphone. (我以前常相機拍照，但現在我都用智慧型手機。)" },
        { word: "useful", translate: "有用的", sentence: "This book is very useful to me. I need it to do my science report. (這本書對我很有用。我需要它來做我的科學報告。)" },
        { word: "fake", translate: "假的", sentence: "The woman used a fake name at the hotel. (這名女子在飯店使用了假名。)" },
        { word: "deal", translate: "交易", sentence: "The jeans only cost NT$200. It's a great deal. (這件牛仔褲只要200元台幣。這是一筆很划算的交易。)" },
        { word: "scam", translate: "詐騙", sentence: "There are a lot of online stores, and some are scams. You need to be careful. (有很多網路商店，有些是詐騙。你需要小心。)" },
        { word: "strange", translate: "奇怪的;陌生的", sentence: "There is a strange woman behind the tree. Who is she? (樹後面有一個陌生的女人。她是誰？)" },
        { word: "joke", translate: "玩笑;笑話", sentence: "This is not a joke, and we must act right now. (這不是開玩笑，我們必須現在就行動。)" },
        { word: "seller", translate: "賣家", sentence: "They are the largest seller of books in Taiwan. (他們是台灣最大的圖書賣家。)" },
        { word: "anymore", translate: "再也(不)", sentence: "Sam doesn't live here anymore. He moved to Tainan last month. (山姆再也不住這裡了。他上個月搬到台南了。)" },
        { word: "stop by", translate: "順道拜訪", sentence: "I will stop by your house tomorrow after lunch. (我明天午餐後會順道拜訪你家。)" },
        { word: "pick up", translate: "取(某物)", sentence: "Can you pick up the tickets on your way home from work? (你下班回家的路上能順便取票嗎？)" },
        { word: "trick", translate: "欺騙;騙局", sentence: "Sue is planning to play a trick on her brother. (蘇正計畫捉弄她弟弟。)" },
        { word: "billion", translate: "十億", sentence: "There are over one billion people in India. (印度有超過十億人口。)" },
        { word: "part", translate: "部分", sentence: "Jerry: What's your favorite part of this song? Gina: The last minute. (傑瑞：這首歌你最喜歡哪個部分？吉娜：最後一分鐘。)" },
        { word: "tip", translate: "提示;指導", sentence: "My mother gave me some useful tips for buying watermelons. (我媽媽給了我一些買西瓜的實用提示。)" },
        { word: "information", translate: "資料;消息", sentence: "I need some information about good restaurants in Taipei. (我需要一些台北好餐廳的資訊。)" },
        { word: "stranger", translate: "陌生人", sentence: "Elisa told her daughter not to talk to strangers. (艾麗莎告訴她女兒不要和陌生人說話。)" },
        { word: "secret", translate: "祕密(的)", sentence: "John and his wife have no secrets from each other. (約翰和他的妻子對彼此沒有秘密。)" },
        { word: "word", translate: "字", sentence: "Those words are too difficult for Mike. He's just five. (這些字對麥克來說太難了。他才五歲。)" },
        { word: "sentence", translate: "句子", sentence: "I don't know the meaning of this Japanese sentence. Could you explain it to me? (我不知道這個日文句子的意思。你能解釋給我聽嗎？)" },
        { word: "tell from", translate: "區分...與", sentence: "Ms. Lee can't tell Paul from his brother Mark. (李老師無法分辨保羅和他的哥哥馬克。)" },
        { word: "stay", translate: "保持", sentence: "The department store stays open until 10 p.m. (百貨公司保持營業到晚上十點。)" }
    ],
    "Lesson 3": [
        { word: "salad", translate: "沙拉", sentence: "I had some salad with my steak. (我吃牛排配了些沙拉。)" },
        { word: "hamburger", translate: "漢堡", sentence: "The fast food restaurant is famous for its burgers. (這家速食餐廳以其漢堡聞名。)" },
        { word: "coffee", translate: "咖啡", sentence: "Ken couldn't sleep last night because he drank too much coffee. (肯昨晚睡不著，因為他喝了太多咖啡。)" },
        { word: "steak", translate: "牛排", sentence: "Patty ordered a steak at the restaurant. (佩蒂在餐廳點了一份牛排。)" },
        { word: "French fries", translate: "薯條", sentence: "I would like to order some French fries without salt. (我想要點一些不加鹽的薯條。)" },
        { word: "fried chicken", translate: "炸雞", sentence: "Fred eats fried chicken three times a week. (弗雷德一週吃三次炸雞。)" },
        { word: "ham", translate: "火腿", sentence: "Dan usually has a ham sandwich and milk for breakfast. (丹早餐通常吃火腿三明治和牛奶。)" },
        { word: "cheese", translate: "起司", sentence: "Blue cheese smells bad but tastes good. (藍紋起司聞起來很臭但嚐起來很好吃。)" },
        { word: "pork", translate: "豬肉", sentence: "Al and his family don't eat pork. (艾爾和他的家人不吃豬肉。)" },
        { word: "bean soup", translate: "豆子湯", sentence: "My mom's bean soup is delicious. We can't get enough of it. (我媽媽的豆子湯很美味。我們百喝不厭。)" },
        { word: "vegetable", translate: "蔬菜", sentence: "I had a bowl of vegetable soup for lunch. (我午餐喝了一碗蔬菜湯。)" },
        { word: "pizza", translate: "披薩", sentence: "Ivy ate all the pizza without sharing it with her friends. (艾薇把披薩全吃了，沒有和朋友分享。)" },
        { word: "bun", translate: "小圓麵包", sentence: "Some people don't eat the buns when they have a hamburger. (有些人吃漢堡時不吃小圓麵包。)" },
        { word: "toast", translate: "烤麵包片", sentence: "Jim always puts butter on his toast. (吉姆總是在烤麵包上塗奶油。)" },
        { word: "meat", translate: "肉", sentence: "Chicken is white meat, and beef is red meat. (雞肉是白肉，牛肉是紅肉。)" },
        { word: "bread", translate: "麵包", sentence: "Would you like some bread and butter? (你想要一些麵包和奶油嗎？)" },
        { word: "wall", translate: "牆壁", sentence: "William put pictures on the walls of his bedroom. (威廉把照片掛在他臥室的牆上。)" },
        { word: "meal", translate: "一餐", sentence: "Gina cooks three meals for her family every day. (吉娜每天為家人煮三餐。)" },
        { word: "oil", translate: "油", sentence: "Maggie started to cook the chicken with some oil. (瑪姬開始用一些油煮雞肉。)" },
        { word: "sound", translate: "聽起來", sentence: "Ian: What do you think about my plan? Lily: It sounds good. (伊恩：你覺得我的計畫怎麼樣？莉莉：聽起來不錯。)" },
        { word: "weight", translate: "體重", sentence: "Tommy lost a lot of weight when he was sick. (湯米生病時瘦了很多。)" },
        { word: "smell", translate: "聞起來", sentence: "The vegetable soup smells good. Who made it? (蔬菜湯聞起來很香。是誰做的？)" },
        { word: "taste", translate: "嘗起來", sentence: "The fried rice tasted good. I couldn't stop eating it. (炒飯嚐起來很好吃。我忍不住一直吃。)" },
        { word: "dig in", translate: "開始吃", sentence: "Let's dig in before the food gets cold. (我們在食物變冷前開動吧。)" },
        { word: "soon", translate: "很快地", sentence: "Gemma is going to be a mother soon. (潔瑪很快就要當媽媽了。)" },
        { word: "order", translate: "點餐;訂購", sentence: "Excuse me. May I take your order, sir? (打擾一下。先生，可以為您點餐了嗎？)" },
        { word: "put on", translate: "增加(體重)", sentence: "I don't eat a lot because I'm afraid of putting on weight. (我吃不多，因為我怕體重增加。)" },
        { word: "get", translate: "變得", sentence: "Eat your soup first, or it will get cold. (先喝你的湯，否則它會變冷。)" },
        { word: "notice", translate: "注意;看到", sentence: "Zack: Dad is back. Liza: I know. I noticed his car outside. (柴克：爸爸回來了。麗莎：我知道。我注意到他的車在外面。)" },
        { word: "invite", translate: "邀請", sentence: "Jordan invited us to his party last weekend. (喬登滿上週末邀請我們去他的派對。)" },
        { word: "besides", translate: "此外;而且", sentence: "I don't want to eat out. Besides, I don't have any money. (我不想在外面吃。而且，我沒錢了。)" },
        { word: "probably", translate: "也許", sentence: "Helen likes the green T-shirt, so she will probably buy it. (海倫喜歡那件綠色T恤，所以她也許會買它。)" },
        { word: "bite", translate: "一口的量;咬", sentence: "Nick took a bite of the sandwich. (尼克咬了一口三明治。)" },
        { word: "stand for", translate: "代表", sentence: "The flowers stand for my love. (這些花代表我的愛。)" },
        { word: "matter", translate: "有關係", sentence: "To Julie, her children matter the most in the world. (對茱莉來說，她的孩子是世界上最重要的。)" },
        { word: "sign", translate: "標誌", sentence: "The sign on the wall says 'Wash hands before you eat.' (牆上的標誌寫著「飯前請洗手」。)" },
        { word: "friendly", translate: "令人愉快的", sentence: "Mr. Chen's restaurant is friendly. My family and I feel happy and comfortable there. (陳先生的餐廳令人感到愉快。我和我的家人在那裡感到快樂又舒適。)" }
    ],
    "Lesson 4": [
        { word: "set up", translate: "搭(帳篷);建立", sentence: "It's getting dark. Let's set up camp quickly. (天快黑了。我們快點搭帳篷吧。)" },
        { word: "make a fire", translate: "生火", sentence: "Be careful when you make a fire. (生火時要小心。)" },
        { word: "boil", translate: "煮沸", sentence: "I am boiling water for the tea. (我正在為泡茶燒水。)" },
        { word: "bug", translate: "蟲", sentence: "James caught some bugs. (詹姆斯抓了一些蟲子。)" },
        { word: "picnic", translate: "野餐", sentence: "Let's go on a picnic at the park today. (我們今天去公園野餐吧。)" },
        { word: "hang out", translate: "晾(掛)", sentence: "Dad hung out the clothes to dry. (爸爸把衣服掛出去晾乾。)" },
        { word: "towel", translate: "毛巾", sentence: "Howard dried his hands with the towel. (霍華德用毛巾擦乾雙手。)" },
        { word: "lie", translate: "躺下", sentence: "Max lay down and took a rest. (麥克斯躺下來休息了一會兒。)" },
        { word: "grass", translate: "草地", sentence: "The sign reads, 'Keep off the grass.' (標誌上寫著「請勿踐踏草皮」。)" },
        { word: "string lights", translate: "繩燈", sentence: "We put string lights around the trees for the party. (我們為了派對在樹上掛了繩燈。)" },
        { word: "moon", translate: "月亮", sentence: "We can usually see a full moon during the Mid-Autumn Festival. (我們通常可以在中秋節看到滿月。)" },
        { word: "count", translate: "數數;計算", sentence: "Count to ten before we start the game. (在我們開始遊戲前數到十。)" },
        { word: "pack", translate: "打包", sentence: "Sandy was still packing her bag when the taxi came. (當計程車來的時候，珊迪還在打包行李。)" },
        { word: "perfect", translate: "完美的", sentence: "David had perfect weather during his vacation in Japan. (大衛在日本度假時天氣非常完美。)" },
        { word: "be able to", translate: "能夠", sentence: "The young birds are able to fly now. (幼鳥現在能飛了。)" },
        { word: "well", translate: "很好地", sentence: "I didn't sleep well because I had a bad dream. (我睡得不好，因為我做了一個惡夢。)" },
        { word: "loudly", translate: "大聲地", sentence: "Sorry, I can't hear you clearly. Please speak loudly. (抱歉，我聽不清楚。請大聲點說。)" },
        { word: "slowly", translate: "緩慢地", sentence: "The sun went down slowly behind the mountains. (太陽在山後緩緩落下。)" },
        { word: "gently", translate: "輕柔地", sentence: "Emily closed the door gently because Tim was sleeping. (艾蜜莉輕輕地關上門，因為提姆在睡覺。)" },
        { word: "smile", translate: "微笑", sentence: "The old woman smiled at me after I helped her. (我幫助那位老婦人後，她對我微笑了。)" },
        { word: "hop", translate: "單腳跳躍", sentence: "The boy didn't walk but hopped along the sidewalk. (那個男孩不是用走的，而是沿著人行道跳著走。)" },
        { word: "dancing queen", translate: "舞后", sentence: "Ann is a dancing queen. She dances the best at school. (安是舞后。她是學校裡跳舞最棒的。)" },
        { word: "hard", translate: "努力地", sentence: "Tim studies hard and plays hard. (提姆努力學習也盡情玩樂。)" },
        { word: "trip", translate: "絆倒", sentence: "Andy ran too fast and tripped. (安迪跑太快絆倒了。)" },
        { word: "experience", translate: "經歷", sentence: "I took a trip to the USA last month. It was a great experience for me. (我上個月去美國旅行。這對我來說是個很棒的經歷。)" },
        { word: "diary", translate: "日記", sentence: "Ben keeps a diary about his school life. (班有寫關於他學校生活的日記。)" },
        { word: "arrive", translate: "抵達", sentence: "Ann: What time will the train arrive in Taipei? Ben: At five. (安：火車什麼時候會抵達台北？班：五點。)" },
        { word: "area", translate: "區域", sentence: "It will rain in all areas of this country this afternoon. (今天下午這個國家的所有地區都會下雨。)" },
        { word: "successfully", translate: "成功地", sentence: "Paula played the piano successfully at the show. (寶拉在表演中成功地彈奏了鋼琴。)" },
        { word: "pot", translate: "鍋子;壺", sentence: "There is a pot of chicken soup in the kitchen. (廚房裡有一鍋雞湯。)" },
        { word: "burn", translate: "燒焦", sentence: "Sam didn't enjoy his dinner because his steak burned. (山姆晚餐吃得不開心，因為他的牛排燒焦了。)" },
        { word: "unhappy", translate: "不開心的", sentence: "The workers are unhappy because they have to work on the weekend. (工人們很不開心，因為他們週末必須工作。)" },
        { word: "hold", translate: "舉辦", sentence: "The teacher will hold a meeting with the parents next week. (老師下週將會和家長們開會。)" },
        { word: "circle", translate: "圓圈", sentence: "The sun looks like a big yellow circle in the sky. (太陽看起來就像天空中一個黃色的大圓圈。)" },
        { word: "shy", translate: "害羞的", sentence: "Harry is so shy. He seldom talks in class. (哈利很害羞。他很少在課堂上說話。)" },
        { word: "line", translate: "列;隊伍", sentence: "Many people waited in line outside the bakery. (許多人在麵包店外面排隊。)" },
        { word: "laugh", translate: "笑", sentence: "Ivan laughed at the end of Eva's funny story. (伊凡在伊娃講完有趣的故事後笑了。)" },
        { word: "anyone", translate: "任何人", sentence: "There isn't anyone in the classroom. Where are the students? (教室裡沒有任何人。學生們在哪裡？)" },
        { word: "else", translate: "其他", sentence: "You ordered the soup and the sandwich. Anything else? (你點了湯和三明治。還需要其他東西嗎？)" },
        { word: "clap", translate: "拍手", sentence: "At the end of the show, one man began to clap, and the others joined in. (表演結束時，一名男子開始拍手，其他人也跟著拍手。)" },
        { word: "cheer", translate: "歡呼", sentence: "Let's cheer for Lisa! She won first place in the race. (讓我們為麗莎歡呼！她贏得了賽跑第一名。)" },
        { word: "festival", translate: "節慶", sentence: "Many people went to the movie festival last night. (昨晚許多人去參加了電影節。)" },
        { word: "heart", translate: "愛心", sentence: "Andrew drew a big heart on the card to show his love for his wife. (安德魯在卡片上畫了一顆大愛心來表達對妻子的愛。)" },
        { word: "shape", translate: "形狀", sentence: "Jim's birthday cake is in the shape of a bear. (吉姆的生日蛋糕是熊的形狀。)" },
        { word: "lucky", translate: "幸運的", sentence: "Amber: Did you find a parking space? Janet: Yes, I did! I was so lucky. (琥珀：你找到停車位了嗎？珍妮：是的，找到了！我真幸運。)" }
    ],
    "Lesson 5": [
        { word: "earthquake", translate: "地震", sentence: "No one was hurt in the earthquake this morning. (今天早上的地震沒有人受傷。)" },
        { word: "cover", translate: "遮蓋", sentence: "The boy covered his body with a blanket. (男孩用毯子蓋住身體。)" },
        { word: "typhoon", translate: "颱風", sentence: "The road signs fell in the street during the big typhoon last night. (昨晚強烈颱風期間，路標倒在街上了。)" },
        { word: "candle", translate: "蠟燭", sentence: "Please light the candle on the birthday cake. (請點燃生日蛋糕上的蠟燭。)" },
        { word: "smoke alarm", translate: "煙霧警報器", sentence: "The loud sound of the smoke alarm woke up everyone in the house. (煙霧警報器的巨大聲響吵醒了屋裡的所有人。)" },
        { word: "elevator", translate: "電梯", sentence: "My leg hurts, so I'm going to take the elevator. (我的腿很痛，所以我打算搭電梯。)" },
        { word: "raise", translate: "舉起", sentence: "Raise your hand when you have any questions. (有問題時請舉手。)" },
        { word: "pull", translate: "拉;抽出", sentence: "Jeff pulled a pen out of his pocket. (傑夫從口袋裡拿出一支筆。)" },
        { word: "push", translate: "推;按", sentence: "Lily pushed the door open and walked out. (莉莉推開門走了出去。)" },
        { word: "rich", translate: "富有的", sentence: "Mr. Smith is very rich. He has 12 big houses. (史密斯先生很有錢。他有12棟大房子。)" },
        { word: "deep", translate: "深的", sentence: "Be careful. The water is very deep here. (小心。這裡的水很深。)" },
        { word: "hold on", translate: "緊緊抓牢", sentence: "The boy held on to his mom's arm when they crossed the street. (過馬路時，男孩緊緊抓住媽媽的手臂。)" },
        { word: "abroad", translate: "在國外", sentence: "Helen and her family always go abroad in the summer. (海倫和她的家人夏天總是出國。)" },
        { word: "dangerous", translate: "危險的", sentence: "It's dangerous for you to walk by yourself at night. (晚上獨自走路對你來說很危險。)" },
        { word: "moment", translate: "時刻", sentence: "My mom made me a sandwich, but I wasn't hungry at that moment. (我媽媽幫我做了一個三明治，但那時候我不餓。)" },
        { word: "hear", translate: "聽到", sentence: "I heard my dad singing in the shower last night. (昨晚我聽到我爸爸在洗澡時唱歌。)" },
        { word: "someone", translate: "某人", sentence: "Can you ask someone else to help you? I'm busy now. (你能請別人幫你嗎？我現在很忙。)" },
        { word: "scary", translate: "嚇人的", sentence: "The story was scary. Tim couldn't sleep after he heard it. (這個故事很嚇人。提姆聽完後睡不著覺。)" },
        { word: "fall off", translate: "掉下", sentence: "Doris fell off her bike and got hurt. (桃樂絲從腳踏車上摔下來受傷了。)" },
        { word: "cut", translate: "割傷", sentence: "I cut my finger last night when I was making dinner. (昨晚我做晚餐時割傷了手指。)" },
        { word: "nothing", translate: "沒有事物", sentence: "I know nothing about Ivan. In fact, he just moved here last week. (我對伊凡一無所知。事實上，他上週才搬來這裡。)" },
        { word: "scene", translate: "場景", sentence: "In the first scene of the movie, the actress walked past the room slowly. (在電影的第一個場景中，女演員緩慢地走過房間。)" },
        { word: "leading", translate: "主要的", sentence: "Jay: Who is the leading actress in this movie? Betty: Jennifer Lawrence. (傑：這部電影的女主角是誰？貝蒂：珍妮佛·勞倫斯。)" },
        { word: "real-life", translate: "真實生活中的", sentence: "The teacher used some real-life examples to explain the idea. (老師用了一些真實生活中的例子來解釋這個概念。)" },
        { word: "ever", translate: "在任何時候", sentence: "The food at that restaurant was terrible, so I don't want to eat there ever again. (那家餐廳的食物很糟糕，所以我再也不想去那裡吃飯了。)" },
        { word: "go out", translate: "熄滅", sentence: "I couldn't see anything when the lights went out. (停電時我什麼也看不見。)" },
        { word: "lesson", translate: "教訓", sentence: "That mistake taught us a lesson. We'll never forget about it. (那個錯誤給了我們一個教訓。我們永遠不會忘記。)" },
        { word: "land", translate: "陸地", sentence: "Frogs live both in water and on land. (青蛙生活在水中和陸地上。)" },
        { word: "several", translate: "數個的", sentence: "Carl has several pets. He has two cats and a dog. (卡爾有幾隻寵物。他有兩隻貓和一隻狗。)" },
        { word: "grow", translate: "成長", sentence: "Mike is growing so fast. These clothes are too small for him. (麥克長得好快。這些衣服對他來說太小了。)" },
        { word: "gray", translate: "灰色的", sentence: "Anton: What's that big gray animal over there? Leah: It's an elephant. (安東：那邊那隻灰色的大動物是什麼？莉亞：是大象。)" },
        { word: "dozen", translate: "一打", sentence: "Remember to buy a dozen eggs on your way home. (記得在回家的路上買一打雞蛋。)" },
        { word: "scared", translate: "感到害怕的", sentence: "Hank is scared of speaking in front of people. (漢克害怕在人群面前說話。)" },
        { word: "window", translate: "窗戶", sentence: "Could you close the windows? I feel cold. (你能關上窗戶嗎？覺得有點冷。)" },
        { word: "sight", translate: "景象", sentence: "Look at all the fireflies in the dark. It's a beautiful sight. (看看黑暗中的這些螢火蟲。這是多麼美麗的景象。)" },
        { word: "surprise", translate: "驚訝", sentence: "Daisy's friends planned a birthday surprise for her. (黛西的朋友們為她策劃了一個生日驚喜。)" },
        { word: "flood", translate: "淹沒;洪水", sentence: "The heavy rain flooded some roads. (大雨淹沒了一些道路。)" },
        { word: "apartment", translate: "公寓", sentence: "The apartment building has many floors, and each floor has eight different homes. (這棟公寓大樓有很多樓層，每層有八戶不同的住家。)" },
        { word: "except", translate: "除了...之外", sentence: "The museum is open every day except Mondays. (博物館除了星期一以外每天都開放。)" },
        { word: "cookie", translate: "餅乾", sentence: "My grandma always makes delicious cookies for us when we visit her. (我奶奶在我們去拜訪她時，總是會做美味的餅乾給我們。)" },
        { word: "drawer", translate: "抽屜", sentence: "Linda put her books in the desk drawer. (琳達把書放進書桌抽屜裡。)" },
        { word: "quite", translate: "相當地", sentence: "The movie was quite interesting, and I liked the story very much. (這部電影相當有趣，我非常喜歡這個故事。)" },
        { word: "angry", translate: "生氣的", sentence: "Mr. Stark was angry about the broken plates. (史塔克先生因為盤子被打破而生氣。)" },
        { word: "fool", translate: "傻瓜", sentence: "Don't be a fool and play outside during a typhoon. (別當傻瓜在颱風天在外面玩。)" }
    ],
    "Lesson 6": [
        { word: "straw", translate: "吸管", sentence: "Linda drank her juice through a straw. (琳達用吸管喝果汁。)" },
        { word: "carry", translate: "攜帶", sentence: "Gina helped her grandma carry the heavy bag. (吉娜幫奶奶提重袋子。)" },
        { word: "metal", translate: "金屬", sentence: "You can use a metal bowl over and over again. (你可以一再重複使用金屬碗。)" },
        { word: "spoon", translate: "湯匙", sentence: "Adam is eating the soup with a spoon. (亞當正在用湯匙喝湯。)" },
        { word: "chopsticks", translate: "筷子", sentence: "In Taiwan, many people use chopsticks to eat. (在台灣，許多人用筷子吃飯。)" },
        { word: "paper", translate: "紙", sentence: "I need a piece of paper to write down your phone number. (我需要一張紙來寫下你的電話號碼。)" },
        { word: "stair", translate: "樓梯", sentence: "Ted lives on the third floor, and he usually takes the stairs. (泰德住在三樓，他通常走樓梯。)" },
        { word: "instead of", translate: "作為...替代", sentence: "Mandy brought fruit instead of flowers as a gift for her friend in the hospital. (曼蒂帶了水果而不是花，作為送給住院朋友的禮物。)" },
        { word: "jog", translate: "慢跑", sentence: "Don't jog right after dinner. It's not good for you. (晚餐後不要馬上慢跑。這對你不好。)" },
        { word: "newspaper", translate: "報紙", sentence: "I read about the sad news in the newspaper. (我在報紙上讀到了這個悲傷的新聞。)" },
        { word: "postcard", translate: "明信片", sentence: "I'll send you a postcard when I arrive in London. (我一到倫敦就會寄明信片給你。)" },
        { word: "businessman", translate: "商人", sentence: "Mr. Smith is a businessman. He sells shoes. (史密斯先生是個商人。他賣鞋子。)" },
        { word: "workbook", translate: "習作", sentence: "Class, remember to bring your workbooks to school tomorrow. (各位同學，記得明天把習作帶到學校。)" },
        { word: "bother", translate: "費心", sentence: "Leo: Do you need me to wait for you? Ally: No, don't bother. (里歐：你需要我等你嗎？艾莉：不，別麻煩了。)" },
        { word: "end up", translate: "最後成為", sentence: "We planned to just have drinks, but we ended up having a meal together. (我們本來只打算喝點飲料，但最後卻一起吃了頓飯。)" },
        { word: "ocean", translate: "海洋", sentence: "Many people are swimming in the ocean although the water is cold. (儘管水很冷，還是有許多人在海裡游泳。)" },
        { word: "turtle", translate: "海龜", sentence: "The fisherman saw two turtles swimming in the sea. (漁夫看到兩隻海龜在海裡游泳。)" },
        { word: "perhaps", translate: "也許", sentence: "The sky is getting dark. Perhaps it will rain soon. (天空變暗了。也許快下雨了。)" },
        { word: "if", translate: "如果", sentence: "Rick will stay home if it rains tomorrow. (如果明天落雨，瑞克就會待在家裡。)" },
        { word: "take action", translate: "採取行動", sentence: "We must take action if we don't want the team to lose. (如果我們不想輸掉比賽，我們必須採取行動。)" },
        { word: "though", translate: "雖然", sentence: "Eric went to school yesterday though he was sick. (艾瑞克昨天雖然生病了，還是去上學了。)" },
        { word: "break down", translate: "分解", sentence: "Plastic bags don't break down easily. (塑膠袋不容易分解。)" },
        { word: "correct", translate: "正確的", sentence: "Tom got eight correct answers on the test. (湯姆在考試中答對了八題。)" },
        { word: "feed", translate: "餵", sentence: "Ian feeds the dogs twice a day. (伊恩每天餵狗兩次。)" },
        { word: "baby", translate: "幼鳥;嬰兒", sentence: "The birds are feeding their babies in the trees. (鳥兒們正在樹上餵牠們的幼鳥。)" },
        { word: "jellyfish", translate: "水母", sentence: "You can see a lot of beautiful jellyfish in this lake. (你可以在這個湖裡看到許多美麗的水母。)" },
        { word: "die", translate: "死亡", sentence: "At the end of the story, the bad guy died and the good people lived happily. (在故事的結尾，壞人死了，好人幸福地生活。)" },
        { word: "crazy about", translate: "非常喜歡", sentence: "Pete is crazy about that new song. He listens to it all the time. (皮特非常喜歡那首新歌。他一直都在聽。)" },
        { word: "service", translate: "服務", sentence: "The service at this restaurant is very good. The waiters are always friendly. (這家餐廳的服務很好。服務生總是很友善。)" },
        { word: "excellent", translate: "優秀的", sentence: "Our new teacher is excellent. She explains things in a clear way. (我們的新老師非常優秀。她講解得很清楚。)" },
        { word: "wish", translate: "願望", sentence: "Lily's birthday wish this year is a family trip to Penghu in the summer. (莉莉今年的生日願望是夏天和家人去澎湖旅行。)" },
        { word: "garbage", translate: "垃圾", sentence: "Please take out the garbage when you leave. (離開時請把垃圾帶走。)" },
        { word: "somewhere", translate: "在某處", sentence: "This place is too noisy. Can we go somewhere else? (這個地方太吵了。我們可以去別的地方嗎？)" },
        { word: "enter", translate: "進入", sentence: "The police entered the building through the back door. (警察從後門進入了這棟大樓。)" },
        { word: "knife", translate: "刀子", sentence: "I need a knife to cut my steak. (我需要一把刀來切牛排。)" },
        { word: "fork", translate: "叉子", sentence: "The little boy is learning to eat with a fork. (這個小男孩正在學習用叉子吃飯。)" },
        { word: "choice", translate: "選擇", sentence: "You have a choice of noodles or rice for dinner. (晚餐你可以選擇麵條或米飯。)" },
        { word: "possible", translate: "可能的", sentence: "We can't win the game. It's not possible. (我們贏不了這場比賽的。這不可能。)" },
        { word: "no longer", translate: "不再", sentence: "The Simpsons moved away. They no longer live here. (辛普森一家搬走了。他們不再住在這裡了。)" },
        { word: "gladly", translate: "樂意地", sentence: "I will gladly show you around the city when you visit next month. (下個月你來參觀時，我會很樂意帶你到處看看這座城市。)" }
    ]
};