// 確保全域變數存在，以便合併多版本、多冊的字庫
if (typeof window.englishDb === 'undefined') {
    window.englishDb = {};
}
if (!window.englishDb["翰林"]) {
    window.englishDb["翰林"] = {};
}

// ==========================================
// 翰林版 1下 (Book 2) 完整字庫 (全單字 + 完整中文翻譯例句)
// ==========================================
window.englishDb["翰林"]["一下"] = {
    "Get Ready": [
        { word: "fruit", translate: "水果", sentence: "Oranges are my favorite fruit. (橘子是我最喜歡的水果。)" },
        { word: "menu", translate: "菜單", sentence: "I am hungry. Let's take a look at the menu. (我餓了。我們來看一下菜單吧。)" },
        { word: "papaya", translate: "木瓜", sentence: "Let's eat these two papayas. (我們來吃這兩顆木瓜吧。)" },
        { word: "watermelon", translate: "西瓜", sentence: "It's hot. Let's drink some watermelon milk. (好熱。我們來喝些西瓜牛奶吧。)" },
        { word: "strawberry", translate: "草莓", sentence: "Those strawberries are big and red. (那些草莓又大又紅。)" },
        { word: "guava", translate: "芭樂", sentence: "I eat a guava after dinner every day. (我每天晚餐後吃一顆芭樂。)" },
        { word: "grape", translate: "葡萄", sentence: "Betty is drinking grape juice. (貝蒂正在喝葡萄汁。)" },
        { word: "thirsty", translate: "口渴的", sentence: "I am thirsty. Can I have some juice? (我口渴了。我可以喝點果汁嗎？)" }
    ],
    "Lesson 1": [
        { word: "like", translate: "喜歡;像…", sentence: "I like this park. It is big and beautiful. (我喜歡這個公園。它又大又美麗。)" },
        { word: "sport", translate: "運動", sentence: "Terry plays sports in his free time. (泰瑞在空閒時間做運動。)" },
        { word: "much", translate: "多(的)", sentence: "Hurry up! We don't have much time. (快點！我們沒有很多時間了。)" },
        { word: "team", translate: "隊;組", sentence: "Frank is on the school baseball team. (法蘭克是學校棒球隊的隊員。)" },
        { word: "practice", translate: "練習", sentence: "Jack practices basketball after school every day. (傑克每天放學後練習籃球。)" },
        { word: "every", translate: "每一", sentence: "I wash my book bag every six months. (我每六個月洗一次我的書包。)" },
        { word: "then", translate: "那麼", sentence: "A: I don't watch TV. B: Really? Then what do you do in your free time? (A: 我不看電視。B: 真的嗎？那你空閒時間做什麼？)" },
        { word: "swim", translate: "游泳", sentence: "A: What is that bear doing? B: It is swimming. (A: 那隻熊在做什麼？B: 牠在游泳。)" },
        { word: "join", translate: "參加", sentence: "A: Can I join your team? B: Sure. Welcome! (A: 我可以加入你們的隊伍嗎？B: 當然。歡迎！)" },
        { word: "eye", translate: "眼睛", sentence: "Camila has beautiful brown eyes. (卡蜜拉有一雙美麗的棕色眼睛。)" },
        { word: "hair", translate: "頭髮", sentence: "A: I like your hair color. B: Thank you. (A: 我喜歡你的髮色。B: 謝謝。)" },
        { word: "know", translate: "知道;認識", sentence: "A: Do you know Viola? B: Viola Huang? Yeah. She is my cousin. (A: 你認識薇歐拉嗎？B: 黃薇歐拉？認識。她是我表姊。)" },
        { word: "hundred", translate: "百", sentence: "There are nine hundred students in my school. (我的學校裡有九百名學生。)" },
        { word: "centimeter", translate: "公分", sentence: "The ruler is fifteen centimeters long. (這把尺十五公分長。)" },
        { word: "You can say that again!", translate: "一點也沒錯!", sentence: "A: That band is really popular in the USA. B: You can say that again! (A: 那個樂團在美國真的很受歡迎。B: 一點也沒錯！)" },
        { word: "guitar", translate: "吉他", sentence: "My sister practices the guitar in her room. (我妹妹在她的房間裡練習吉他。)" },
        { word: "piano", translate: "鋼琴", sentence: "Many students in the class can play the piano. (班上很多學生會彈鋼琴。)" },
        { word: "fly a kite", translate: "放風箏", sentence: "The boy is flying a kite. (那個男孩正在放風箏。)" },
        { word: "paint", translate: "畫圖;顏料;油漆", sentence: "A: What can you do? B: I can paint the walls. (A: 你會做什麼？B: 我可以粉刷牆壁。)" },
        { word: "make a cake", translate: "做蛋糕", sentence: "A: We can make a cake for Sue's birthday. B: Yeah, let's do it. (A: 我們可以為蘇的生日做一個蛋糕。B: 耶，我們來做吧。)" },
        { word: "nose", translate: "鼻子", sentence: "Pinocchio's nose is long and thin. (皮諾丘的鼻子又長又細。)" },
        { word: "leg", translate: "腿", sentence: "My legs are 90 centimeters long. (我的腿有90公分長。)" },
        { word: "large", translate: "大的", sentence: "This house is large for my family. (這棟房子對我的家人來說很大。)" },
        { word: "ear", translate: "耳朵", sentence: "The dog's ears are very big. (這隻狗的耳朵非常大。)" },
        { word: "mouth", translate: "嘴巴", sentence: "Don't talk with your mouth full. (不要滿嘴食物講話。)" },
        { word: "thick", translate: "厚的", sentence: "Harry has many thick books. (哈利有很多厚書。)" },
        { word: "lip", translate: "嘴唇", sentence: "Dogs' lips are black. (狗的嘴唇是黑色的。)" },
        { word: "strong", translate: "強壯的", sentence: "These bugs are small but strong. (這些蟲子很小但很強壯。)" },
        { word: "arm", translate: "手臂", sentence: "Those monkeys have really long arms. (那些猴子的手臂真的很長。)" },
        { word: "height", translate: "身高;高度", sentence: "The doghouse is 50 centimeters in height. (這個狗屋高度是50公分。)" },
        { word: "player", translate: "選手;球員", sentence: "That handsome man over there is Zoe's favorite baseball player. (那邊那個英俊的男人是柔依最喜歡的棒球選手。)" },
        { word: "the USA", translate: "美國", sentence: "The girl band comes from the USA. (這個女子樂團來自美國。)" },
        { word: "body", translate: "身體", sentence: "He has a strong body. (他有強壯的身體。)" },
        { word: "put one's all", translate: "盡全力", sentence: "Jeremy puts his all into every game. (傑瑞米在每場比賽都盡全力。)" },
        { word: "into", translate: "到…裡面", sentence: "Please put your pencils into the pencil case. (請把你的鉛筆放進鉛筆盒裡。)" },
        { word: "a lot of", translate: "很多的", sentence: "Grandma cooks a lot of food for us on Thanksgiving every year. (奶奶每年感恩節都會為我們煮很多食物。)" },
        { word: "stand out", translate: "突出", sentence: "The black picture on the orange wall really stands out. (橘色牆上的黑色畫作真的很突出。)" },
        { word: "different", translate: "不同的", sentence: "Vincent is very different from his brother. (文森特和他的哥哥非常不同。)" },
        { word: "top", translate: "頂尖的", sentence: "My brothers both go to top schools. (我的哥哥們都讀頂尖的學校。)" },
        { word: "on the other hand", translate: "另一方面", sentence: "Adam is very good at basketball. On the other hand, he's new to baseball. (亞當很擅長籃球。另一方面，他是棒球新手。)" },
        { word: "make up for...", translate: "彌補…", sentence: "For a baseball player, he's not very strong, but he makes up for it with a lot of practice. (對於一個棒球選手來說，他不是很強壯，但他用大量的練習來彌補。)" }
    ],
    "Lesson 2": [
        { word: "early", translate: "早的", sentence: "A: I go to bed at ten. B: That's early. (A: 我十點就寢。B: 那很早。)" },
        { word: "work", translate: "工作", sentence: "They work eight hours a day. (他們一天工作八小時。)" },
        { word: "often", translate: "經常", sentence: "Timothy is often quiet in class. (提摩西在班上經常很安靜。)" },
        { word: "get up", translate: "起床", sentence: "I'm not a morning person. I never get up before 10 a.m. (我不是一個早起的人。我從不在早上10點前起床。)" },
        { word: "usually", translate: "通常", sentence: "We usually have dinner at six. (我們通常在六點吃晚餐。)" },
        { word: "seldom", translate: "很少", sentence: "I seldom see my cousin. He is studying in Poland. (我很少見到我表哥。他在波蘭讀書。)" },
        { word: "sometimes", translate: "有時候", sentence: "A: Do you eat out? B: Yeah, sometimes. (A: 你會在外面吃飯嗎？B: 對，有時候。)" },
        { word: "even", translate: "甚至", sentence: "A: Do you like Alice? B: Alice? I don't even know her. (A: 你喜歡愛麗絲嗎？B: 愛麗絲？我甚至不認識她。)" },
        { word: "late", translate: "晚的", sentence: "A: The movie is at 11 p.m. B: Wow, that's late. (A: 電影在晚上十一點。B: 哇，那很晚。)" },
        { word: "do one's homework", translate: "做功課", sentence: "My brothers do their homework in the living room. (我的哥哥們在客廳寫功課。)" },
        { word: "hour", translate: "小時", sentence: "That video is an hour and twenty minutes long. (那部影片有一小時二十分鐘長。)" },
        { word: "always", translate: "總是", sentence: "Hank is always nervous in front of girls. (漢克在女生面前總是感到緊張。)" },
        { word: "tired", translate: "疲累的", sentence: "The fans are tired after the meet-and-greet. (粉絲們在見面會後感到疲累。)" },
        { word: "shower", translate: "淋浴", sentence: "Ashley is in the shower. (艾希莉正在淋浴。)" },
        { word: "never", translate: "從未", sentence: "John is never late for school. (約翰上學從不遲到。)" },
        { word: "by the way", translate: "順帶一提", sentence: "By the way, is your sister at home? (順帶一提，你妹妹在家嗎？)" },
        { word: "library", translate: "圖書館", sentence: "Do you often go to the library? (你經常去圖書館嗎？)" },
        { word: "check out", translate: "借(書)", sentence: "I check out books from the library once a month. (我每個月從圖書館借一次書。)" },
        { word: "once", translate: "一次", sentence: "I clean my room once a week. (我每週打掃一次房間。)" },
        { word: "twice", translate: "兩次", sentence: "They walk the dogs twice a day. (他們一天遛兩次狗。)" },
        { word: "walk", translate: "遛(寵物)", sentence: "We don't walk our dogs every day. (我們不是每天遛狗。)" },
        { word: "I can't help it.", translate: "我沒辦法。/我控制不了。", sentence: "A: You're listening to that song again. B: I can't help it. It's so good. (A: 你又在聽那首歌了。B: 我控制不了。它太好聽了。)" },
        { word: "then", translate: "然後", sentence: "Wash your hands, and then you can eat. (洗洗手，然後你就可以吃了。)" },
        { word: "too", translate: "太…", sentence: "The table is too small for five people. (這張桌子對五個人來說太小了。)" },
        { word: "How often...?", translate: "多常…?", sentence: "A: How often do you say 'I love you' to your family? B: Not very often. (A: 你多常對家人說「我愛你」？B: 不太常。)" },
        { word: "about", translate: "大約", sentence: "A: How often do you clean up your room? B: About once a month. (A: 你多常打掃你的房間？B: 大約一個月一次。)" },
        { word: "brush one's teeth", translate: "刷牙", sentence: "Do you brush your teeth after lunch? (你午餐後會刷牙嗎？)" },
        { word: "face", translate: "臉", sentence: "The girl's face is cute. (這個女孩的臉很可愛。)" },
        { word: "breakfast", translate: "早餐", sentence: "Some people don't eat breakfast. (有些人不吃早餐。)" },
        { word: "lunch", translate: "午餐", sentence: "The Chen family goes out for lunch on Sundays. (陳家人星期天都會出去吃午餐。)" },
        { word: "exercise", translate: "運動", sentence: "They often exercise at the park after dinner. (他們晚餐後經常在公園運動。)" },
        { word: "computer", translate: "電腦", sentence: "Students can't use the computer in class. (學生不能在課堂上使用電腦。)" },
        { word: "minute", translate: "分鐘", sentence: "A: Can we go in now? B: Please wait a minute. The classroom is not ready. (A: 我們現在可以進去嗎？B: 請等一分鐘。教室還沒準備好。)" },
        { word: "answer", translate: "回答;答案", sentence: "A: Do you know the answer to this question? B: Sure. (A: 你知道這個問題的答案嗎？B: 當然。)" },
        { word: "question", translate: "問題", sentence: "Sherry has a question about her homework. (雪莉對她的作業有一個問題。)" },
        { word: "trouble", translate: "困難;麻煩", sentence: "Mr. Chen's sons often make trouble at school. (陳先生的兒子們經常在學校製造麻煩。)" },
        { word: "life", translate: "生活;生命", sentence: "I have great friends and family. My life is good. (我有很棒的朋友和家人。我的生活很好。)" },
        { word: "love", translate: "愛", sentence: "We have three dogs, and we love them very much. (我們有三隻狗，而且我們非常愛牠們。)" },
        { word: "real", translate: "真實的", sentence: "Ross Lee is not the writer's real name. (羅斯·李不是這位作家的真名。)" }
    ],
    "Lesson 3": [
        { word: "painting", translate: "畫作", sentence: "The paintings on the wall are beautiful. (牆上的畫作很美麗。)" },
        { word: "flower", translate: "花", sentence: "Do we have enough flowers for our dinner party? (我們的晚宴有足夠的花嗎？)" },
        { word: "which", translate: "哪一個", sentence: "A: Which is Kyle's house? B: The red house over there is. (A: 哪一棟是凱爾的房子？B: 那邊那棟紅色的房子是。)" },
        { word: "thirsty", translate: "口渴的", sentence: "I am always hot and thirsty after baseball games. (打完棒球後，我總是又熱又渴。)" },
        { word: "coffee", translate: "咖啡", sentence: "Too much coffee is not good for you. (喝太多咖啡對你不好。)" },
        { word: "shop", translate: "商店", sentence: "There aren't many shops near my house. (我家附近沒有很多商店。)" },
        { word: "later", translate: "稍後;晚點", sentence: "A: I'm going home now. Bye. B: See you later. (A: 我現在要回家了。掰。B: 待會見。)" },
        { word: "Of course.", translate: "當然。", sentence: "A: Are you going to Ed's birthday party later? B: Of course. (A: 你待會要去艾德的生日派對嗎？B: 當然。)" },
        { word: "clerk", translate: "店員", sentence: "The clerk is very nice. She helps me a lot. (那位店員人很好。她幫了我很多忙。)" },
        { word: "may", translate: "可以;可能", sentence: "A: May I come in? B: Sure. Please come in. (A: 我可以進來嗎？B: 當然。請進。)" },
        { word: "juice", translate: "果汁", sentence: "I always have orange juice for breakfast. (我早餐總是喝柳橙汁。)" },
        { word: "want", translate: "想要", sentence: "Mr. Chen wants a baby, but Mrs. Chen doesn't. (陳先生想要個寶寶，但陳太太不想。)" },
        { word: "anything", translate: "任何事物", sentence: "Do you know anything about Van Gogh? (你知道任何關於梵谷的事嗎？)" },
        { word: "else", translate: "其他", sentence: "Joanne is not happy, but everyone else is. (喬安不開心，但其他每個人都很開心。)" },
        { word: "treat", translate: "請客;款待", sentence: "Let me treat you to dinner later. (待會讓我請你吃晚餐。)" },
        { word: "sweet", translate: "甜美的;甜的", sentence: "Holly is a sweet girl. People love her. (霍莉是個甜美的女孩。大家都很喜歡她。)" },
        { word: "hot", translate: "熱的", sentence: "It's so hot. I want some ice cream. (好熱。我想要些冰淇淋。)" },
        { word: "chocolate", translate: "巧克力", sentence: "Chocolate ice cream is my favorite. (巧克力冰淇淋是我的最愛。)" },
        { word: "dollar", translate: "元", sentence: "A: How much is that comic book? B: It's two hundred dollars. (A: 那本漫畫書多少錢？B: 兩百元。)" },
        { word: "for here", translate: "內用", sentence: "May I have black coffee for here, please? (請給我一杯內用的黑咖啡好嗎？)" },
        { word: "to go", translate: "外帶", sentence: "A: Do you want your juice for here or to go? B: To go. Thanks. (A: 你的果汁要內用還是外帶？B: 外帶。謝謝。)" },
        { word: "Here you are.", translate: "給你。", sentence: "A: May I have some tea, please? B: Sure. Here you are. (A: 請給我一些茶好嗎？B: 當然。給你。)" },
        { word: "bright", translate: "鮮豔的;明亮的", sentence: "The man is painting the wall bright blue. (那個男人正在把牆壁漆成亮藍色。)" },
        { word: "dark", translate: "黑的;暗的", sentence: "It's too dark in my room. I can't read. (我房間太暗了。我無法看書。)" },
        { word: "art", translate: "美術;藝術", sentence: "Miss Lee is an art teacher at Green Junior High School. (李老師是格林國中的美術老師。)" },
        { word: "milk", translate: "牛奶", sentence: "Have some hot milk before bed. (睡前喝些熱牛奶吧。)" },
        { word: "hamburger", translate: "漢堡", sentence: "The hamburger house on Elm Street is great. (榆樹街上的漢堡店很棒。)" },
        { word: "chicken rice", translate: "雞肉飯", sentence: "My mom makes good chicken rice. (我媽媽做的雞肉飯很好吃。)" },
        { word: "tea", translate: "茶", sentence: "Do you have some ice? My tea is too hot. (你有一些冰塊嗎？我的茶太燙了。)" },
        { word: "ice cream", translate: "冰淇淋", sentence: "Lara's favorite food is ice cream. (蘿拉最喜歡的食物是冰淇淋。)" },
        { word: "soup", translate: "湯", sentence: "In English, we always say 'eat soup,' not 'drink soup.' (在英文中，我們總是說「吃湯(eat soup)」，而不是「喝湯(drink soup)」。)" },
        { word: "sandwich", translate: "三明治", sentence: "That shop has really good sandwiches. (那家店有非常棒的三明治。)" },
        { word: "work", translate: "作品", sentence: "The Mona Lisa is a work by Leonardo da Vinci. (蒙娜麗莎是李奧納多·達文西的作品。)" },
        { word: "show", translate: "表現;秀出", sentence: "She's showing her new watch to her friends. (她正在向朋友們展示她的新腕錶。)" },
        { word: "part", translate: "部分", sentence: "Music is an important part in a movie. (音樂在電影中是很重要的一部分。)" },
        { word: "sky", translate: "天空", sentence: "The sky is gray today. (今天天空灰灰的。)" },
        { word: "street", translate: "街道", sentence: "It's a quiet night. There are no people on the street. (這是一個安靜的夜晚。街上沒有人。)" },
        { word: "by", translate: "被;由", sentence: "I'm reading some books by Charles Dickens. (我正在讀一些查爾斯·狄更斯的書。)" }
    ],
    "Lesson 4": [
        { word: "why", translate: "為什麼", sentence: "Why is the sea blue? (為什麼海是藍色的？)" },
        { word: "wear", translate: "戴;穿", sentence: "I never wear a watch. (我從不戴手錶。)" },
        { word: "mask", translate: "口罩;面具", sentence: "Dr. Smith is wearing a mask. (史密斯醫生戴著口罩。)" },
        { word: "because", translate: "因為", sentence: "I drink coffee in the morning because it wakes me up. (我早上喝咖啡，因為它能讓我清醒。)" },
        { word: "sick", translate: "生病的", sentence: "Mindy can't come to the party because she's sick. (明蒂因為生病不能來參加派對。)" },
        { word: "water", translate: "水", sentence: "A: How may I help you? B: Can I have some water, please? (A: 我能為您服務嗎？B: 可以給我一些水嗎？)" },
        { word: "glass", translate: "玻璃杯;玻璃", sentence: "A: What is that? B: That's a glass of milk shake. (A: 那是什麼？B: 那是一杯奶昔。)" },
        { word: "flour", translate: "麵粉", sentence: "There are three bags of flour on the table. (桌上有三袋麵粉。)" },
        { word: "need", translate: "需要;需求", sentence: "A: How many apples do you need? B: Six is enough. Thanks. (A: 你需要幾顆蘋果？B: 六顆就夠了。謝謝。)" },
        { word: "pie", translate: "派", sentence: "Do you want some apple pie? (你想要一些蘋果派嗎？)" },
        { word: "still", translate: "仍然", sentence: "The boy is still hungry after the big meal. (吃完大餐後，那個男孩仍然很餓。)" },
        { word: "thing", translate: "東西;事情", sentence: "Can you buy these things for me? (你能幫我買這些東西嗎？)" },
        { word: "a little", translate: "一點點", sentence: "A: Do you have any milk? I only need a little. B: No, I don't have any. (A: 你有牛奶嗎？我只需要一點點。B: 不，我沒有。)" },
        { word: "salt", translate: "鹽", sentence: "Do not eat too much salt. It is not good for you. (不要吃太多鹽。那對你不好。)" },
        { word: "something", translate: "某物;某事", sentence: "I have something for you. (我有東西要給你。)" },
        { word: "sugar", translate: "糖", sentence: "A: How much is a bag of sugar? B: It's NT$45. (A: 一袋糖多少錢？B: 是45元新台幣。)" },
        { word: "get", translate: "取得", sentence: "We can get some food over there. (我們可以在那邊買到一些食物。)" },
        { word: "all right", translate: "好的;好吧", sentence: "A: I don't have any eggs. Can you give me some? B: All right. Here you go. (A: 我沒有任何雞蛋。你能給我一些嗎？B: 好吧。給你。)" },
        { word: "so", translate: "所以", sentence: "Marvin is always tired in the morning, so he sometimes takes a shower before work. (馬文早上總是覺得累，所以他有時候會在上班前洗澡。)" },
        { word: "back off", translate: "退後;走開", sentence: "Back off! Don't play with the dog. It's not safe. (退後！不要跟那隻狗玩。這不安全。)" },
        { word: "meal", translate: "餐", sentence: "My family always has a big meal on Christmas Eve. (我的家人總是在平安夜吃一頓大餐。)" },
        { word: "bottle", translate: "瓶子", sentence: "There is a bottle of juice on the sofa. (沙發上有一瓶果汁。)" },
        { word: "candy", translate: "糖果", sentence: "Is there any candy in the box? (盒子裡有糖果嗎？)" },
        { word: "popcorn", translate: "爆米花", sentence: "A tub of popcorn is NT$80. (一桶爆米花80元新台幣。)" },
        { word: "cup", translate: "杯", sentence: "A: I am so tired. B: A cup of coffee can help. (A: 我好累。B: 一杯咖啡會有幫助。)" },
        { word: "bowl", translate: "碗", sentence: "She eats a bowl of fruit every morning. (她每天早上吃一碗水果。)" },
        { word: "fruit salad", translate: "水果沙拉", sentence: "How about a plate of fruit salad for breakfast? (早餐來一盤水果沙拉如何？)" },
        { word: "pizza", translate: "披薩", sentence: "These five pizzas are for Andy's party. (這五個披薩是為安迪的派對準備的。)" },
        { word: "milk shake", translate: "奶昔", sentence: "I'm making some milk shake. Do you want some? (我正在做一些奶昔。你想要一些嗎？)" },
        { word: "can", translate: "罐子", sentence: "The can of juice is bad. Don't drink it. (這罐果汁壞了。不要喝它。)" },
        { word: "toast", translate: "烤吐司;烘烤", sentence: "Miss Parker often has toast for breakfast. (派克小姐早餐經常吃烤吐司。)" },
        { word: "bread", translate: "麵包", sentence: "Do you like white bread or brown bread? (你喜歡白麵包還是黑麵包？)" },
        { word: "yummy", translate: "好吃的", sentence: "These cookies are yummy. Where can I get them? (這些餅乾很好吃。我能在哪裡買到它們？)" },
        { word: "easy", translate: "容易的", sentence: "Life is not easy for many people. (生活對許多人來說並不容易。)" },
        { word: "snack", translate: "點心", sentence: "I'm hungry. I want some snacks. (我餓了。我想要一些點心。)" },
        { word: "kid", translate: "小孩", sentence: "A: Is this your kid? He's cute. B: Yes, he is my son. (A: 這是你的小孩嗎？他很可愛。B: 是的，他是我的兒子。)" },
        { word: "cheese", translate: "乳酪", sentence: "Kyle always puts a lot of cheese on his pizza. (凱爾總是在他的披薩上放很多起司。)" },
        { word: "plate", translate: "盤子", sentence: "Please be careful. This is my mom's favorite plate. (請小心。這是我媽媽最喜歡的盤子。)" },
        { word: "last", translate: "最後(的)", sentence: "This is our last bottle of water, guys. (各位，這是我們最後一瓶水了。)" },
        { word: "enjoy", translate: "享受;喜愛", sentence: "A: Don't be nervous. Enjoy your time! B: Thanks. (A: 別緊張。好好享受你的時間！B: 謝謝。)" },
        { word: "turn into", translate: "(使)變成", sentence: "We can turn this sofa into a bed. (我們可以把這張沙發變成一張床。)" },
        { word: "each", translate: "每一個(的)", sentence: "Each family is enjoying the holidays. (每個家庭都在享受假期。)" }
    ],
    "Lesson 5": [
        { word: "yesterday", translate: "昨天", sentence: "I didn't go to school yesterday. (我昨天沒去上學。)" },
        { word: "beach", translate: "海灘", sentence: "My wife and I take a walk on the beach every morning. (我妻子和我每天早上在海灘散步。)" },
        { word: "trash", translate: "垃圾", sentence: "A: How much are the trash bags? B: One hundred dollars. (A: 垃圾袋多少錢？B: 一百元。)" },
        { word: "ago", translate: "前;以前", sentence: "I watched the movie at home two days ago. (我兩天前在家看了這部電影。)" },
        { word: "visit", translate: "拜訪", sentence: "A: How often do you visit your grandmother? B: Once a week. (A: 你多常去拜訪你奶奶？B: 一週一次。)" },
        { word: "island", translate: "島嶼", sentence: "The island is small but very beautiful. (這座島嶼很小但非常美麗。)" },
        { word: "a few", translate: "幾個;一些", sentence: "Only a few people like this painting. (只有少數幾個人喜歡這幅畫。)" },
        { word: "sea", translate: "海", sentence: "The dark blue sea is so beautiful. (深藍色的海好美。)" },
        { word: "stop", translate: "停止", sentence: "A: The guy stopped and looked at you. Do you know him? B: No, I don't. (A: 那個傢伙停下來看著你。你認識他嗎？B: 不，我不認識。)" },
        { word: "happen", translate: "發生", sentence: "A: Henry is not happy. What happened to him? B: I don't know. (A: 亨利不開心。他發生什麼事了？B: 我不知道。)" },
        { word: "dead", translate: "死亡的", sentence: "Her dog was dead, and she was very sad. (她的狗死了，她非常傷心。)" },
        { word: "warm", translate: "溫暖的", sentence: "A: Can I have some warm water, please? B: Sure. (A: 請給我一些溫水好嗎？B: 當然。)" },
        { word: "rainforest", translate: "雨林", sentence: "There are many plants and animals in the rainforest. (雨林裡有許多植物和動物。)" },
        { word: "die", translate: "死亡", sentence: "A: My dog died yesterday. B: I'm sorry. (A: 我的狗昨天死了。B: 聽到這消息我很難過。)" },
        { word: "by", translate: "在…旁邊", sentence: "There is a brown horse by the big tree. (大樹旁邊有一匹棕色的馬。)" },
        { word: "How come?", translate: "怎麼會?/為什麼?", sentence: "A: I don't like Ted. B: How come? He is a nice guy. (A: 我不喜歡泰德。B: 怎麼會？他是個好人。)" },
        { word: "then", translate: "那時候", sentence: "I worked in that company then. (那時候我在那家公司工作。)" },
        { word: "busy", translate: "忙碌的", sentence: "Parents are always busy. (父母總是很忙碌。)" },
        { word: "river", translate: "河流", sentence: "Do not swim in the river. (不要在河裡游泳。)" },
        { word: "lake", translate: "湖泊", sentence: "There are many beautiful fish in the lake. (湖裡有許多美麗的魚。)" },
        { word: "hill", translate: "山丘", sentence: "My grandpa's house stands on a hill. (我爺爺的房子位於山丘上。)" },
        { word: "mountain", translate: "山", sentence: "Bears live in the mountains. (熊住在山裡。)" },
        { word: "camp", translate: "露營;紮營", sentence: "We seldom camp in the mountains in January. (我們很少在一月份去山裡露營。)" },
        { word: "climb", translate: "爬(山)", sentence: "The fox climbed up the tree for food. (狐狸爬上樹找食物。)" },
        { word: "row a boat", translate: "划船", sentence: "I rowed a boat with my parents on the river. (我和父母在河上划船。)" },
        { word: "plant", translate: "種植;植物", sentence: "My mom planted an apple tree for me. (我媽媽為我種了一棵蘋果樹。)" },
        { word: "hike", translate: "健行", sentence: "Mr. Thompson hikes in the forest every weekend. (湯普森先生每個週末都在森林裡健行。)" },
        { word: "picnic", translate: "野餐", sentence: "My friends and I didn't go on a picnic that day. (我和我的朋友那天沒有去野餐。)" },
        { word: "last", translate: "上一個的", sentence: "Yesterday was my friend's birthday, and we had a big meal last night. (昨天是我朋友的生日，昨晚我們吃了一頓大餐。)" },
        { word: "live", translate: "居住", sentence: "Marie lives in a tree house with her family. (瑪麗和她的家人住在一個樹屋裡。)" },
        { word: "playground", translate: "遊樂場;操場", sentence: "Kids often make new friends at the playground. (孩子們經常在遊樂場結交新朋友。)" },
        { word: "everything", translate: "每樣事物", sentence: "Annie really likes Toby. She knows everything about him. (安妮非常喜歡托比。她對他的一切都瞭若指掌。)" },
        { word: "change", translate: "改變", sentence: "Maggie changed her phone number a few days ago. (瑪姬幾天前改了她的電話號碼。)" },
        { word: "burn", translate: "燃燒", sentence: "The company burned the rainforest and planted palm trees. (那家公司燒毀了雨林並種植了棕櫚樹。)" },
        { word: "oil", translate: "油", sentence: "A: Go wash your hands. There's oil on them. B: OK, Dad. (A: 去洗手。上面有油。B: 好的，爸爸。)" },
        { word: "sell", translate: "賣", sentence: "A: Did you sell your car? B: Yes, I needed the money. (A: 你把車賣了嗎？B: 是的，我需要這筆錢。)" },
        { word: "make money", translate: "賺錢", sentence: "Tommy makes money for his family. (湯米賺錢養家。)" },
        { word: "miss", translate: "想念", sentence: "I miss my elementary school classmates. (我很想念我小學的同班同學。)" },
        { word: "little", translate: "小的", sentence: "The little girl over there is Tina's sister. (那邊那個小女孩是蒂娜的妹妹。)" },
        { word: "little by little", translate: "一點一點地;逐漸地", sentence: "The ice turned into water little by little. (冰塊一點一點地變成了水。)" },
        { word: "way", translate: "方式", sentence: "Ted goes to bed before 10 p.m. This way, he can have enough sleep. (泰德晚上十點前就寢。這樣一來，他就能有足夠的睡眠。)" }
    ],
    "Lesson 6": [
        { word: "airport", translate: "機場", sentence: "There is an airport near my house. (我家附近有一座機場。)" },
        { word: "travel", translate: "旅行;行進", sentence: "Eric is traveling the world with his family. (艾瑞克正在和他的家人環遊世界。)" },
        { word: "rest", translate: "休息", sentence: "Why don't we take a rest under the big tree? (我們何不在大樹下休息一下呢？)" },
        { word: "hotel", translate: "飯店", sentence: "There are three hotels on this street. (這條街上有三家飯店。)" },
        { word: "plane", translate: "飛機", sentence: "The workers are building an airplane. (工人們正在建造一架飛機。)" },
        { word: "the sights", translate: "風景;名勝", sentence: "Welcome to Indonesia. Let's go see the sights! (歡迎來到印尼。我們去觀光吧！)" },
        { word: "bookstore", translate: "書店", sentence: "Elly often goes to the bookstore after school. (艾莉放學後經常去書店。)" },
        { word: "buy", translate: "購買", sentence: "My brother bought a nice pencil case at the shop. (我弟弟在店裡買了一個好看的鉛筆盒。)" },
        { word: "just", translate: "剛才;就;只", sentence: "Amy just came back from the US. (艾美剛從美國回來。)" },
        { word: "learn", translate: "學習", sentence: "My grandpa plays the piano. I learned a lot about music from him. (我爺爺會彈鋼琴。我從他那裡學到了很多關於音樂的知識。)" },
        { word: "story", translate: "故事", sentence: "The story about the boy was so sad. (關於那個男孩的故事好令人傷心。)" },
        { word: "cool", translate: "酷的", sentence: "A: Where did you get this cool watch? B: From my mom. It was for my birthday. (A: 你從哪裡得到這支酷手錶的？B: 從我媽媽那裡。這是給我的生日禮物。)" },
        { word: "train", translate: "火車", sentence: "Nick is now on a train to the Taj Mahal. (尼克現在正搭乘前往泰姬陵的火車。)" },
        { word: "cold", translate: "冷的", sentence: "Your hands are so cold. (你的手好冷。)" },
        { word: "try", translate: "嘗試", sentence: "Penny tried the salad, but she didn't like it. (潘妮嘗試了沙拉，但她不喜歡。)" },
        { word: "way", translate: "距離;路線", sentence: "It's a long way from my house to school. (從我家到學校有很長一段路。)" },
        { word: "take", translate: "帶;拿;取", sentence: "I took an umbrella with me to school. (我帶了一把雨傘去學校。)" },
        { word: "the other day", translate: "前幾天", sentence: "I went to the beach the other day and met my friend. (前幾天我去了海灘，遇到了我的朋友。)" },
        { word: "station", translate: "車站;局", sentence: "Wendy is on her way to the train station. (溫蒂正在前往火車站的路上。)" },
        { word: "department store", translate: "百貨公司", sentence: "Many people go to the department store on weekends. (很多人週末去百貨公司。)" },
        { word: "restaurant", translate: "餐廳", sentence: "Maggie likes the chicken soup at this restaurant. (瑪姬喜歡這家餐廳的雞湯。)" },
        { word: "theater", translate: "電影院", sentence: "The movie theater sells great popcorn. (這家電影院賣很棒的爆米花。)" },
        { word: "market", translate: "市場", sentence: "Ellen goes to the night market every Friday night. (愛倫每個星期五晚上去夜市。)" },
        { word: "temple", translate: "寺廟", sentence: "Sam visited many temples last month. (山姆上個月參觀了許多寺廟。)" },
        { word: "famous", translate: "有名的", sentence: "There is a famous ice cream shop next to our school. (我們學校旁邊有一家有名的冰淇淋店。)" },
        { word: "during", translate: "在…期間", sentence: "Don't use your phone during a movie. (看電影期間不要使用手機。)" },
        { word: "besides", translate: "除…之外", sentence: "Besides a cat, we also got a dog from the farm. (除了貓之外，我們還從農場養了一隻狗。)" },
        { word: "fall in love", translate: "墜入情網", sentence: "He fell in love at age sixteen. (他在十六歲時墜入愛河。)" },
        { word: "age", translate: "年紀", sentence: "The king died at a young age. (國王在年輕時就去世了。)" },
        { word: "lose", translate: "失去", sentence: "I lost my water bottle at the beach yesterday. (我昨天在海灘弄丟了我的水瓶。)" },
        { word: "cry", translate: "哭泣", sentence: "A: I'm so sad now. B: Just cry. It can help. (A: 我現在好傷心。B: 就哭吧。這會有幫助的。)" },
        { word: "hide", translate: "躲藏", sentence: "I hid behind the tree, so my mom couldn't see me. (我躲在樹後面，所以我媽媽看不到我。)" },
        { word: "build", translate: "建造", sentence: "My brother built a tree house during the weekend. (我哥哥在週末建了一個樹屋。)" },
        { word: "trip", translate: "旅行;行程", sentence: "Jim really enjoyed his trip to the US last year. (吉姆非常享受去年他的美國之旅。)" },
        { word: "sadly", translate: "令人傷心地", sentence: "Sadly, Mrs. Ko's son lost his life at a young age. (令人傷心地，柯太太的兒子在年輕時就喪失了生命。)" },
        { word: "last", translate: "持續", sentence: "A: How long did the concert last? B: Two hours. The fans enjoyed it very much. (A: 演唱會持續了多久？B: 兩個小時。粉絲們非常享受。)" }
    ],
    "Culture & Festival Unit": [
        { word: "Easter", translate: "復活節", sentence: "We're not going to school on Easter. (我們在復活節不去上學。)" },
        { word: "moon", translate: "月亮", sentence: "The moon is big and bright. (月亮又大又明亮。)" },
        { word: "church", translate: "教堂", sentence: "How often do you go to church? (你多常去教堂？)" },
        { word: "roll", translate: "滾動", sentence: "The ball rolled down the hill. (球滾下了山丘。)" },
        { word: "hunt", translate: "搜尋;狩獵", sentence: "Some animals hunt at night. (有些動物在夜間狩獵。)" },
        { word: "fall", translate: "降臨;發生", sentence: "Easter falls late this year. (今年復活節來得很晚。)" },
        { word: "check out", translate: "查看", sentence: "There's a new movie theater near our school. Let's go check it out this weekend! (我們學校附近新開了一家電影院。這週末我們去看看吧！)" },
        { word: "get together", translate: "團聚", sentence: "Can we get together for dinner this Friday? (我們這週五能聚在一起吃晚餐嗎？)" }
    ]
};