// 確保全域變數存在
if (typeof window.englishDb === 'undefined') { window.englishDb = {}; }
if (!window.englishDb["康軒"]) { window.englishDb["康軒"] = {}; }

// ==========================================
// 康軒 3下 (L1~L4) 完整字庫 (全單字 + 完整中文翻譯例句)
// ==========================================
window.englishDb["康軒"]["三下"] = {
    "Lesson 1": [
        { word: "attack", translate: "攻擊", sentence: "The man was attacked when he was crossing the street, and he was taken to the hospital right away. (那名男子過馬路時受到攻擊，並立刻被送往醫院。)" },
        { word: "foreigner", translate: "外國人", sentence: "From now on, foreigners are not allowed to enter the country. (從現在起，外國人不得進入該國。)" },
        { word: "sharp", translate: "鋒利的", sentence: "Be careful with the knife. It's very sharp. (小心那把刀。它非常鋒利。)" },
        { word: "fake", translate: "假的", sentence: "Not only the girl's cellphone number but also her name is fake. (不僅這個女孩的手機號碼是假的，連她的名字也是假的。)" },
        { word: "while", translate: "當時", sentence: "Judy's husband was making dinner while she was drying her hair. (茱蒂的丈夫做晚餐時，她正在吹乾頭髮。)" },
        { word: "lazy", translate: "懶惰的", sentence: "Alex is the laziest person I've ever met. (艾力克斯是我見過最懶惰的人。)" },
        { word: "bee", translate: "蜜蜂", sentence: "I saw some bees sitting on the flowers in the garden this morning. (今天早上我看到一些蜜蜂停在花園裡的花朵上。)" },
        { word: "honey", translate: "蜂蜜", sentence: "Honey can be used to treat a sore throat. (蜂蜜可以用來治療喉嚨痛。)" },
        { word: "as soon as", translate: "一...就...", sentence: "I called my father as soon as I heard the good news. (我一聽到這個好消息就打電話給我爸爸。)" },
        { word: "as long as", translate: "只要", sentence: "They'll go camping as long as the weather is good. (只要天氣好，他們就會去露營。)" },
        { word: "bridge", translate: "橋", sentence: "Cross the bridge, and you'll see me by the river. (過了那座橋，你就會在河邊看到我。)" },
        { word: "typhoon", translate: "颱風", sentence: "The road signs fell in the street during the big typhoon last night. (昨晚強烈颱風期間，路標倒在街上了。)" },
        { word: "giant", translate: "巨大的", sentence: "Regina saw a giant snake in her room and cried out for help. (蕾吉娜在房間裡看到一條巨蛇，大聲呼救。)" },
        { word: "kite", translate: "風箏", sentence: "It's common to see kids flying their kites in the park on windy days. (在起風的日子裡，經常可以看到孩子們在公園放風箏。)" },
        { word: "chalk", translate: "粉筆", sentence: "The girl is drawing on the wall with a piece of yellow chalk. (這個女孩正用一塊黃色粉筆在牆上畫畫。)" },
        { word: "bug", translate: "蟲", sentence: "There's a bug in your hair. Let me get it out for you. (你的頭髮裡有隻蟲。讓我幫你弄出來。)" },
        { word: "insect", translate: "昆蟲", sentence: "Spiders are not insects because they have eight legs. (蜘蛛不是昆蟲，因為牠們有八條腿。)" },
        { word: "China", translate: "中國", sentence: "Most of the clothes in the shop were made in China. (這家店裡的大部分衣服都是在中國製造的。)" },
        { word: "balcony", translate: "陽臺", sentence: "Greg is hanging clothes out on the balcony. (葛瑞格正在陽台上晾衣服。)" },
        { word: "neighbor", translate: "鄰居", sentence: "My neighbor Iris always says hi to me with a smile on her face. (我的鄰居艾瑞絲總是面帶微笑地向我打招呼。)" },
        { word: "yard", translate: "院子", sentence: "There's a big yard at my grandparents' house. (我祖父母家有一個大院子。)" },
        { word: "ant", translate: "螞蟻", sentence: "An ant is a small insect that lives in large groups. (螞蟻是一種成群生活的小昆蟲。)" },
        { word: "bench", translate: "長椅", sentence: "Mrs. Wang sits on the bench and chats with her friends in the park every afternoon. (王太太每天下午都坐在長椅上和朋友們在公園聊天。)" },
        { word: "spot", translate: "看出;辨識", sentence: "Many people don't know how to spot fake news. (許多人不知道如何辨識假新聞。)" },
        { word: "source", translate: "資訊來源", sentence: "Please list all your sources at the end of your report. (請在報告的最後列出你所有的資訊來源。)" },
        { word: "trusted", translate: "可靠的", sentence: "May is an old and trusted friend of mine. (梅是我一位認識很久且可靠的朋友。)" },
        { word: "website", translate: "網站", sentence: "For more information, please visit our website. (如需更多資訊，請造訪我們的網站。)" },
        { word: "error", translate: "錯誤", sentence: "Irene often makes spelling errors in her homework. (艾琳常在作業中犯拼寫錯誤。)" },
        { word: "copy", translate: "複製;抄襲", sentence: "Grayson copied the answers from his classmate's test paper. (葛雷森抄襲了同學考卷上的答案。)" },
        { word: "headline", translate: "標題;頭條", sentence: "The knife attack was in the headlines for several days. (這起持刀攻擊事件連續幾天登上了頭條新聞。)" },
        { word: "smoke", translate: "抽菸", sentence: "Smoking is not good for your health. (抽菸對你的健康不好。)" },
        { word: "truth", translate: "真相", sentence: "Tell me the truth. Did you take money from Amy's wallet? (告訴我真相。你從艾美的錢包裡拿錢了嗎？)" },
        { word: "angle", translate: "觀點;角度", sentence: "We should look at the problem from different angles. (我們應該從不同的角度來看待這個問題。)" },
        { word: "far", translate: "遙遠的", sentence: "We could even hear the sound of water far away. (我們甚至能聽到遠處的水聲。)" },
        { word: "over-the-top", translate: "太過頭的", sentence: "I think what he just said is over-the-top. Don't take it seriously. (我覺得他剛才說的話太過頭了。別太認真。)" },
        { word: "tip", translate: "提示", sentence: "My grandma gave me some helpful tips for growing strawberries. (我奶奶給了我一些種草莓的實用提示。)" }
    ],
    "Lesson 2": [
        { word: "widely", translate: "廣泛地", sentence: "English is widely spoken around the world. (英文在世界各地被廣泛使用。)" },
        { word: "neither", translate: "也不", sentence: "Nick doesn't eat beef, and neither does his wife. (尼克不吃牛肉，他太太也不吃。)" },
        { word: "member", translate: "成員", sentence: "Vicky is a member of the badminton team. (維琪是羽毛球隊的一員。)" },
        { word: "joy", translate: "喜悅", sentence: "You can find joy in everything you do. (你可以在做的每件事中找到喜悅。)" },
        { word: "relative", translate: "親戚", sentence: "People in Taiwan usually visit their relatives during Chinese New Year. (台灣人通常在農曆新年期間拜訪親戚。)" },
        { word: "polite", translate: "禮貌的", sentence: "It is not polite to talk with your mouth full. (滿嘴食物講話是不禮貌的。)" },
        { word: "lonely", translate: "孤獨的", sentence: "Being alone does not mean that you should be lonely. (獨處並不意味著你應該感到孤獨。)" },
        { word: "hobby", translate: "嗜好", sentence: "Reading has been a hobby of Bonnie's since she was little. (閱讀從邦妮小時候起就是她的嗜好。)" },
        { word: "feeling", translate: "情感", sentence: "I'm sorry. I didn't mean to hurt your feelings. (對不起。我不是故意要傷害你的感情。)" },
        { word: "shy", translate: "害羞的", sentence: "Joseph is too shy to ask the girl he likes out. (喬瑟夫太害羞了，不敢約他喜歡的女孩出去。)" },
        { word: "stranger", translate: "陌生人", sentence: "Many children are taught not to talk to strangers. (許多孩子被教導不要和陌生人說話。)" },
        { word: "neither... nor...", translate: "既不...也不", sentence: "Neither my parents nor I was at home last night. (昨晚我父母和我都不在家。)" },
        { word: "put down", translate: "貶低", sentence: "Stop putting yourself down. You aren't good at everything you do, but nobody else is, either. (別再貶低自己了。你並不是每件事都擅長，但其他人也不是。)" },
        { word: "tidy", translate: "整理", sentence: "Winnie spent all morning cleaning and tidying the kitchen. (溫妮花了一整個上午打掃和整理廚房。)" },
        { word: "roll", translate: "翻滾", sentence: "The cat was rolling the ball across the floor. (貓在地板上滾著球。)" },
        { word: "hunt", translate: "搜尋;打獵", sentence: "Would you like to go on a hunt? (你想去打獵嗎？)" },
        { word: "traffic", translate: "交通", sentence: "There's always a lot of traffic at this time of day. (每天的這個時候總是有很多交通車流。)" },
        { word: "lend", translate: "借出", sentence: "It was kind of you to lend me the money. (你真好，借錢給我。)" },
        { word: "borrow", translate: "借入", sentence: "This is the bike I borrowed from my cousin. (這是我向我表哥借的腳踏車。)" },
        { word: "God", translate: "上帝", sentence: "Do you believe in God? (你相信上帝嗎？)" },
        { word: "umbrella", translate: "雨傘", sentence: "It's raining outside. Take an umbrella, or you'll get wet. (外面在下雨。帶把傘，否則你會淋濕。)" },
        { word: "mud", translate: "泥土", sentence: "When the soccer game was over, Ben was covered in mud. (足球比賽結束時，班全身都是泥巴。)" },
        { word: "towel", translate: "毛巾", sentence: "Howard dried his hands with the kitchen towel. (霍華德用廚房毛巾擦乾了手。)" },
        { word: "go ahead", translate: "開始;做", sentence: "Jane: Can I ask you a question? Daniel: Sure. Go ahead. (珍：我可以問你一個問題嗎？丹尼爾：當然。說吧。)" },
        { word: "be all ears", translate: "洗耳恭聽", sentence: "Tell me what happened. I'm all ears. (告訴我發生了什麼事。我洗耳恭聽。)" },
        { word: "turn", translate: "機會", sentence: "It's your turn to do the dishes tonight. (今晚輪到你洗碗了。)" },
        { word: "either... or...", translate: "不是...就是", sentence: "Either you or your classmate has to take out the trash. (不是你就是你的同學必須去倒垃圾。)" }
    ],
    "Lesson 3": [
        { word: "pool", translate: "游泳池", sentence: "Daisy decided to buy a house with a big swimming pool. (黛西決定買一棟有大游泳池的房子。)" },
        { word: "wish", translate: "希望", sentence: "Helen shook hands with me and wished me good luck. (海倫和我握手並祝我好運。)" },
        { word: "human", translate: "人類", sentence: "I'm not perfect. I'm only human. (我並不完美。我只是個凡人。)" },
        { word: "risk", translate: "風險", sentence: "Going skiing can be dangerous because of the risk of getting hurt. (去滑雪可能很危險，因為有受傷的風險。)" },
        { word: "hopefully", translate: "但願", sentence: "We are going to the beach tomorrow. Hopefully, it won't rain. (我們明天要去海灘。但願不會下雨。)" },
        { word: "nail", translate: "釘子", sentence: "Alex picked a nail up off the floor. (艾力克斯從地板上撿起一根釘子。)" },
        { word: "bell", translate: "鈴", sentence: "Stop writing when you hear the bell ring. (聽到鐘聲響起時請停止作答。)" },
        { word: "blank", translate: "空白的", sentence: "Write your name in the blank space at the bottom of the page. (把你的名字寫在頁面底部的空白處。)" },
        { word: "blackboard", translate: "黑板", sentence: "The teacher had two students write their answers on the blackboard. (老師讓兩個學生把答案寫在黑板上。)" },
        { word: "envelope", translate: "信封", sentence: "In Taiwan, children get lucky money in red envelopes during Chinese New Year. (在台灣，孩子們在農曆新年期間會收到紅包。)" },
        { word: "stamp", translate: "郵票", sentence: "Remember to put a stamp on the envelope before you mail it. (寄信前記得在信封上貼郵票。)" },
        { word: "postcard", translate: "明信片", sentence: "I'll send you a postcard as soon as I get to the USA. (我一到美國就會寄明信片給你。)" },
        { word: "mask", translate: "口罩", sentence: "On winter days, many people wear face masks to keep warm. (在冬天的日子裡，許多人戴口罩保暖。)" },
        { word: "ring", translate: "戒指", sentence: "Patrick is wearing a ring on his middle finger. (派翠克的中指上戴著一枚戒指。)" },
        { word: "comb", translate: "梳子", sentence: "I always carry a comb in my schoolbag. (我總是在書包裡帶一把梳子。)" },
        { word: "tie", translate: "領帶", sentence: "My father has to wear a shirt and tie at work. (我爸爸上班時必須穿襯衫打領帶。)" },
        { word: "dot", translate: "點", sentence: "The island is a small green dot on the map. (這個島是地圖上的一個小綠點。)" },
        { word: "match", translate: "相配", sentence: "Sharon said she loved how your shoes matched your skirt. (雪倫說她很喜歡你的鞋子和裙子的搭配。)" },
        { word: "belt", translate: "腰帶", sentence: "Ivy bought her father a belt as his birthday gift. (艾薇買了一條腰帶給她爸爸當生日禮物。)" },
        { word: "gas", translate: "汽油", sentence: "Gas prices have risen sharply over the past few weeks. (汽油價格在過去幾週急劇上漲。)" },
        { word: "pipe", translate: "管子", sentence: "There are water pipes under the road. (馬路底下有水管。)" },
        { word: "drum", translate: "鼓", sentence: "Linda is good at playing the drums. (琳達很擅長打鼓。)" },
        { word: "violin", translate: "小提琴", sentence: "It is not easy to learn to play the violin. (學習拉小提琴並不容易。)" },
        { word: "bow", translate: "琴弓", sentence: "To choose the right violin bow, you have to test whether you like the sound it makes when you use it. (為了選擇合適的小提琴弓，你必須測試看看你是否喜歡使用它時發出的聲音。)" },
        { word: "piano", translate: "鋼琴", sentence: "Rebecca practices the piano every night. (蕾貝卡每天晚上練習鋼琴。)" }
    ],
    "Lesson 4": [
        { word: "yearbook", translate: "畢業紀念冊", sentence: "Your yearbook will record your school memories for a lifetime. (你的畢業紀念冊將會記錄你一生的學校回憶。)" },
        { word: "neck", translate: "脖子", sentence: "Puffy fell down the stairs and broke her neck. (帕菲從樓梯上摔下來，摔斷了脖子。)" },
        { word: "prize", translate: "獎", sentence: "Everyone clapped loudly when Annie went up to get her prize. (當安妮上台領獎時，每個人都大聲鼓掌。)" },
        { word: "quiz", translate: "小考", sentence: "We had a quiz in math class this morning. (我們今天早上的數學課有小考。)" },
        { word: "workbook", translate: "習作", sentence: "Class, remember to bring your workbooks to school tomorrow. (各位同學，記得明天把習作帶到學校。)" },
        { word: "notes", translate: "筆記", sentence: "It is important to listen carefully and take notes in class. (在課堂上仔細聽講並做筆記很重要。)" },
        { word: "forever", translate: "永遠", sentence: "I thought we would be friends forever. (我以為我們會永遠是朋友。)" },
        { word: "cow", translate: "母牛", sentence: "We saw a farmer lead a few cows across the bridge. (我們看到一位農夫牽著幾頭牛過橋。)" },
        { word: "goose", translate: "鵝", sentence: "We saw several geese swimming in the lake. (我們看到幾隻鵝在湖裡游泳。)" },
        { word: "duck", translate: "鴨子", sentence: "Several foreign visitors were feeding bread to the ducks. (幾位外國遊客正在餵鴨子吃麵包。)" },
        { word: "kick", translate: "踢", sentence: "The police officers kicked the door open and caught the bad guys. (警察踢開門並抓住了壞人。)" },
        { word: "tail", translate: "尾巴", sentence: "Oliver keeps a white dog with a short tail. (奧利佛養了一隻短尾巴的白狗。)" },
        { word: "slim down", translate: "變瘦", sentence: "Jogging every day helped Brenda slim down to fifty kilograms. (每天慢跑幫助布蘭達瘦到了五十公斤。)" },
        { word: "program", translate: "計畫", sentence: "This program helps teachers create interesting science lessons. (這個計畫幫助老師們設計有趣的科學課程。)" },
        { word: "mile", translate: "英里", sentence: "The nearest supermarket is about a mile down the road. (最近的超市沿著這條路走大約一英里。)" },
        { word: "plant", translate: "種植", sentence: "My grandpa planted trees around the house. (我爺爺在房子周圍種了樹。)" },
        { word: "rose", translate: "玫瑰", sentence: "Giving someone nine roses means 'I want to be with you forever.' (送人九朵玫瑰代表「我想永遠和你在一起」。)" },
        { word: "seed", translate: "種子", sentence: "Plant seeds of hope and love; it will all come back to you. (種下希望和愛的種子；這一切都會回到你身邊。)" },
        { word: "circle", translate: "圓圈", sentence: "The math teacher drew a circle on the blackboard. (數學老師在黑板上畫了一個圓圈。)" },
        { word: "death", translate: "死亡", sentence: "Death is nothing else but going home to God, said Mother Teresa. (德蕾莎修女說：「死亡無非就是回到上帝的身邊。」)" },
        { word: "ghost", translate: "鬼", sentence: "I don't believe in ghosts. What about you? (我不相信有鬼。你呢？)" },
        { word: "band", translate: "樂團", sentence: "Mayday is one of the most famous bands in Taiwan. (五月天是台灣最著名的樂團之一。)" },
        { word: "square", translate: "廣場", sentence: "A famous band is going to play in the town square tonight. (一個著名的樂團今晚將在鎮上的廣場表演。)" },
        { word: "handsome", translate: "英俊的", sentence: "Vincent is the most handsome man I've ever met. (文森是我見過最英俊的男人。)" },
        { word: "knock down", translate: "擊倒", sentence: "You don't lose if you get knocked down; you lose if you stay down. (如果你被擊倒了，你並沒有輸；如果你一直倒地不起，你才輸了。)" },
        { word: "sail", translate: "航行", sentence: "The ship will set sail for New York City at noon. (這艘船將在中午啟航前往紐約市。)" },
        { word: "rainbow", translate: "彩虹", sentence: "The walls of the bedroom were painted all the colors of the rainbow. (臥室的牆壁漆成了彩虹的所有顏色。)" },
        { word: "hill", translate: "小山;丘陵", sentence: "Patty enjoyed the great view on the hill. (佩蒂喜歡山丘上的美麗景色。)" },
        { word: "shoulder", translate: "肩膀", sentence: "I'm always here if you ever need a shoulder to cry on. (如果你需要一個肩膀哭泣，我一直都在這裡。)" },
        { word: "root", translate: "根源", sentence: "To fix the problem, you have to get to the root of it first. (要解決這個問題，你必須先找到問題的根源。)" },
        { word: "put up with", translate: "忍受", sentence: "Cindy is not going to put up with her husband's smoking anymore. (辛蒂不想再忍受她丈夫抽菸了。)" }
    ]
};