// 確保全域變數存在，以便合併多版本、多冊的字庫
if (typeof window.englishDb === 'undefined') {
    window.englishDb = {};
}
if (!window.englishDb["南一"]) {
    window.englishDb["南一"] = {};
}

// ==========================================
// 南一版 1下 (Book 2) 完整字庫 (全單字 + 完整中文翻譯例句)
// ==========================================
window.englishDb["南一"]["一下"] = {
    "Get Ready": [
        { word: "fruit", translate: "水果", sentence: "Oranges are my favorite fruit. (橘子是我最喜歡的水果。)" },
        { word: "menu", translate: "菜單", sentence: "I am hungry. Let's take a look at the menu. (我餓了。我們來看一下菜單吧。)" },
        { word: "papaya", translate: "木瓜", sentence: "Let's eat these two papayas. (我們來吃這兩顆木瓜吧。)" },
        { word: "watermelon", translate: "西瓜", sentence: "It's hot. Let's drink some watermelon milk. (好熱。我們來喝些西瓜牛奶吧。)" },
        { word: "strawberry", translate: "草莓", sentence: "Those strawberries are big and red. (那些草莓又大又紅。)" },
        { word: "guava", translate: "芭樂", sentence: "I eat a guava after dinner every day. (我每天晚餐後吃一顆芭樂。)" },
        { word: "grape", translate: "葡萄", sentence: "Betty is drinking grape juice. (貝蒂正在喝葡萄汁。)" },
        { word: "thirsty", translate: "口渴的", sentence: "I am thirsty. Can I have some juice? (我口渴了。我可以喝點果汁嗎？)" }
    ],
    "Lesson 1": [
        { word: "Tuesday", translate: "星期二", sentence: "We don't have English class on Tuesdays. (我們星期二沒有英文課。)" },
        { word: "meat-free", translate: "無肉的;素食的", sentence: "Today is a meat-free day at my school. (今天我學校是無肉日。)" },
        { word: "Monday", translate: "星期一", sentence: "Let's go out for dinner on Monday night. (我們星期一晚上出去吃晚餐吧。)" },
        { word: "vegetable", translate: "蔬菜", sentence: "Jerry and his brother don't like vegetables. (傑瑞和他的弟弟不喜歡蔬菜。)" },
        { word: "throw away", translate: "丟掉", sentence: "Let's throw away those old boxes. (我們把那些舊箱子丟掉吧。)" },
        { word: "almost", translate: "幾乎", sentence: "It is almost 11 o'clock. Time for bed. (快十一點了。該睡覺了。)" },
        { word: "every", translate: "每一", sentence: "They dance at the park every evening. (他們每天傍晚在公園跳舞。)" },
        { word: "a lot of", translate: "很多的", sentence: "There are a lot of people in the park. (公園裡有很多人。)" },
        { word: "enough", translate: "足夠的", sentence: "We have enough food and water. (我們有足夠的食物和水。)" },
        { word: "know", translate: "知道", sentence: "Amy: Where is Micky? Rita: I don't know. (艾美：米奇在哪裡？瑞塔：我不知道。)" },
        { word: "letter", translate: "信件", sentence: "Let's write a letter to Santa. (我們寫封信給聖誕老人吧。)" },
        { word: "waste", translate: "浪費", sentence: "Don't waste water. We don't have enough water now. (不要浪費水。我們現在沒有足夠的水。)" },
        { word: "principal", translate: "校長", sentence: "Our principal is very hard-working. (我們的校長非常努力工作。)" },
        { word: "time", translate: "次數", sentence: "I throw away my vegetables almost every time. (我幾乎每次都把我的蔬菜丟掉。)" },
        { word: "week", translate: "星期;週", sentence: "There are seven days in a week. (一星期有七天。)" },
        { word: "Wednesday", translate: "星期三", sentence: "I have an English class on Wednesdays. (我星期三有英文課。)" },
        { word: "Thursday", translate: "星期四", sentence: "Let's meet on Thursday morning. (我們星期四早上見吧。)" },
        { word: "Friday", translate: "星期五", sentence: "The party is at Kenny's house at 6 p.m. on Friday. (派對在星期五下午六點於肯尼家舉行。)" },
        { word: "weekend", translate: "週末", sentence: "We don't go to school on weekends. (我們週末不上學。)" },
        { word: "Saturday", translate: "星期六", sentence: "My father doesn't go to work on Saturdays. (我爸爸星期六不上班。)" },
        { word: "Sunday", translate: "星期日", sentence: "Mother's Day is on Sunday. (母親節在星期日。)" },
        { word: "Taiwan", translate: "臺灣", sentence: "Taiwan is a beautiful island. (臺灣是一個美麗的島嶼。)" },
        { word: "thousand", translate: "千", sentence: "There are about one thousand people in the museum. (博物館裡大約有一千人。)" },
        { word: "same", translate: "相同的", sentence: "My brother and I are in the same class. (我哥哥和我同班。)" },
        { word: "hundred", translate: "百", sentence: "There are five hundred students in my school. (我們學校有五百名學生。)" },
        { word: "million", translate: "百萬", sentence: "There are one million people in this country. (這個國家有一百萬人。)" },
        { word: "hungry", translate: "餓的", sentence: "I'm so hungry. Can I have something to eat? (我好餓。可以給我一點東西吃嗎？)" },
        { word: "fight", translate: "對抗;打擊", sentence: "Captain Brave is fighting the bad guys in the TV show. (勇敢隊長正在電視節目中對抗壞人。)" },
        { word: "hour", translate: "小時", sentence: "They play basketball for an hour every Friday night. (他們每個星期五晚上打一小時的籃球。)" },
        { word: "only", translate: "只有", sentence: "Mr. and Mrs. Wang only have a daughter. (王先生和王太太只有一個女兒。)" },
        { word: "give", translate: "給予", sentence: "Please give me a pen. (請給我一支筆。)" },
        { word: "money", translate: "錢", sentence: "I don't have any money with me. (我身上沒有帶錢。)" },
        { word: "or", translate: "或者", sentence: "Don't eat or drink in the museum. (不要在博物館內飲食。)" },
        { word: "ton", translate: "噸", sentence: "We have tons of food for this big party. (我們為了這個大型派對準備了大量的食物。)" },
        { word: "hunger", translate: "飢餓", sentence: "Let's join \"Fight Hunger!\" this weekend. (我們這個週末參加「對抗飢餓」活動吧。)" },
        { word: "charity", translate: "慈善機構", sentence: "She donates a lot of money to a large charity. (她捐了很多錢給一個大型慈善機構。)" },
        { word: "event", translate: "活動;事件", sentence: "\"Save the Ocean\" is a great event for everyone. (「拯救海洋」對每個人來說都是個很棒的活動。)" },
        { word: "over", translate: "超過", sentence: "Over eight hundred million people around the world are hungry. (全世界有超過八億人正在挨餓。)" }
    ],
    "Lesson 2": [
        { word: "rain", translate: "下雨", sentence: "It rains a lot in Taiwan in summer. (臺灣夏天經常下雨。)" },
        { word: "weather", translate: "天氣", sentence: "What's the weather like today? (今天天氣如何？)" },
        { word: "visit", translate: "拜訪;參觀", sentence: "I visit my grandpa every weekend. (我每個週末去拜訪我爺爺。)" },
        { word: "robot", translate: "機器人", sentence: "Look! This is my new toy robot. (看！這是我的新玩具機器人。)" },
        { word: "hotel", translate: "飯店;旅館", sentence: "This hotel is beautiful and famous. (這家飯店既美麗又有名。)" },
        { word: "face", translate: "臉", sentence: "What's that on your face? (你臉上那是什麼？)" },
        { word: "check in", translate: "辦理入住登記", sentence: "The man over there can check you in. (那邊那個男人可以幫你辦理入住登記。)" },
        { word: "then", translate: "然後", sentence: "Let me close the door, and then we can go home. (讓我關上門，然後我們就可以回家了。)" },
        { word: "different", translate: "不同的", sentence: "Cindy and I are in different classes. (辛蒂和我不同班。)" },
        { word: "carry", translate: "提;攜帶;運送", sentence: "Let me carry the bag for you. (讓我幫你提袋子。)" },
        { word: "speak", translate: "講;說話", sentence: "Excuse me. Do you speak English? (不好意思。你會說英文嗎？)" },
        { word: "language", translate: "語言", sentence: "My English teacher can speak many languages. (我的英文老師會說很多種語言。)" },
        { word: "song", translate: "歌曲", sentence: "Lisa is writing a song for her mom now. (麗莎現在正在為她媽媽寫一首歌。)" },
        { word: "else", translate: "其他的", sentence: "Your dog is so smart. What else can he do? (你的狗好聰明。牠還會做什麼？)" },
        { word: "scan", translate: "掃描", sentence: "The robot can scan your face. (這個機器人可以掃描你的臉。)" },
        { word: "book", translate: "預訂", sentence: "Let's book a room and check it out. (我們訂一間房去一探究竟吧。)" },
        { word: "check it out", translate: "一探究竟", sentence: "Let's book a room and check it out. (我們訂一間房去一探究竟吧。)" },
        { word: "snow", translate: "下雪;雪", sentence: "It snows in New York in winter. (紐約冬天會下雪。)" },
        { word: "snowy", translate: "下雪的", sentence: "It is a snowy night with a big yellow moon. (這是一個下著雪的夜晚，有著一輪黃色的大月亮。)" },
        { word: "rainy", translate: "多雨的;雨天的", sentence: "The weather is cold and rainy. (天氣又冷又多雨。)" },
        { word: "cloud", translate: "雲", sentence: "Dark clouds are all over the sky. (烏雲布滿了整個天空。)" },
        { word: "cloudy", translate: "多雲的;陰天的", sentence: "It is cloudy. Please bring an umbrella with you. (現在多雲。請隨身帶把傘。)" },
        { word: "wind", translate: "風", sentence: "The north wind is blowing hard. (北風正強烈地吹著。)" },
        { word: "windy", translate: "風大的", sentence: "Today is a very windy day. (今天風很大。)" },
        { word: "season", translate: "季節", sentence: "What's your favorite season? (你最喜歡的季節是什麼？)" },
        { word: "spring", translate: "春季", sentence: "My favorite season is spring. (我最喜歡的季節是春天。)" },
        { word: "summer", translate: "夏季", sentence: "The kids play in the river in summer. (孩子們夏天在河裡玩耍。)" },
        { word: "fall", translate: "秋季", sentence: "The forest is very beautiful in fall. (森林在秋天非常美麗。)" },
        { word: "winter", translate: "冬季", sentence: "It is very cold here in winter. (這裡冬天非常冷。)" },
        { word: "warm", translate: "溫暖的", sentence: "Can I have some warm water, please? (請給我一些溫水好嗎？)" },
        { word: "cold", translate: "寒冷的;冰冷的", sentence: "Your hands are so cold. Are you OK? (你的手好冷。你還好嗎？)" },
        { word: "trip", translate: "旅行", sentence: "How's your trip to the USA? (你的美國之旅如何？)" },
        { word: "special", translate: "特別的", sentence: "Are you doing anything special this weekend? (你這個週末有要做什麼特別的事嗎？)" },
        { word: "build", translate: "建造", sentence: "They are building new houses by the river. (他們正在河邊建造新房子。)" },
        { word: "taste", translate: "體驗;味道", sentence: "I like the taste of beef noodles. (我喜歡牛肉麵的味道。)" },
        { word: "everything", translate: "一切", sentence: "My little sister likes everything about Mickey Mouse. (我妹妹喜歡關於米老鼠的一切。)" },
        { word: "salt", translate: "鹽", sentence: "Please put more salt on the beef. (請在牛肉上多放點鹽。)" },
        { word: "dry", translate: "乾燥的", sentence: "The river is dry in winter. (這條河在冬天是乾涸的。)" },
        { word: "fall down", translate: "倒塌;摔下", sentence: "Run! The bridge is falling down! (快跑！橋要倒塌了！)" },
        { word: "find out", translate: "找出;查明;發現", sentence: "Can you find out her phone number for me? (你能幫我查出她的電話號碼嗎？)" },
        { word: "gone", translate: "消失的", sentence: "My favorite watch is gone. I'm so sad. (我最喜歡的手錶不見了。我好難過。)" },
        { word: "style", translate: "風格;類型", sentence: "There are different styles of jackets in this shop. (這家店裡有不同款式的夾克。)" },
        { word: "salty", translate: "鹹的", sentence: "The beef noodles are too salty. (這牛肉麵太鹹了。)" },
        { word: "look for", translate: "尋找", sentence: "Are you looking for a special hotel? (你在尋找一間特別的飯店嗎？)" },
        { word: "key", translate: "關鍵", sentence: "The weather is the key. (天氣是關鍵。)" }
    ],
    "Lesson 3": [
        { word: "excuse me", translate: "抱歉;打擾", sentence: "Excuse me. Is this the right bus to the zoo? (不好意思。這是去動物園的正確公車嗎？)" },
        { word: "second", translate: "第二的", sentence: "English is the second class on Mondays. (英文是星期一的第二堂課。)" },
        { word: "third", translate: "第三的", sentence: "I'm the third child. I have two big brothers. (我是第三個孩子。我有兩個哥哥。)" },
        { word: "March", translate: "三月", sentence: "There is a party at Cindy's house on March 5. (三月五日在辛蒂家有一場派對。)" },
        { word: "holiday", translate: "假期;節日", sentence: "We are going to Japan for our holidays. (我們假期要去日本。)" },
        { word: "street", translate: "街道", sentence: "Wendy's flower shop is on Victor Street. (溫蒂的花店在維克多街。)" },
        { word: "festival", translate: "節日;節慶", sentence: "People celebrate the Moon Festival in fall. (人們在秋天慶祝中秋節。)" },
        { word: "when", translate: "何時", sentence: "Amy: When is the grass concert? Jason: It's on April 13. (艾美：草地音樂會是什麼時候？傑森：四月十三日。)" },
        { word: "full", translate: "完整的", sentence: "Dan, please write your full name here. (丹，請在這裡寫下你的全名。)" },
        { word: "date", translate: "日期", sentence: "What's the date of Peter's birthday? (彼得的生日是幾月幾日？)" },
        { word: "colorful", translate: "繽紛的", sentence: "There are colorful pictures of flowers on the table. (桌上有色彩繽紛的花朵照片。)" },
        { word: "powder", translate: "粉末", sentence: "What is the white powder for? (這白色的粉末是做什麼用的？)" },
        { word: "take off", translate: "休假", sentence: "Can I please take ten days off from school? (我可以向學校請十天假嗎？)" },
        { word: "call", translate: "稱 為", sentence: "We also call Holi the festival of colors. (我們也稱侯麗節為色彩節。)" },
        { word: "I get it.", translate: "我懂了", sentence: "Sara: Do you get it? Alice: Yes, I get it. (莎拉：你懂了嗎？愛麗絲：是的，我懂了。)" },
        { word: "month", translate: "月", sentence: "There are twelve months in a year. (一年有十二個月。)" },
        { word: "January", translate: "一月", sentence: "The festival starts on the first day of January. (節慶從一月的第一天開始。)" },
        { word: "February", translate: "二月", sentence: "Chinese New Year is in February this year. (今年的農曆新年在二月。)" },
        { word: "April", translate: "四月", sentence: "Lydia and her family go to the States in April every year. (莉迪亞和她的家人每年四月都會去美國。)" },
        { word: "May", translate: "五月", sentence: "We have a lot of rain in Taiwan from May to June. (臺灣五月到六月雨水很多。)" },
        { word: "June", translate: "六月", sentence: "I can go to your shop's opening party on June 2. (我六月二日可以去你店裡的開幕派對。)" },
        { word: "July", translate: "七月", sentence: "Jane's birthday party is on July 20. (珍的生日派對在七月二十日。)" },
        { word: "August", translate: "八月", sentence: "Father's Day in Taiwan is on August 8. (臺灣的父親節在八月八日。)" },
        { word: "September", translate: "九月", sentence: "Shelly has a trip with her sister on September 15. (雪莉九月十五日和她妹妹去旅行。)" },
        { word: "October", translate: "十月", sentence: "The welcoming party for Julia is on October 3. Are you coming? (茱莉亞的迎新派對在十月三日。你要來嗎？)" },
        { word: "November", translate: "十一月", sentence: "Thanksgiving falls on the fourth Thursday of November. (感恩節在十一月的第四個星期四。)" },
        { word: "December", translate: "十二月", sentence: "Christmas is on December 25. (聖誕節在十二月二十五日。)" },
        { word: "celebrate", translate: "慶祝", sentence: "Tom and his sister are celebrating their dad's birthday. (湯姆和他的妹妹正在慶祝他們爸爸的生日。)" },
        { word: "for example", translate: "例如", sentence: "The robot can do many things. For example, it can book tickets for you. (這個機器人會做很多事。例如，它可以幫你訂票。)" },
        { word: "each other", translate: "彼此;互相", sentence: "The man and the woman are looking at each other. (那男人和女人正看著彼此。)" },
        { word: "large", translate: "大的", sentence: "I like this table. It is large. (我喜歡這張桌子。它很大。)" },
        { word: "1st", translate: "第一的", sentence: "This is my first visit to Taipei. (這是我第一次來臺北。)" },
        { word: "knock", translate: "敲", sentence: "Please knock on the door before you enter. (進去前請敲門。)" },
        { word: "wish", translate: "祝;希望", sentence: "We wish you a happy birthday. (我們祝你生日快樂。)" },
        { word: "wash", translate: "清洗", sentence: "Brenda, please wash your hands. They are dirty. (布蘭達，請洗手。手很髒。)" },
        { word: "thing", translate: "事物;東西", sentence: "There are many things in the box. (盒子裡有很多東西。)" },
        { word: "in common", translate: "共同", sentence: "Alex and his brother have many things in common. (艾力克斯和他的哥哥有很多共通點。)" },
        { word: "mark", translate: "標示", sentence: "What marks the start of spring? (什麼標誌著春天的開始？)" },
        { word: "start", translate: "開始", sentence: "It's the start of the holidays! Let's go out and have fun. (這是假期的開始！我們出去玩吧。)" },
        { word: "costume", translate: "化裝服", sentence: "There are many costumes in that store. (那家店裡有很多化裝服。)" },
        { word: "luck", translate: "運氣", sentence: "Good luck with everything! (祝一切順利！)" },
        { word: "celebration", translate: "慶祝活動", sentence: "It's my grandpa's ninetieth birthday. We are having a big celebration. (這是我爺爺的九十歲生日。我們要舉行盛大的慶祝活動。)" },
        { word: "other", translate: "其他的", sentence: "How do other countries celebrate the New Year? (其他國家如何慶祝新年？)" }
    ],
    "Lesson 4": [
        { word: "make", translate: "製作", sentence: "Jessica is making a cake for her son. (潔西卡正在為她的兒子做一個蛋糕。)" },
        { word: "paper", translate: "紙", sentence: "The students draw a cat on paper in art class. (學生們在美術課上用紙畫了一隻貓。)" },
        { word: "which", translate: "哪一個", sentence: "Sam: Which do you like, apples or oranges? Alex: I like apples. (山姆：你喜歡哪一個，蘋果還是橘子？艾力克斯：我喜歡蘋果。)" },
        { word: "choice", translate: "選擇", sentence: "Sorry. You have no choice. (抱歉。你別無選擇。)" },
        { word: "walk", translate: "走路", sentence: "Leila walks to school every day. (蕾拉每天走路去上學。)" },
        { word: "collect", translate: "收集", sentence: "The man is collecting pens of different colors. (這個男人正在收集不同顏色的筆。)" },
        { word: "much", translate: "很多的", sentence: "Don't drink too much coffee in a day. (一天不要喝太多咖啡。)" },
        { word: "need", translate: "需要", sentence: "I need some salt for this dish. (這道菜我需要一點鹽。)" },
        { word: "half", translate: "一半", sentence: "Half of the students in the classroom are girls. (教室裡一半的學生是女孩。)" },
        { word: "piece", translate: "張;片", sentence: "Please bring three pieces of paper to school tomorrow. (明天請帶三張紙到學校。)" },
        { word: "boil", translate: "烹煮;煮沸", sentence: "Jamie is boiling vegetables for lunch. (傑米正在煮午餐的蔬菜。)" },
        { word: "after", translate: "在……之後", sentence: "Jane walks in the park after lunch. (珍午餐後在公園散步。)" },
        { word: "screen", translate: "篩子;螢幕", sentence: "Wash the screen on the door. It's dirty. (把門上的紗窗洗一洗。它很髒。) / Sara's picture is on the screen. (莎拉的照片在螢幕上。)" },
        { word: "work", translate: "工作", sentence: "My dad is at work right now. (我爸爸現在在工作。)" },
        { word: "tour guide", translate: "導遊", sentence: "The tour guide is showing us around. (導遊正在帶我們四處參觀。)" },
        { word: "poop", translate: "糞便", sentence: "Please collect poop in the bucket. (請將大便收集在桶子裡。)" },
        { word: "bucket", translate: "桶", sentence: "I need 4 buckets of water. (我需要四桶水。)" },
        { word: "get", translate: "拿取;獲得", sentence: "First, get a bucket and collect some poop. (首先，拿一個桶子並收集一些大便。)" },
        { word: "pumpkin pie", translate: "南瓜派", sentence: "Mom is making a pumpkin pie. I can't wait. (媽媽正在做南瓜派。我等不及了。)" },
        { word: "fried chicken", translate: "炸雞", sentence: "Let's have fried chicken for dinner. (我們晚餐吃炸雞吧。)" },
        { word: "coffee", translate: "咖啡", sentence: "Have a cup of coffee and take a break. (喝杯咖啡休息一下。)" },
        { word: "juice", translate: "果汁", sentence: "A glass of juice, please. (請給我一杯果汁。)" },
        { word: "rice", translate: "米飯", sentence: "I eat two bowls of rice for lunch every day. (我每天午餐吃兩碗飯。)" },
        { word: "pork", translate: "豬肉", sentence: "The restaurant is famous for its pork dishes. (這家餐廳以豬肉料理聞名。)" },
        { word: "dozen", translate: "十二個;一打", sentence: "I would like two dozen eggs, please. (請給我兩打雞蛋。)" },
        { word: "bread", translate: "麵包", sentence: "Emily's lunch today is a slice of bread and a cup of tea. (艾蜜莉今天的午餐是一片麵包和一杯茶。)" },
        { word: "slice", translate: "片", sentence: "Would you like a slice of bread? (你想要一片麵包嗎？)" },
        { word: "useful", translate: "有用的", sentence: "English is useful. You can make friends from different countries. (英文很有用。你可以交到來自不同國家的朋友。)" },
        { word: "mean", translate: "意思是", sentence: "What does the teacher mean? (老師是什麼意思？)" },
        { word: "power", translate: "動力", sentence: "The car runs on green power. (這輛車靠綠色動力行駛。)" },
        { word: "garbage", translate: "垃圾;廢物", sentence: "Adam, take out the garbage now, please. (亞當，請現在把垃圾拿出去。)" },
        { word: "in other words", translate: "換句話說", sentence: "Grace always gets points in every basketball game. In other words, she is good at basketball. (葛蕾絲在每場籃球比賽都能得分。換句話說，她很擅長打籃球。)" },
        { word: "gas", translate: "氣體燃料;汽油", sentence: "The car is running out of gas. It can't move now. (車子快沒油了。現在動不了了。)" },
        { word: "believe", translate: "相信", sentence: "Can you believe it? The winner of the game is a 10-year-old boy. (你相信嗎？比賽的贏家是一個十歲的小男孩。)" },
        { word: "human", translate: "人類的", sentence: "How small can the human eye see? (人類的眼睛能看到多小的東西？)" },
        { word: "kilometer", translate: "公里", sentence: "Tom walks three kilometers to school every morning. (湯姆每天早上走三公里去上學。)" },
        { word: "tank", translate: "槽", sentence: "The water tank is full. (水槽滿了。)" },
        { word: "stinky", translate: "臭的", sentence: "What are you eating? It's stinky! (你在吃什麼？好臭！)" },
        { word: "kind", translate: "種類", sentence: "A special kind of bus runs in England. (英國有一種特別的公車。)" }
    ],
    "Lesson 5": [
        { word: "senior high school", translate: "高中", sentence: "Jerry is now a senior high school student. (傑瑞現在是一名高中生。)" },
        { word: "reporter", translate: "記者", sentence: "John is a reporter. He collects stories from all over the world. (約翰是名記者。他收集來自世界各地的故事。)" },
        { word: "ask", translate: "詢問", sentence: "Jack always asks a lot of questions in English class. (傑克總是在英文課問很多問題。)" },
        { word: "question", translate: "問題", sentence: "Do you have any questions? (你們有任何問題嗎？)" },
        { word: "another", translate: "另一個的", sentence: "I want another cup of tea. (我想要另一杯茶。)" },
        { word: "win", translate: "勝利", sentence: "It is our team's first win this year. (這是我們隊伍今年的首勝。)" },
        { word: "often", translate: "時常", sentence: "How often do you visit your grandpa? (你多常拜訪你爺爺？)" },
        { word: "train", translate: "訓練", sentence: "The athletes train five times a day. It is so hard. (運動員一天訓練五次。真辛苦。)" },
        { word: "twice", translate: "兩次", sentence: "The Huang family goes out for dinner twice a week. (黃家人一星期出去吃兩次晚餐。)" },
        { word: "homework", translate: "作業", sentence: "How much homework does Anna get? (安娜有多少作業？)" },
        { word: "tug of war", translate: "拔河", sentence: "Tom and his brother are on the tug of war team. (湯姆和他的哥哥在拔河隊。)" },
        { word: "each", translate: "每一個", sentence: "There is a lot of effort behind each story. (每個故事背後都有很多努力。)" },
        { word: "Hard work pays off.", translate: "努力就會有收穫。", sentence: "Hard work pays off. (努力就會有收穫。)" },
        { word: "always", translate: "總是;永遠", sentence: "Ivy is always smiling. (艾薇總是面帶微笑。)" },
        { word: "usually", translate: "通常", sentence: "What do you usually do on weekends? (你週末通常做什麼？)" },
        { word: "sometimes", translate: "有時候", sentence: "I sometimes go on a picnic with my family in the park. (我有時和家人去公園野餐。)" },
        { word: "seldom", translate: "很少", sentence: "David seldom watches TV after work. (大衛下班後很少看電視。)" },
        { word: "never", translate: "從不;未曾", sentence: "Ben is never late for class. (班上課從不遲到。)" },
        { word: "once", translate: "一次;曾經", sentence: "He plays basketball once a week. (他一星期打一次籃球。)" },
        { word: "on time", translate: "準時", sentence: "Andy always goes to school on time. (安迪上學總是準時。)" },
        { word: "life", translate: "生活;人生", sentence: "Ella doesn't know much about her grandma's early life. (艾拉對她奶奶早期的生活了解不多。)" },
        { word: "early", translate: "早的", sentence: "It usually rains in early spring in Taiwan. (臺灣的初春通常會下雨。)" },
        { word: "swim", translate: "游泳", sentence: "Let's go swimming. It's good for our health. (我們去游泳吧。這對我們的健康有益。)" },
        { word: "jump rope", translate: "跳繩", sentence: "The students are jumping rope now. (學生們現在正在跳繩。)" },
        { word: "get hurt", translate: "受傷", sentence: "Don't get hurt. (不要受傷。)" },
        { word: "during", translate: "在…期間", sentence: "Please don't talk during the movie. (電影播放期間請不要說話。)" },
        { word: "sick", translate: "生病的", sentence: "The doctor says, \"You're sick. Take a day off from work.\" (醫生說：「你生病了。請一天假吧。」)" },
        { word: "stop", translate: "停止", sentence: "Stop the car! There is a child behind the car. (停車！車後面有個小孩。)" },
        { word: "sport", translate: "運動", sentence: "What sports do you play? (你做什麼運動？)" },
        { word: "care", translate: "在乎;關心", sentence: "You care too much about your looks. (你太在意自己的外表了。)" },
        { word: "notice", translate: "注意到", sentence: "We seldom notice a mother's hard work at home. (我們很少注意到母親在家的辛勞。)" },
        { word: "athlete", translate: "運動員", sentence: "Who is your favorite baseball athlete? (你最喜歡的棒球運動員是誰？)" },
        { word: "trophy", translate: "獎盃", sentence: "The winner can get a trophy and a lot of money. (贏家可以得到一個獎盃和很多錢。)" },
        { word: "effort", translate: "努力", sentence: "Jane always puts effort into her work. (珍總是對她的工作投入努力。)" },
        { word: "You rock!", translate: "很棒;很厲害!", sentence: "You rock! (很棒；很厲害！)" }
    ],
    "Lesson 6": [
        { word: "sky", translate: "天空", sentence: "There are a lot of birds in the sky. (天空中有很多鳥。)" },
        { word: "clear", translate: "晴朗的", sentence: "You can see the mountains from here on a clear day. (在晴朗的日子裡，你可以從這裡看到群山。)" },
        { word: "lost", translate: "迷路的", sentence: "My little brother often gets lost. (我弟弟經常迷路。)" },
        { word: "sure", translate: "確定的", sentence: "Ken: Is that Cindy's bag? Joy: I'm not sure. (肯：那是辛蒂的包包嗎？喬伊：我不確定。)" },
        { word: "woman", translate: "女人", sentence: "Who's that tall woman over there? (那邊那個高個子女人是誰？)" },
        { word: "map", translate: "地圖", sentence: "I can't read the map. Can you help me? (我看不懂地圖。你能幫我嗎？)" },
        { word: "straight", translate: "直地", sentence: "Go straight along this street, and you can see the school. (沿著這條街直走，你就能看到學校。)" },
        { word: "turn", translate: "轉向", sentence: "Please turn right at the next corner. (請在下一個轉角右轉。)" },
        { word: "left", translate: "左邊", sentence: "Turn left and you can see a fish shop. (左轉你就能看到一家魚店。)" },
        { word: "along", translate: "沿著", sentence: "You can see a lot of flowers along the river. (你可以沿著河邊看到許多花。)" },
        { word: "road", translate: "路", sentence: "The famous restaurant is on the very busy road. (那家有名的餐廳在那條非常繁忙的路上。)" },
        { word: "block", translate: "街區", sentence: "My home is two blocks away from the park. (我家離公園兩個街區遠。)" },
        { word: "station", translate: "車站", sentence: "There is a train station near my house. (我家附近有一個火車站。)" },
        { word: "idea", translate: "想法;主意", sentence: "That's a good idea. (那是個好主意。)" },
        { word: "minute", translate: "分鐘", sentence: "There are sixty minutes in an hour. (一小時有六十分鐘。)" },
        { word: "wait", translate: "等一下;等待", sentence: "I am waiting for the bus. (我正在等公車。)" },
        { word: "wrong", translate: "錯誤的", sentence: "Sorry. You have the wrong number. (抱歉。你打錯電話了。)" },
        { word: "fair", translate: "園遊會,展覽", sentence: "We are having a good time at the school fair. (我們在學校園遊會玩得很開心。)" },
        { word: "corner", translate: "街角", sentence: "Go straight and turn left at the first corner. (直走並在第一個轉角左轉。)" },
        { word: "right", translate: "右邊", sentence: "The school is on your right. / Turn right on Moon Street. (學校在你的右邊。 / 在月亮街右轉。)" },
        { word: "bank", translate: "銀行", sentence: "There is a bank on Rainbow Street. (彩虹街上有一家銀行。)" },
        { word: "movie theater", translate: "電影院", sentence: "The new movie theater is big and beautiful. (這家新電影院又大又漂亮。)" },
        { word: "cross", translate: "跨越", sentence: "Don't cross the street. The car is coming fast. (不要穿越馬路。車子開得很快。)" },
        { word: "across from", translate: "在...對面", sentence: "The restaurant is across from the park. (這家餐廳在公園對面。)" },
        { word: "in back of", translate: "在...後面", sentence: "Sara sits in back of me. (莎拉坐在我後面。)" },
        { word: "bakery", translate: "麵包店", sentence: "I usually go to the bakery after school. (我放學後通常會去麵包店。)" },
        { word: "library", translate: "圖書館", sentence: "Please don't run in the library. (請不要在圖書館裡跑步。)" },
        { word: "hospital", translate: "醫院", sentence: "My brother works in the hospital. (我哥哥在醫院工作。)" },
        { word: "foot", translate: "腳", sentence: "Do you go to school by bus or on foot? (你搭公車還是走路去上學？)" },
        { word: "metro", translate: "地鐵;捷運", sentence: "Let's go to the zoo by metro. (我們搭捷運去動物園吧。)" },
        { word: "boat", translate: "船", sentence: "We go to Green Island by boat. (我們搭船去綠島。)" },
        { word: "ride", translate: "騎;乘坐", sentence: "Can you ride a bike? (你會騎腳踏車嗎？)" },
        { word: "horse", translate: "馬", sentence: "Look! Those kids are feeding horses. (看！那些孩子正在餵馬。)" },
        { word: "hike", translate: "長途步行", sentence: "People often go hiking on sunny days. (人們經常在晴朗的日子去健行。)" },
        { word: "may", translate: "也許", sentence: "It is cloudy. It may rain in the afternoon. (多雲。下午可能會下雨。)" },
        { word: "dangerous", translate: "危險的", sentence: "Don't play with fire. It is dangerous. (不要玩火。這很危險。)" },
        { word: "will", translate: "決心", sentence: "Where there's a will, there's a way. (有志者，事竟成。)" },
        { word: "nothing", translate: "沒有(東西)", sentence: "There is nothing in the bag. (袋子裡什麼都沒有。)" },
        { word: "sleigh", translate: "雪橇", sentence: "Do you like to ride on sleighs? (你喜歡坐雪橇嗎？)" },
        { word: "mate", translate: "夥伴", sentence: "Teresa is my best mate. We always help each other. (泰瑞莎是我最好的夥伴。我們總是互相幫助。)" },
        { word: "weekday", translate: "平日", sentence: "On weekdays, I usually go to bed at 10 o'clock. (平日我通常十點上床睡覺。)" },
        { word: "train", translate: "火車", sentence: "There are many ways to school. By metro, by train, or by boat. (有很多去學校的方式。搭捷運、搭火車或搭船。)" },
        { word: "stand in ... way", translate: "阻礙", sentence: "Nothing can stand in their way. (沒有什麼能阻擋他們。)" },
        { word: "I see.", translate: "我懂了。", sentence: "I see. (我懂了。)" }
    ]
};