// 確保全域變數存在，以便合併多冊字庫
if (typeof window.englishDb === 'undefined') {
    window.englishDb = {};
}
if (!window.englishDb["康軒"]) {
    window.englishDb["康軒"] = {};
}

// ==========================================
// 康軒 1下 完整字庫 (全單字 + 完整中文翻譯例句)
// ==========================================
window.englishDb["康軒"]["一下"] = {
    "Get Ready": [
        { word: "fruit", translate: "水果", sentence: "Oranges are my favorite fruit. (橘子是我最喜歡的水果。)" },
        { word: "menu", translate: "菜單", sentence: "I am hungry. Let's take a look at the menu. (我餓了。我們來看一下菜單吧。)" },
        { word: "papaya", translate: "木瓜", sentence: "Let's eat these two papayas. (我們來吃這兩顆木瓜吧。)" },
        { word: "watermelon", translate: "西瓜", sentence: "It's hot. Let's drink some watermelon milk. (好熱。我們來喝些西瓜牛奶吧。)" },
        { word: "strawberry", translate: "草莓", sentence: "Those strawberries are big and red. (那些草莓又大又紅。)" },
        { word: "guava", translate: "芭樂", sentence: "I eat a guava after dinner every day. (我每天晚餐後吃一顆芭樂。)" },
        { word: "grape", translate: "葡萄", sentence: "Betty is drinking grape juice. (貝蒂正在喝葡萄汁。)" },
        { word: "thirsty", translate: "口渴的", sentence: "I am thirsty. Can I have some juice? (我口渴了。我可以喝點果汁嗎？)" }
    ],
    "Lesson 1": [
        { word: "get up", translate: "起床", sentence: "I get up at 6:30 every morning. (我每天早上六點半起床。)" },
        { word: "teeth", translate: "牙齒", sentence: "Toby brushes his teeth every night. (托比每天晚上刷牙。)" },
        { word: "face", translate: "臉", sentence: "Helen has a beautiful face. (海倫有一張美麗的臉龐。)" },
        { word: "exercise", translate: "運動", sentence: "Let's exercise in the gym. (我們在體育館運動吧。)" },
        { word: "breakfast", translate: "早餐", sentence: "Susan has milk tea and a sandwich for breakfast every day. (蘇珊每天早餐喝奶茶配三明治。)" },
        { word: "bath", translate: "泡澡;洗澡", sentence: "My brother takes a bath every morning. (我哥哥每天早上泡澡。)" },
        { word: "homework", translate: "家庭作業", sentence: "Fred is doing his homework in his room. (弗雷德正在他的房間寫作業。)" },
        { word: "baseball", translate: "棒球", sentence: "I watch baseball games on weekends. (我週末都會看棒球比賽。)" },
        { word: "soccer", translate: "足球", sentence: "Frank does not like soccer. (法蘭克不喜歡足球。)" },
        { word: "video game", translate: "電玩遊戲", sentence: "David and his friends are playing video games in the living room. (大衛和他的朋友們正在客廳打電動。)" },
        { word: "practice", translate: "練習", sentence: "Judy and her friends are practicing baseball at school. (茱蒂和她的朋友們正在學校練習棒球。)" },
        { word: "every", translate: "每一", sentence: "My friends and I practice English every day. (我和朋友每天練習英文。)" },
        { word: "team", translate: "隊伍", sentence: "I am on the school basketball team. (我是學校籃球隊的一員。)" },
        { word: "know", translate: "知道", sentence: "Ben: Do you know that man? Ann: Yes, he's my uncle. (班：你認識那個男人嗎？安：是的，他是我叔叔。)" },
        { word: "player", translate: "運動員;選手", sentence: "Jason is a very good soccer player. (傑森是個很棒的足球員。)" },
        { word: "grade", translate: "成績", sentence: "We are here for fun, not for grades. (我們來這裡是為了樂趣，不是為了成績。)" },
        { word: "test", translate: "考試", sentence: "Rita is studying for her math tests. (瑞塔正在準備她的數學考試。)" },
        { word: "study", translate: "學習;研讀", sentence: "I study English and math every day. (我每天讀英文和數學。)" },
        { word: "either", translate: "也(用於否定句)", sentence: "Ken: I don't like the song. Leo: I don't like it, either. (肯：我不喜歡這首歌。里歐：我也不喜歡。)" },
        { word: "must", translate: "一定;必須", sentence: "It is late. You must go home now. (時間晚了。你現在必須回家。)" },
        { word: "enjoy", translate: "享受", sentence: "I enjoy my school life. What about you? (我很享受學校生活。你呢？)" },
        { word: "then", translate: "那麼;然後;當時", sentence: "John, get a papaya. Then make some papaya milk. (約翰，拿一顆木瓜。然後做些木瓜牛奶。)" },
        { word: "ticket", translate: "票;券", sentence: "Paul: I have two tickets for the baseball game. Betty: Can I go with you? (保羅：我有兩張棒球比賽的票。貝蒂：我可以跟你一起去嗎？)" },
        { word: "together", translate: "一起", sentence: "My sister and I go to school together every day. (我妹妹和我每天一起上學。)" },
        { word: "how much", translate: "多少錢", sentence: "Zack: How much are these shelves? Ally: They are eight hundred dollars. (柴克：這些架子多少錢？艾莉：八百元。)" },
        { word: "hundred", translate: "百", sentence: "There are one hundred photos inside the box. (盒子裡有一百張照片。)" },
        { word: "dollar", translate: "元", sentence: "Rita: How much is the cake? John: It's fifty dollars. (瑞塔：這塊蛋糕多少錢？約翰：五十元。)" },
        { word: "badminton", translate: "羽毛球", sentence: "Paul and his sister are playing badminton in the park. (保羅和他的妹妹正在公園打羽毛球。)" },
        { word: "tennis", translate: "網球", sentence: "My dad is playing tennis with my mom. (我爸爸正在和我媽媽打網球。)" },
        { word: "ask", translate: "問;要求", sentence: "We cannot download the game. Let's ask Simon for help. (我們無法下載這個遊戲。我們請賽門幫忙吧。)" },
        { word: "happen", translate: "發生", sentence: "There are mice here. Does this happen every day? (這裡有老鼠。這每天都發生嗎？)" },
        { word: "fast", translate: "快速的", sentence: "My brother is a fast runner. (我哥哥跑得很快。)" },
        { word: "move", translate: "移動;搬家", sentence: "Please move your car. (請移動你的車。)" },
        { word: "hit", translate: "擊;打;襲擊", sentence: "Don't hit your brother with the toy. Be a good girl. (不要用玩具打你弟弟。做個乖女孩。)" },
        { word: "fun", translate: "樂趣;有趣的", sentence: "Ms. Wilson's English classes are a lot of fun. (威爾森老師的英文課很有趣。)" },
        { word: "win", translate: "贏", sentence: "Ann: Can you win the tennis game? Tom: Yes, I can. (安：你能贏得這場網球比賽嗎？湯姆：是的，我可以。)" },
        { word: "lose", translate: "輸掉(比賽);失去", sentence: "We cannot lose the game this Friday. Let's practice again. (這個星期五的比賽我們不能輸。我們再練習一次吧。)" },
        { word: "side", translate: "邊;面", sentence: "The slide is on the right side of the playground. (溜滑梯在遊樂場的右側。)" },
        { word: "touch", translate: "接觸;觸碰", sentence: "Don't touch the baby. He is sleeping. (不要碰這個嬰兒。他正在睡覺。)" },
        { word: "last", translate: "最後的;前一個的", sentence: "Can I have the last banana in the basket, Mom? (媽，我可以吃籃子裡最後一根香蕉嗎？)" },
        { word: "point", translate: "得分;觀點", sentence: "Draw a picture of your family, and you can get five points. (畫一張你家人的畫，你就可以得到五分。)" }
    ],
    "Lesson 2": [
        { word: "housework", translate: "家事", sentence: "William helps his father with the housework every day. (威廉每天幫他爸爸做家事。)" },
        { word: "mop", translate: "拖(地);拖把", sentence: "Let's mop the floor together. (我們一起拖地吧。)" },
        { word: "floor", translate: "地板;樓層", sentence: "There is a big box on the floor. (地板上有一個大箱子。)" },
        { word: "clean", translate: "打掃;乾淨的", sentence: "The room is dirty. Let's clean it together. (房間很髒。我們一起打掃吧。)" },
        { word: "trash", translate: "垃圾", sentence: "There is a lot of trash in the house. It is dirty. (房子裡有很多垃圾。很髒。)" },
        { word: "do the dishes", translate: "洗碗盤", sentence: "Rebecca does the dishes after dinner every evening. (蕾貝卡每天晚上吃完晚餐後都會洗碗。)" },
        { word: "set", translate: "布置;設定", sentence: "Amber is setting the table in the dining room. (安珀正在餐廳布置餐桌。)" },
        { word: "street", translate: "街道", sentence: "The movie theater is on a busy street. (電影院在一條熱鬧的街上。)" },
        { word: "market", translate: "市場", sentence: "Ron goes to the market with his dad every Sunday morning. (榮恩每個星期天早上都和爸爸去市場。)" },
        { word: "town", translate: "城鎮", sentence: "There is a library in town. (鎮上有一座圖書館。)" },
        { word: "anytime", translate: "任何時候", sentence: "You can ask questions anytime. (你隨時都可以問問題。)" },
        { word: "seldom", translate: "很少", sentence: "I seldom eat out. My parents often prepare meals for us. (我很少在外用餐。我父母常為我們準備餐點。)" },
        { word: "always", translate: "總是", sentence: "Ivan always works out in the gym after school. (伊凡放學後總是在健身房運動。)" },
        { word: "habit", translate: "習慣", sentence: "Sally always takes a rest after lunch. That is her habit. (莎莉午餐後總是會休息。那是她的習慣。)" },
        { word: "never", translate: "從不", sentence: "Alan goes to bed early every night. He is never late for school. (艾倫每晚都很早睡。他上學從不遲到。)" },
        { word: "break", translate: "打破;休息", sentence: "My brother gets up at 6 a.m. every day. He never breaks his habit. (我哥哥每天早上六點起床。他從不打破他的習慣。)" },
        { word: "often", translate: "時常", sentence: "Nancy often eats two eggs for breakfast. (南西早餐時常吃兩顆蛋。)" },
        { word: "sometimes", translate: "有時候", sentence: "Sean often drinks milk in the morning, but he sometimes drinks juice. (尚恩早上時常喝牛奶，但他有時候喝果汁。)" },
        { word: "sure", translate: "確定的", sentence: "Nina: Is that Tina's cousin? Harry: Hmm... I'm not really sure. (妮娜：那是蒂娜的表哥嗎？哈利：嗯...我不是很確定。)" },
        { word: "place", translate: "地方", sentence: "Taiwan is a great place to me. (台灣對我來說是個好地方。)" },
        { word: "usually", translate: "通常", sentence: "We usually go to school at 7 a.m. (我們通常早上七點上學。)" },
        { word: "dirty", translate: "髒的", sentence: "Your room is very dirty. Clean it now! (你的房間很髒。現在就打掃！)" },
        { word: "month", translate: "月", sentence: "There are twelve months in a year. (一年有十二個月。)" },
        { word: "believe", translate: "相信", sentence: "Irene: I cook dinner for my parents every day. Greg: Come on! I don't believe you. (艾琳：我每天都為父母煮晚餐。葛瑞格：少來了！我不相信你。)" },
        { word: "once", translate: "一次", sentence: "Tina goes to the library once a week. (蒂娜每週去圖書館一次。)" },
        { word: "twice", translate: "兩次", sentence: "My brother loves animals. He goes to the zoo twice a month. (我弟弟喜歡動物。他每個月去兩次動物園。)" },
        { word: "terrible", translate: "可怕的;糟糕的", sentence: "Jayden: There is a lot of trash in the living room. Zoey: That's terrible. (傑登：客廳裡有很多垃圾。柔依：那真糟糕。)" },
        { word: "how often", translate: "多常", sentence: "Ashley: How often do you have a group chat? Peter: We have a group chat three times a week. (艾希莉：你們多常進行群組聊天？彼得：我們每週群聊三次。)" },
        { word: "cellphone", translate: "手機", sentence: "Stella: What's your cellphone number? Philip: It's 0988-123-456. (史黛拉：你的手機號碼是多少？菲利普：是0988-123-456。)" },
        { word: "following", translate: "下列事物", sentence: "Please read the following with me. (請跟我一起讀下列內容。)" },
        { word: "may / might", translate: "可能;也許", sentence: "It might be cold, but it is still a nice day. (天氣也許會冷，但仍是美好的一天。)" },
        { word: "change", translate: "改變", sentence: "I do not like this color. Please change it. (我不喜歡這個顏色。請換掉它。)" },
        { word: "more", translate: "更多的", sentence: "I am hungry. I want more sandwiches. (我餓了。我想要更多三明治。)" },
        { word: "germ", translate: "細菌", sentence: "There are a lot of germs on the swings. (鞦韆上有很多細菌。)" },
        { word: "toilet seat", translate: "馬桶座", sentence: "Don't be lazy! Let's clean the toilet seat every night. (別偷懶！我們每晚都來清洗馬桶座吧。)" },
        { word: "answer", translate: "答案;回答", sentence: "Edward: Do you know the answer to this question? Olivia: Yes, it's B. (愛德華：你知道這個問題的答案嗎？奧莉薇亞：知道，是B。)" },
        { word: "for example", translate: "舉例來說", sentence: "Zoe likes fruit. For example, she likes guavas and oranges. (柔依喜歡水果。舉例來說，她喜歡芭樂和橘子。)" },
        { word: "free", translate: "空閒的;免費的", sentence: "Lily: What do you usually do in your free time? Ken: I watch TV. (莉莉：你空閒時通常做什麼？肯：我看電視。)" },
        { word: "finger", translate: "手指", sentence: "Mandy, your fingers are dirty. Wash them, and then you can eat. (曼蒂，妳的手指很髒。洗一洗，然後妳就可以吃了。)" },
        { word: "kill", translate: "殺", sentence: "The mouse is really cute. Don't kill it. (這隻老鼠真的很可愛。不要殺牠。)" },
        { word: "time", translate: "次數", sentence: "I go to the movies six times a year. (我一年去看六次電影。)" },
        { word: "work", translate: "工作", sentence: "Are you at work right now? Can we meet for lunch? (你現在在上班嗎？我們可以見面吃午餐嗎？)" }
    ],
    "Lesson 3": [
        { word: "January", translate: "一月", sentence: "The year starts with January. (一年從一月開始。)" },
        { word: "February", translate: "二月", sentence: "There are only 28 or 29 days in February. (二月只有28天或29天。)" },
        { word: "March", translate: "三月", sentence: "My mom's birthday is on March 8. (我媽媽的生日在三月八日。)" },
        { word: "April", translate: "四月", sentence: "Peter goes to the USA every April. (彼得每年四月都會去美國。)" },
        { word: "May", translate: "五月", sentence: "Mother's Day is on the second Sunday in May. (母親節在五月的第二個星期天。)" },
        { word: "June", translate: "六月", sentence: "June is the 6th month of the year. (六月是一年中的第六個月。)" },
        { word: "July", translate: "七月", sentence: "We do not go to school in July. (我們七月不用去上學。)" },
        { word: "August", translate: "八月", sentence: "Father's Day in Taiwan is on August 8th. (台灣的父親節在八月八日。)" },
        { word: "September", translate: "九月", sentence: "Teacher's Day is in September. (教師節在九月。)" },
        { word: "October", translate: "十月", sentence: "October 10 is a holiday in Taiwan. (十月十日是台灣的假日。)" },
        { word: "November", translate: "十一月", sentence: "November is between October and December. (十一月在十月和十二月之間。)" },
        { word: "December", translate: "十二月", sentence: "December means the end of a year. (十二月意味著一年的結束。)" },
        { word: "Easter", translate: "復活節", sentence: "Children often find eggs in the garden on Easter. (孩子們常在復活節時在花園裡找彩蛋。)" },
        { word: "Halloween", translate: "萬聖節前夕", sentence: "People in the USA often wear special clothes on Halloween. (美國人常在萬聖節前夕穿著特別的衣服。)" },
        { word: "Thanksgiving", translate: "感恩節", sentence: "Thanksgiving is a holiday in the USA. (感恩節是美國的節日。)" },
        { word: "Christmas", translate: "聖誕節", sentence: "Alex and his family usually get together at Christmas. (艾力克斯和他的家人通常在聖誕節團聚。)" },
        { word: "holiday", translate: "節日;假期", sentence: "Ivy is on holiday this week. (艾薇這週在休假。)" },
        { word: "race", translate: "賽跑;競賽", sentence: "Let's watch the car race this Sunday. (我們這個星期天來看賽車吧。)" },
        { word: "whose", translate: "誰的", sentence: "Zack: Whose blanket is on the table? Joan: That's Rita's. (柴克：桌上是誰的毯子？瓊：那是瑞塔的。)" },
        { word: "when", translate: "何時", sentence: "Leo: When is the meeting with the students in New York City? Kelly: It's at 8 p.m. (里歐：與紐約市學生的會議是什麼時候？凱莉：在晚上八點。)" },
        { word: "second", translate: "第二的;秒", sentence: "My second class starts at 9:10 a.m. (我的第二堂課在早上九點十分開始。)" },
        { word: "date", translate: "日期;約會", sentence: "Ann: What's the date today? Ben: It's May 28th. (安：今天是幾月幾日？班：五月二十八日。)" },
        { word: "third", translate: "第三(的)", sentence: "Tuesday is the third day of the week. (星期二是這週的第三天。)" },
        { word: "away", translate: "離...之遠", sentence: "Today is August 28th. Teacher's Day is one month away. (今天是八月二十八日。距離教師節還有一個月。)" },
        { word: "first", translate: "第一(的)", sentence: "David is the first child in his family. (大衛是他家裡的第一個孩子。)" },
        { word: "runner", translate: "跑者", sentence: "The runners are running on the sports field. (跑者們正在運動場上跑步。)" },
        { word: "over there", translate: "在那邊", sentence: "Lisa: Who's the boy over there? Bill: He's Gina's brother. (麗莎：在那邊的男孩是誰？比爾：他是吉娜的哥哥。)" },
        { word: "take care of", translate: "照顧", sentence: "My sister has a pet. She takes care of it every day. (我妹妹有一隻寵物。她每天照顧牠。)" },
        { word: "play the role of...", translate: "扮演...的角色", sentence: "Angela plays the role of a beautiful nurse in the movie. (安琪拉在這部電影中扮演一位美麗的護士。)" },
        { word: "letter", translate: "信件;字母", sentence: "Daniel is writing a letter to his old friend. (丹尼爾正在寫信給他的老朋友。)" },
        { word: "dear", translate: "親愛的", sentence: "Nice to see you again, my dear friend. (很高興再次見到你，我親愛的朋友。)" },
        { word: "busy", translate: "忙碌的", sentence: "I cannot answer the phone. I am busy now. (我無法接電話。我現在很忙。)" },
        { word: "miss", translate: "想念", sentence: "Clara is in Japan. She misses her grandparents in Taiwan. (克拉拉在日本。她很想念在台灣的祖父母。)" },
        { word: "everything", translate: "一切事物", sentence: "Linda: Is everything all right? Jacob: Yes, thanks. (琳達：一切都好嗎？雅各：是的，謝謝。)" },
        { word: "love", translate: "愛", sentence: "We always get a lot of love from our parents. (我們總是從父母那裡得到很多愛。)" }
    ],
    "Lesson 4": [
        { word: "food", translate: "食物", sentence: "The food here is yummy. Let's have dinner here. (這裡的食物很好吃。我們在這裡吃晚餐吧。)" },
        { word: "bottle", translate: "瓶子", sentence: "Owen: Where is the water bottle? Julie: Isn't it on the table? (歐文：水瓶在哪裡？茱莉：不是在桌上嗎？)" },
        { word: "water", translate: "水;澆水", sentence: "Ian: I'm thirsty. Can I have some water? Mary: Sure. Here you are. (伊恩：我口渴了。可以給我一些水嗎？瑪麗：沒問題。給你。)" },
        { word: "bowl", translate: "碗", sentence: "Thomas: Can I have a bowl of rice? Michelle: Sure, you can. (湯瑪斯：我可以要一碗飯嗎？蜜雪兒：當然可以。)" },
        { word: "rice", translate: "米;飯", sentence: "We eat rice for lunch at school every day. (我們每天在學校午餐都吃飯。)" },
        { word: "plate", translate: "盤子", sentence: "Please wash these plates after lunch. (午餐後請把這些盤子洗一洗。)" },
        { word: "noodle", translate: "麵條", sentence: "Ken: Let's eat noodles for dinner. Lena: That's a good idea. (肯：我們晚餐吃麵吧。蓮娜：好主意。)" },
        { word: "pie", translate: "派", sentence: "Cindy and her mother are making a pie in the kitchen. (辛蒂和她媽媽正在廚房裡做派。)" },
        { word: "piece", translate: "塊;片;張", sentence: "There are two pieces of strawberry cake. You can have some. (這裡有兩塊草莓蛋糕。你可以吃一些。)" },
        { word: "glass", translate: "玻璃杯", sentence: "Nita: Do you want some drinks? Simon: Yes, I want a glass of black tea. (妮塔：你想喝點飲料嗎？賽門：是的，我想要一杯紅茶。)" },
        { word: "gram", translate: "公克", sentence: "Add fifty grams of sugar. (加入五十公克糖。)" },
        { word: "kilogram", translate: "公斤", sentence: "Ann has one kilogram of fish in her bag. (安的袋子裡有一公斤的魚。)" },
        { word: "salt", translate: "鹽", sentence: "Don't add too much salt to the egg. (不要加太多鹽到蛋裡。)" },
        { word: "sugar", translate: "糖", sentence: "My dad always drinks coffee with sugar and milk. (我爸爸喝咖啡總是加糖和牛奶。)" },
        { word: "a few", translate: "幾個;一些", sentence: "There are a few plates on the table. (桌上有幾個盤子。)" },
        { word: "a little", translate: "少量的;一點", sentence: "Please add a little cold water and sugar to the tea. (請加一點冷水和糖到茶裡。)" },
        { word: "can", translate: "(鐵、鋁)罐", sentence: "I need six cans of apple juice. (我需要六罐蘋果汁。)" },
        { word: "pancake", translate: "鬆餅", sentence: "Sherry is making pancakes in the kitchen. (雪莉正在廚房裡做鬆餅。)" },
        { word: "help", translate: "幫助", sentence: "Brad always helps his parents with the housework. (布萊德總是幫他父母做家事。)" },
        { word: "how many", translate: "多少(個)", sentence: "Sam: How many tests do you have today? Lily: I have two. (山姆：你今天有幾個考試？莉莉：我有兩個。)" },
        { word: "give", translate: "給", sentence: "Let's give our seats to those old men. (我們讓座給那些老人吧。)" },
        { word: "need", translate: "需要", sentence: "Ross: How many tickets do you need? Carol: Four, please. (羅斯：你需要幾張票？卡蘿：請給我四張。)" },
        { word: "flour", translate: "麵粉", sentence: "I don't have enough flour. I can't make noodles now. (我沒有足夠的麵粉。我現在沒辦法做麵條。)" },
        { word: "of course", translate: "當然", sentence: "Eunice: Can I go to the basketball game with you? Wayne: Of course. Let's meet at 5:00 p.m. (尤妮絲：我可以跟你一起去籃球賽嗎？韋恩：當然。我們下午五點見。)" },
        { word: "which", translate: "哪一個", sentence: "Jay: Which do you want, the green tea or the papaya milk? Doris: The papaya milk is fine. (傑：你想要哪一個，綠茶還是木瓜牛奶？桃樂絲：木瓜牛奶就好。)" },
        { word: "enough", translate: "足夠的", sentence: "I am not hungry. A small sandwich is enough for me. (我不餓。一個小三明治對我來說就夠了。)" },
        { word: "yummy", translate: "美味的", sentence: "These pies are yummy. (這些派很美味。)" },
        { word: "teach", translate: "教", sentence: "My uncle teaches PE at this senior high school. (我叔叔在這所高中教體育。)" },
        { word: "easy", translate: "容易的", sentence: "I can answer the question. It is very easy for me. (我能回答這個問題。這對我來說很容易。)" },
        { word: "how much", translate: "多少", sentence: "Ken: How much milk do you want? Amy: We want three glasses of milk. (肯：你們想要多少牛奶？艾美：我們想要三杯牛奶。)" },
        { word: "delicious", translate: "美味的", sentence: "The cook can make delicious dishes. (這位廚師能做出美味的菜餚。)" },
        { word: "difficult", translate: "困難的", sentence: "Joe can make pies. It is not difficult for him. (喬會做派。這對他來說不難。)" },
        { word: "add", translate: "添加", sentence: "Now, please add some salt to the vegetables in the pan. (現在，請在鍋裡的蔬菜加些鹽。)" },
        { word: "mix", translate: "混合", sentence: "Mix black tea and milk. Let's have some milk tea. (混合紅茶和牛奶。我們來喝些奶茶吧。)" },
        { word: "heat", translate: "加熱;熱", sentence: "Are you hungry? I can heat up the soup for you. (你餓了嗎？我可以幫你把湯加熱。)" },
        { word: "pan", translate: "平底鍋", sentence: "My mother cooks with a pan. (我媽媽用平底鍋煮飯。)" },
        { word: "butter", translate: "奶油", sentence: "Heat the pan. Then put some sugar, salt, and butter in it. (加熱平底鍋。然後放入一些糖、鹽和奶油。)" },
        { word: "round", translate: "圓形的", sentence: "Frank has a round face. (法蘭克有一張圓臉。)" },
        { word: "batter", translate: "糊狀物", sentence: "Please use the batter to make pancakes. (請用這個糊狀物來做鬆餅。)" },
        { word: "until", translate: "直到...為止", sentence: "Don't wait until it is too late. (不要等到太遲了才行動。)" },
        { word: "brown", translate: "棕色(的)", sentence: "Ken has beautiful brown eyes. (肯有著美麗的棕色眼睛。)" },
        { word: "both", translate: "兩者(都)", sentence: "My parents are both cooks. (我的父母都是廚師。)" },
        { word: "ready", translate: "準備好的", sentence: "Ann: Are you ready for the race? Ben: Yes, I am. (安：你準備好比賽了嗎？班：是的，我準備好了。)" }
    ],
    "Lesson 5": [
        { word: "science", translate: "科學", sentence: "Emily: When do you have science class? Sam: On Mondays, Wednesdays, and Fridays. (艾蜜莉：你什麼時候有科學課？山姆：在星期一、三和五。)" },
        { word: "camp", translate: "營隊;露營", sentence: "I joined an English camp and made many new friends there. (我參加了一個英語營，在那裡交了很多新朋友。)" },
        { word: "visit", translate: "造訪;拜訪", sentence: "Let's visit our grandma this weekend. (我們這個週末去拜訪奶奶吧。)" },
        { word: "art", translate: "藝術;美術", sentence: "Students draw pictures in art class. (學生們在美術課畫畫。)" },
        { word: "museum", translate: "博物館", sentence: "You cannot eat or drink in the museum. That's the rule. (你不能在博物館裡吃喝。這是規定。)" },
        { word: "ago", translate: "...之前", sentence: "Zoe was short two years ago, but now she is tall. (柔依兩年前很矮，但現在很高了。)" },
        { word: "computer", translate: "電腦", sentence: "There are thirty computers in the classroom. (教室裡有三十台電腦。)" },
        { word: "before", translate: "在...之前;以前", sentence: "John always works out before dinner. (約翰總是在晚餐前運動。)" },
        { word: "yesterday", translate: "昨天", sentence: "Chris was busy yesterday, but he is free today. (克里斯昨天很忙，但他今天有空。)" },
        { word: "surf the Internet", translate: "上網", sentence: "Ben only surfs the Internet on weekends. (班只有在週末才上網。)" },
        { word: "minute", translate: "分鐘", sentence: "The class is about forty-five minutes long. (這堂課大約四十五分鐘長。)" },
        { word: "hour", translate: "小時", sentence: "You are late. The meeting ended an hour ago. (你遲到了。會議一小時前就結束了。)" },
        { word: "story", translate: "故事", sentence: "It's a story about a fox. It wants some grapes in the tree. (這是一個關於狐狸的故事。牠想要樹上的一些葡萄。)" },
        { word: "lazy", translate: "懶惰的", sentence: "Get out of bed. Don't be so lazy. (起床吧。不要這麼懶惰。)" },
        { word: "even", translate: "甚至", sentence: "Everyone loves the song. Even my grandpa loves it. (每個人都喜歡這首歌。甚至我爺爺也喜歡。)" },
        { word: "should", translate: "應該", sentence: "You shouldn't make noise in the library. (你不應該在圖書館製造噪音。)" },
        { word: "wrong", translate: "錯誤的", sentence: "Oscar: Am I wrong? Paul: Yes, you are. The answer is B, not D. (奧斯卡：我錯了嗎？保羅：是的，你錯了。答案是B，不是D。)" },
        { word: "so", translate: "很;那麼", sentence: "It's so hot here. Let's go inside. (這裡好熱。我們進去吧。)" },
        { word: "just", translate: "就;恰好;剛剛", sentence: "I believe in you. Just do it! (我相信你。就去做吧！)" },
        { word: "later", translate: "稍後", sentence: "Vivian: See you later. Flora: OK. (薇薇安：待會見。芙蘿拉：好的。)" },
        { word: "save", translate: "拯救;省下;儲存", sentence: "The mouse helped the lion. He saved his life. (老鼠幫了獅子。牠救了他一命。)" },
        { word: "share", translate: "分享", sentence: "The strawberry pie is too big. Let's share it with our friends. (這個草莓派太大了。我們和朋友分享吧。)" },
        { word: "snack", translate: "點心", sentence: "Do you want some food? The snacks are free. (你想要些食物嗎？點心是免費的。)" },
        { word: "climb", translate: "攀爬", sentence: "The monkeys climbed the trees and jumped around. (猴子們爬上樹並到處跳。)" },
        { word: "kid", translate: "開玩笑;小孩", sentence: "Don't believe Henry. He's just kidding. (不要相信亨利。他只是在開玩笑。)" },
        { word: "explain", translate: "解釋", sentence: "You are late again. Please explain. (你又遲到了。請解釋。)" },
        { word: "leftovers", translate: "剩菜", sentence: "There are a lot of leftovers in the kitchen. Camila prepared too much food. (廚房裡有很多剩菜。卡蜜拉準備了太多食物。)" },
        { word: "hide-and-seek", translate: "捉迷藏", sentence: "The children are playing hide-and-seek in the playground. (孩子們正在遊樂場玩捉迷藏。)" },
        { word: "wise", translate: "有智慧的", sentence: "The old woman is wise. I really learned a lot from her. (這位老婦人很有智慧。我真的從她那裡學到了很多。)" },
        { word: "hunt", translate: "打獵", sentence: "Bears sometimes hunt at night. They eat small animals. (熊有時在晚上打獵。牠們吃小動物。)" },
        { word: "learn", translate: "學習;得知", sentence: "James can't play tennis, but he is learning. (詹姆斯不會打網球，但他正在學。)" },
        { word: "in the end", translate: "最後", sentence: "The player never practiced before the game. In the end, he lost. (這位選手賽前從不練習。最後，他輸了。)" }
    ],
    "Lesson 6": [
        { word: "mountain", translate: "山", sentence: "Jane went to the mountains last week. (珍上週去了山上。)" },
        { word: "lake", translate: "湖", sentence: "Sun Moon Lake is a beautiful place in Taiwan. (日月潭是台灣一個美麗的地方。)" },
        { word: "island", translate: "島", sentence: "There are some islands around Taiwan, like Green Island and Orchid Island. (台灣周圍有一些島嶼，像是綠島和蘭嶼。)" },
        { word: "beach", translate: "海灘", sentence: "Rachel went to the beach with her friends this afternoon. (瑞秋今天下午和朋友們去了海灘。)" },
        { word: "river", translate: "河", sentence: "Jay swam in the river last weekend. (傑上週末在河裡游泳。)" },
        { word: "hill", translate: "小山;丘陵", sentence: "There are many beautiful houses on the hill. (山丘上有許多美麗的房子。)" },
        { word: "pond", translate: "池塘", sentence: "There aren't any fish in the pond. (池塘裡沒有任何魚。)" },
        { word: "hike", translate: "健行", sentence: "Ivan goes hiking with his family once a month. (伊凡每個月都會和家人去健行一次。)" },
        { word: "swim", translate: "游泳", sentence: "Let's go to the beach and swim. (我們去海灘游泳吧。)" },
        { word: "airport", translate: "機場", sentence: "We got to the airport early this morning. (我們今天一大早就到了機場。)" },
        { word: "bright", translate: "明亮的;晴朗的", sentence: "The rooms were large and bright. (這些房間又大又明亮。)" },
        { word: "guy", translate: "傢伙;人", sentence: "Hey, guys! What are you doing here? (嘿，大家！你們在這裡做什麼？)" },
        { word: "suitcase", translate: "手提箱", sentence: "What's in your suitcase? It's heavy. (你的手提箱裡有什麼？很重喔。)" },
        { word: "through", translate: "通過;穿過", sentence: "Lily walked through the park and bought some snacks from the food stand. (莉莉穿過公園，在食物攤買了一些點心。)" },
        { word: "bring", translate: "帶來", sentence: "Rex: Can you bring me the menu? Tiffany: Sure. Just a second, please. (雷克斯：你能給我菜單嗎？蒂芬妮：當然。請等一下。)" },
        { word: "plastic", translate: "塑膠的;塑膠", sentence: "Ryan: Do you need a plastic bag? Iris: No, thanks. I have my bag with me. (萊恩：你需要塑膠袋嗎？艾莉絲：不，謝謝。我自己有帶袋子。)" },
        { word: "keep", translate: "保留;保持", sentence: "Let's keep the streets clean together. (我們一起保持街道的乾淨吧。)" },
        { word: "throw away", translate: "扔掉", sentence: "This old computer still works. Don't throw it away. (這台舊電腦還能用。不要把它丟掉。)" },
        { word: "start", translate: "開始", sentence: "Our science class starts at 8:10. (我們的科學課在8:10開始。)" },
        { word: "begin", translate: "開始", sentence: "The class began at 3 o'clock in the afternoon. (這堂課在下午三點開始。)" },
        { word: "elementary school", translate: "小學", sentence: "My son is ten years old. He is an elementary school student. (我兒子十歲。他是一名小學生。)" },
        { word: "hate", translate: "討厭;憎恨", sentence: "Joshua hates noises. He likes quiet places. (約書亞討厭噪音。他喜歡安靜的地方。)" },
        { word: "amazing", translate: "令人驚喜的", sentence: "Ashley is an amazing tennis player. (艾希莉是個令人驚喜的網球選手。)" },
        { word: "law", translate: "法律", sentence: "Don't break the law. It's not right. (不要違法。這是不對的。)" },
        { word: "-free", translate: "無...的", sentence: "You can buy sugar-free drinks at the market. (你可以在市場買到無糖飲料。)" },
        { word: "kind", translate: "種類;友善的", sentence: "There are many kinds of fruits at the market. (市場裡有很多種水果。)" },
        { word: "program", translate: "計畫", sentence: "Wesley: Can I join the program? Anna: Of course. Write down your full name and phone number here. (衛斯理：我可以加入這個計畫嗎？安娜：當然。把你的全名和電話號碼寫在這裡。)" },
        { word: "buy", translate: "買", sentence: "It's Mother's Day. Let's buy some flowers for Mom. (今天是母親節。我們買些花給媽媽吧。)" },
        { word: "hospital", translate: "醫院", sentence: "My parents are doctors. They work in the same hospital. (我的父母是醫生。他們在同一家醫院工作。)" },
        { word: "package", translate: "包裝;包裹", sentence: "Ann gave her son a package of toys on his birthday. (安在兒子生日時給了他一包玩具。)" },
        { word: "poor", translate: "貧窮的;可憐的", sentence: "Mr. and Mrs. Cook are nice people. They always help the poor. (庫克先生和太太是好人。他們總是幫助窮人。)" },
        { word: "stop", translate: "停止", sentence: "The car hit the man and stopped. (車子撞到那個人後停了下來。)" },
        { word: "collect", translate: "收集", sentence: "The kid collected a lot of trash on the street. (這孩子在街上收集了很多垃圾。)" },
        { word: "half", translate: "一半(的);二分之一", sentence: "Half of one hundred is fifty. (一百的一半是五十。)" },
        { word: "million", translate: "百萬", sentence: "Over two million people visit the city every year. (每年有超過兩百萬人造訪這座城市。)" },
        { word: "lead", translate: "領導", sentence: "Jennifer is nice and wise. She can lead the team. (珍妮佛人很好又有智慧。她能領導這個團隊。)" },
        { word: "one of a kind", translate: "獨一無二", sentence: "The bottles are all different. They are one of a kind. (這些瓶子都不一樣。它們是獨一無二的。)" }
    ]
};