// 確保全域變數存在，以便合併多版本、多冊的字庫
if (typeof window.englishDb === 'undefined') {
    window.englishDb = {};
}
if (!window.englishDb["南一"]) {
    window.englishDb["南一"] = {};
}

// ==========================================
// 南一版 2下 (Book 4) 完整字庫 (全單字 + 完整中文翻譯例句)
// ==========================================
window.englishDb["南一"]["二下"] = {
    "Lesson 1": [
        { word: "thin", translate: "瘦的", sentence: "The thin hungry dog is running on the street. (這隻又瘦又餓的狗正在街上跑。)" },
        { word: "side", translate: "邊;側", sentence: "A girl was sitting on the side of the road. (一個女孩正坐在路邊。)" },
        { word: "trash can", translate: "垃圾桶", sentence: "Please throw the garbage into the trash can. (請把垃圾丟進垃圾桶裡。)" },
        { word: "quiet", translate: "安靜的", sentence: "We're in the library now. Please be quiet. (我們現在在圖書館。請保持安靜。)" },
        { word: "pretty", translate: "漂亮的", sentence: "Jane is not just pretty. She is also smart. (珍不只漂亮。她也很聰明。)" },
        { word: "soup", translate: "湯", sentence: "Have some hot soup. It can warm you up. (喝點熱湯吧。這可以讓你暖和起來。)" },
        { word: "sandwich", translate: "三明治", sentence: "Ken usually has a sandwich for breakfast. (肯早餐通常吃三明治。)" },
        { word: "salad", translate: "沙拉", sentence: "I only had a salad for lunch because I was not very hungry. (我午餐只吃了一個沙拉，因為我不是很餓。)" },
        { word: "miss", translate: "想念", sentence: "Did you miss home when you studied in India? (你在印度讀書時會想家嗎？)" },
        { word: "than", translate: "比", sentence: "There's nothing better than home. (沒有什麼比家更好了。)" },
        { word: "hers", translate: "她的", sentence: "That's not my book. It's hers. (那不是我的書。那是她的。)" },
        { word: "bath", translate: "洗澡", sentence: "How often do you give your cat a bath? (你多常幫你的貓洗澡？)" },
        { word: "clothes", translate: "衣物", sentence: "These clothes are too small for Jack. He is too tall. (這些衣服對傑克來說太小了。他太高了。)" },
        { word: "sock", translate: "襪子", sentence: "I bought a pair of socks yesterday. (我昨天買了一雙襪子。)" },
        { word: "sweater", translate: "毛衣", sentence: "It's cold outside. Put on a sweater before you go out. (外面很冷。出門前穿上一件毛衣。)" },
        { word: "already", translate: "已經", sentence: "It's already very late, but Sam is still not home. (已經很晚了，但山姆還沒回家。)" },
        { word: "maybe", translate: "也許", sentence: "Maybe you are right. (也許你是對的。)" },
        { word: "lonely", translate: "寂寞的", sentence: "Jimmy listens to music when he is lonely. (吉米寂寞的時候會聽音樂。)" },
        { word: "blow", translate: "吹", sentence: "The wind blows through the window. (風從窗戶吹進來。)" },
        { word: "fat", translate: "胖的", sentence: "My dog was fat. I fed it too much food. (我的狗以前很胖。我餵牠吃太多食物了。)" },
        { word: "towel", translate: "毛巾", sentence: "Dry your body with a towel after your bath. (洗完澡後用毛巾擦乾身體。)" },
        { word: "paw", translate: "腳爪", sentence: "A cat's paw is so cute. (貓的腳爪好可愛。)" },
        { word: "little", translate: "小的", sentence: "On a winter day, a girl found a thin little cat on the side of the road. (在一個冬日，一個女孩在路邊發現了一隻瘦小的小貓。)" },
        { word: "free", translate: "自由的", sentence: "Her house is quiet and pretty, but I like to be outside because I am free there. (她的房子安靜又漂亮，但我喜歡待在外面，因為在那裡我是自由的。)" },
        { word: "T-shirt", translate: "T恤", sentence: "Ian's T-shirt was dirty after he played basketball. (伊恩打完籃球後，他的T恤很髒。)" },
        { word: "skirt", translate: "裙子", sentence: "That girl in the blue skirt is my sister. (那個穿藍色裙子的女孩是我妹妹。)" },
        { word: "shorts", translate: "短褲", sentence: "Don't wear shorts when you go hiking in the mountains. (去山上健行時不要穿短褲。)" },
        { word: "shirt", translate: "襯衫", sentence: "That man in the white shirt is my teacher. (那個穿白襯衫的男人是我老師。)" },
        { word: "dress", translate: "洋裝", sentence: "I will wear the red dress to the party. (我會穿這件紅洋裝去派對。)" },
        { word: "jeans", translate: "牛仔褲", sentence: "Don't wear jeans when you play basketball. (打籃球時不要穿牛仔褲。)" },
        { word: "pants", translate: "長褲", sentence: "These pants are too short for a 15-year-old boy. (這些長褲對一個15歲的男孩來說太短了。)" },
        { word: "coat", translate: "大衣", sentence: "A coat keeps you warm on a winter day. (大衣在冬日裡能讓你保暖。)" },
        { word: "tie", translate: "領帶", sentence: "Mr. Lin always puts on a tie before he goes to work. (林先生上班前總是會打領帶。)" },
        { word: "belt", translate: "腰帶", sentence: "These pants are too big for Hank. He needs a belt. (這些長褲對漢克來說太大了。他需要一條腰帶。)" },
        { word: "glove", translate: "手套", sentence: "Put on a pair of gloves before you ride a bike. (騎腳踏車前戴上一雙手套。)" },
        { word: "hat", translate: "帽子", sentence: "Sara doesn't like to wear hats. (莎拉不喜歡戴帽子。)" }
    ],
    "Lesson 2": [
        { word: "ice cream", translate: "冰淇淋", sentence: "It is great to have ice cream on a hot summer day. (在炎熱的夏日吃冰淇淋真棒。)" },
        { word: "sound", translate: "聽起來", sentence: "Sara: I read a book about a girl and her magic cat. Alex: It sounds like a fun story. (莎拉：我讀了一本關於一個女孩和她的魔法貓的書。艾力克斯：聽起來是個有趣的故事。)" },
        { word: "cut", translate: "切", sentence: "Please cut the cake into 5 pieces. (請把蛋糕切成五塊。)" },
        { word: "smell", translate: "聞起來", sentence: "The dish smells good. What did you put in it? (這道菜聞起來很香。你在裡面放了什麼？)" },
        { word: "tomato", translate: "番茄", sentence: "Is a tomato a vegetable or a fruit? (番茄是蔬菜還是水果？)" },
        { word: "cheese", translate: "起司", sentence: "People make cheese with milk. (人們用牛奶製作起司。)" },
        { word: "stomach", translate: "胃", sentence: "Something is wrong with my stomach. I need to take a break. (我的胃不舒服。我需要休息一下。)" },
        { word: "feel", translate: "感覺起來", sentence: "I really made it. It feels like a dream. (我真的做到了。感覺像一場夢。)" },
        { word: "seller", translate: "賣家", sentence: "The seller sells men's clothes. (這個賣家賣男裝。)" },
        { word: "stand", translate: "攤位", sentence: "A pizza seller is cutting a pizza at his stand. (一個披薩賣家正在他的攤位上切披薩。)" },
        { word: "bean", translate: "豆子", sentence: "Sara doesn't like the beans in the dish. (莎拉不喜歡這道菜裡的豆子。)" },
        { word: "bun", translate: "小圓麵包", sentence: "Irene always has some buns for breakfast. (艾琳早餐總是吃些小圓麵包。)" },
        { word: "butter", translate: "奶油", sentence: "Please put some butter on the bun. (請在小圓麵包上塗些奶油。)" },
        { word: "cookie", translate: "餅乾", sentence: "Would you like some tea with those cookies? (你想配些茶吃那些餅乾嗎？)" },
        { word: "French fries", translate: "薯條", sentence: "French fries are delicious, but don't eat too many at a time. (薯條很美味，但一次不要吃太多。)" },
        { word: "hot dog", translate: "熱狗", sentence: "I like to have bread with a hot dog in it. (我喜歡吃裡面夾熱狗的麵包。)" },
        { word: "popcorn", translate: "爆米花", sentence: "You can't watch a movie without popcorn. (你看電影不能沒有爆米花。)" },
        { word: "ham", translate: "火腿", sentence: "I had ham and bread for breakfast. (我早餐吃了火腿和麵包。)" },
        { word: "steak", translate: "肉排;牛排", sentence: "How would you like your steak? (你的牛排要幾分熟？)" },
        { word: "toast", translate: "烤麵包", sentence: "I had a piece of toast for breakfast. (我早餐吃了一片烤麵包。)" },
        { word: "hold", translate: "舉辦", sentence: "My school holds a basketball game every Saturday. (我的學校每個星期六舉辦一場籃球比賽。)" },
        { word: "main", translate: "主要的", sentence: "What is the main idea of the reading? (這篇閱讀的主要想法是什麼？)" },
        { word: "square", translate: "廣場", sentence: "There is a market in the square every Sunday morning. (每個星期天早上廣場上有個市場。)" },
        { word: "ring", translate: "響鈴", sentence: "The phone is ringing. Please pick it up. (電話在響。請接一下。)" },
        { word: "bell", translate: "鐘;鈴", sentence: "In Japan, people ring a bell before they pray for good luck at the temple. (在日本，人們在寺廟祈求好運前會敲鐘。)" },
        { word: "touch", translate: "觸摸", sentence: "Don't touch the bowl. It's hot. (不要碰那個碗。很燙。)" },
        { word: "deal", translate: "交易", sentence: "I bought this cellphone at a low price. It was a good deal! (我以低價買了這支手機。這是一筆很棒的交易！)" },
        { word: "clap", translate: "拍(手)", sentence: "Let's clap for Jane. She did a good job. (我們為珍鼓掌吧。她做得很好。)" },
        { word: "shout", translate: "喊叫", sentence: "Don't shout at the kids. Talk to them. (不要對孩子們大吼。好好跟他們說。)" },
        { word: "agree", translate: "同意", sentence: "Do you agree with the plan? (你同意這個計畫嗎？)" },
        { word: "shake hands", translate: "握手", sentence: "Two young men are shaking hands. (兩個年輕人正在握手。)" },
        { word: "smile", translate: "微笑", sentence: "When you meet someone for the first time, say hello with a smile. (當你第一次遇見某人時，帶著微笑打招呼。)" },
        { word: "village", translate: "村莊", sentence: "Eric came from a small fishing village. (艾瑞克來自一個小漁村。)" },
        { word: "traditional", translate: "傳統的", sentence: "Ning doesn't like traditional Chinese food. (寧不喜歡傳統的中國食物。)" },
        { word: "on display", translate: "展示", sentence: "The cellphone is on display. (這支手機正在展示中。)" },
        { word: "buyer", translate: "買家", sentence: "That woman is the buyer of the expensive car. (那個女人是這輛昂貴汽車的買家。)" },
        { word: "pay a visit", translate: "拜訪", sentence: "Next time, when you are in the Netherlands, be sure to pay a visit to this market. (下次你在荷蘭時，一定要去拜訪這個市場。)" }
    ],
    "Lesson 3": [
        { word: "slowly", translate: "緩慢地", sentence: "Could you please walk more slowly? You're going too fast. (請你走慢一點好嗎？你走太快了。)" },
        { word: "loudly", translate: "大聲地", sentence: "Benson cried loudly when he fell down. (班森跌倒時大聲哭了起來。)" },
        { word: "classmate", translate: "同學", sentence: "Alice and Jasper are classmates. They go to the same school. (愛麗絲和賈斯柏是同學。他們讀同一所學校。)" },
        { word: "neighbor", translate: "鄰居", sentence: "Tom and Hank are neighbors. They live next door to each other. (湯姆和漢克是鄰居。他們住在隔壁。)" },
        { word: "giant", translate: "巨大的", sentence: "Eric planned a giant party to celebrate his wife's birthday. (艾瑞克策劃了一個巨大的派對來慶祝他妻子的生日。)" },
        { word: "lucky", translate: "幸運的", sentence: "I am very lucky to meet so many nice people here. (我很幸運能在這裡遇到這麼多好人。)" },
        { word: "hide", translate: "躲藏", sentence: "Tommy tried to hide behind the car. (湯米試圖躲在車子後面。)" },
        { word: "rock", translate: "岩石", sentence: "Andy cannot move the rock. (安迪無法移動那塊岩石。)" },
        { word: "a while", translate: "一會兒", sentence: "I only stayed in Taipei for a short while. (我只在臺北待了一小段時間。)" },
        { word: "shine", translate: "照耀", sentence: "The sun shone all day long. (太陽一整天都閃耀著。)" },
        { word: "tail", translate: "尾巴", sentence: "The horse has a beautiful tail. (這匹馬有一條美麗的尾巴。)" },
        { word: "brave", translate: "勇敢的", sentence: "Terry is very brave to share his sad story with others. (泰瑞很勇敢地與他人分享他悲傷的故事。)" },
        { word: "somewhere", translate: "某處", sentence: "We looked for somewhere to park the car. (我們尋找某個地方停車。)" },
        { word: "count on", translate: "依靠", sentence: "You can always count on me. I will be there for you. (你永遠可以依靠我。我會在你身邊。)" },
        { word: "tuna", translate: "鮪魚", sentence: "I had a can of tuna for breakfast this morning. (我今天早上吃了一罐鮪魚當早餐。)" },
        { word: "alone", translate: "單獨的;獨自的", sentence: "Henry is alone in his room. (亨利獨自在他的房間裡。)" },
        { word: "block", translate: "阻擋", sentence: "The boat almost blocked out the sun. (這艘船幾乎擋住了太陽。)" },
        { word: "net", translate: "網子", sentence: "I swam the fastest, so the net didn't catch me. (我游得最快，所以網子沒有抓到我。)" },
        { word: "from now on", translate: "從現在開始", sentence: "From now on, we must watch out for boats more carefully. (從現在開始，我們必須更小心地留意船隻。)" },
        { word: "watch out", translate: "留意", sentence: "From now on, we must watch out for boats more carefully. (從現在開始，我們必須更小心地留意船隻。)" },
        { word: "bottle cap", translate: "瓶蓋", sentence: "Kelly used bottle caps to make a toy. (凱莉用瓶蓋做了一個玩具。)" },
        { word: "brush", translate: "刷子", sentence: "I painted with a big brush. (我用一把大刷子畫畫。)" },
        { word: "button", translate: "鈕扣", sentence: "I lost a coat button. (我掉了一顆大衣的鈕扣。)" },
        { word: "newspaper", translate: "報紙", sentence: "I bought a newspaper this morning. (我今天早上買了一份報紙。)" },
        { word: "pot", translate: "鍋;壺", sentence: "Dad made a pot of tea for grandfather every evening last week. (上週每天傍晚，爸爸都為爺爺泡一壺茶。)" },
        { word: "bench", translate: "長凳", sentence: "Ben sat on the bench for a long time. (班在長凳上坐了很久。)" },
        { word: "mask", translate: "口罩", sentence: "We have to wear a mask when we get sick. (我們生病時必須戴口罩。)" },
        { word: "basket", translate: "籃;籠", sentence: "I would not put all my eggs in one basket. (我不會把所有的雞蛋放在同一個籃子裡。)" },
        { word: "plastic", translate: "塑膠的", sentence: "Please recycle plastic bottles. Don't throw them in the trash. (請回收塑膠瓶。不要把它們丟進垃圾桶。)" },
        { word: "straw", translate: "吸管", sentence: "The woman is teaching her baby to drink from a straw. (那個女人正在教她的寶寶用吸管喝水。)" },
        { word: "used to", translate: "過去經常", sentence: "I used to have dinner at that restaurant when I was a student. (我當學生時過去經常在那家餐廳吃晚餐。)" },
        { word: "noisy", translate: "嘈雜的", sentence: "My neighbors are very noisy. I can't sleep well at night. (我的鄰居很吵。我晚上睡不好。)" },
        { word: "chance", translate: "機會", sentence: "I didn't have the chance to read the new book yet. (我還沒有機會讀這本新書。)" },
        { word: "oil", translate: "油", sentence: "He always cooks with little oil. (他煮菜總是放很少油。)" },
        { word: "trick", translate: "誘騙", sentence: "Justin tricked the old man into giving him $100,000. (賈斯汀誘騙那位老人給了他十萬元。)" },
        { word: "kill", translate: "殺害", sentence: "Someone killed the old man last night. (昨晚有人殺害了那位老人。)" },
        { word: "wastewater", translate: "廢水", sentence: "Wastewater from factories and houses is killing sea animals and plants. (來自工廠和家庭的廢水正在殺死海洋動植物。)" },
        { word: "breathe", translate: "呼吸", sentence: "We can't breathe without air. (沒有空氣我們無法呼吸。)" },
        { word: "sincerely", translate: "誠摯地", sentence: "I am sincerely grateful for Mandy's help. (我誠摯地感激曼蒂的幫忙。)" },
        { word: "not ... any longer", translate: "不再...", sentence: "We cannot wait any longer. (我們不能再等了。)" }
    ],
    "Lesson 4": [
        { word: "America", translate: "美國", sentence: "The White House is a landmark in America. (白宮是美國的地標。)" },
        { word: "a little", translate: "一些;少量的", sentence: "Would you like a little more milk in your tea? (你的茶裡想要多加一點牛奶嗎？)" },
        { word: "watermelon", translate: "西瓜", sentence: "Would you like a piece of watermelon on this hot summer day? (在這個炎熱的夏日，你想要來片西瓜嗎？)" },
        { word: "popular", translate: "受歡迎的;流行的", sentence: "She is a popular actress. (她是一位受歡迎的女演員。)" },
        { word: "guava", translate: "芭樂", sentence: "Some guavas are pink inside. (有些芭樂裡面是粉紅色的。)" },
        { word: "papaya", translate: "木瓜", sentence: "Papayas grow on trees. (木瓜長在樹上。)" },
        { word: "peach", translate: "桃子", sentence: "The peach is very big and sweet. (這桃子又大又甜。)" },
        { word: "mouth", translate: "嘴巴", sentence: "He can't talk now because his mouth is full of food. (他現在不能說話，因為他滿嘴都是食物。)" },
        { word: "supermarket", translate: "超市", sentence: "Mr. Wang opened a new supermarket last fall. (王先生去年秋天開了一家新超市。)" },
        { word: "mango", translate: "芒果", sentence: "The mango ice at this store is famous. (這家店的芒果冰很有名。)" },
        { word: "paradise", translate: "天堂", sentence: "This park is a paradise for kids. (這個公園是孩子們的天堂。)" },
        { word: "climate", translate: "氣候", sentence: "He likes to live in a country with a cool climate. (他喜歡住在氣候涼爽的國家。)" },
        { word: "skillful", translate: "有技術的;熟練的", sentence: "He is a skillful painter. (他是一位熟練的畫家。)" },
        { word: "water", translate: "流口水", sentence: "You're making my mouth water! (你讓我流口水了！)" },
        { word: "fall in love", translate: "愛上", sentence: "My parents fell in love when they were in college. (我父母在大學時墜入愛河。)" },
        { word: "strawberry", translate: "草莓", sentence: "Strawberries are out of season now. (草莓現在已經過季了。)" },
        { word: "lemon", translate: "檸檬", sentence: "Nina drank a cup of honey lemon water. (妮娜喝了一杯蜂蜜檸檬水。)" },
        { word: "pear", translate: "梨子", sentence: "Farmers grew these pears in the mountains. (農民在山上種植這些梨子。)" },
        { word: "grape", translate: "葡萄", sentence: "Grapes are my favorite fruit. (葡萄是我最喜歡的水果。)" },
        { word: "sugar", translate: "糖", sentence: "No sugar in my coffee, thanks. (我的咖啡不加糖，謝謝。)" },
        { word: "quarter", translate: "四分之一;十五分鐘", sentence: "A quarter of an hour is fifteen minutes. (四分之一小時是十五分鐘。)" },
        { word: "excellent", translate: "極好的", sentence: "My son is an excellent doctor. (我兒子是一位極好的醫生。)" },
        { word: "several", translate: "幾個的", sentence: "There are several books on the table. (桌上有幾本書。)" },
        { word: "successfully", translate: "成功地", sentence: "He successfully climbed up to the top of Mt. Jade when he was eighteen. (他在十八歲時成功地爬上了玉山山頂。)" },
        { word: "seed", translate: "種子;籽", sentence: "These are watermelon seeds. (這些是西瓜籽。)" },
        { word: "abroad", translate: "到國外;在國外", sentence: "My sister studied abroad when she was twenty-two years old. (我姐姐二十二歲時在國外留學。)" },
        { word: "improve", translate: "改善", sentence: "You have to improve your English. (你必須改善你的英文。)" },
        { word: "grow", translate: "種植", sentence: "Taiwan's climate is excellent for growing fruit. (臺灣的氣候非常適合種植水果。)" }
    ],
    "Lesson 5": [
        { word: "science", translate: "科學", sentence: "We learned about some special animals in today's science class. (我們在今天的科學課上了解了一些特別的動物。)" },
        { word: "strange", translate: "奇怪的", sentence: "Peter said something very strange to me. (彼得對我說了一些很奇怪的話。)" },
        { word: "through", translate: "穿越", sentence: "We drove through the tunnel. (我們開車穿越隧道。)" },
        { word: "noise", translate: "噪音", sentence: "Please stop making noise in the library. (請不要在圖書館裡製造噪音。)" },
        { word: "although", translate: "雖然;儘管", sentence: "Although he has a lot of money, he is not happy. (雖然他有很多錢，但他不快樂。)" },
        { word: "both", translate: "兩者(都)", sentence: "Both of my parents are very tall. (我的父母都很高。)" },
        { word: "if", translate: "如果", sentence: "If it rains tomorrow, we will not go hiking. (如果明天下雨，我們就不去健行。)" },
        { word: "anyone", translate: "任何人", sentence: "Was there anyone in the room? (房間裡有任何人嗎？)" },
        { word: "answer", translate: "答案", sentence: "What's the answer to the question? (這個問題的答案是什麼？)" },
        { word: "sign", translate: "告示;標誌", sentence: "The sign says \"No Swimming.\" (告示上寫著「禁止游泳」。)" },
        { word: "body", translate: "身體", sentence: "Drinking hot water keeps your body warm in winter. (喝熱水能在冬天保持身體溫暖。)" },
        { word: "change", translate: "改變", sentence: "I'm all wet. I need to change my clothes. (我全身都濕了。我需要換衣服。)" },
        { word: "copy", translate: "模仿;抄襲", sentence: "Ricky copied a good idea from a book and made a new toy. (瑞奇從書中模仿了一個好點子，做了一個新玩具。)" },
        { word: "head", translate: "頭部", sentence: "Sandy put a book on her head. (珊迪把一本書放在她頭上。)" },
        { word: "tunnel", translate: "隧道", sentence: "The train went into a tunnel. (火車開進了隧道。)" },
        { word: "design", translate: "設計", sentence: "My sister designed this pretty dress. / I like the design of the building. (我妹妹設計了這件漂亮的洋裝。 / 我喜歡這棟建築的設計。)" },
        { word: "beak", translate: "(鳥類的)嘴;喙", sentence: "Birds use their beaks to pick up food. (鳥類用牠們的喙啄取食物。)" },
        { word: "sound", translate: "聲音", sentence: "What's that strange sound? (那奇怪的聲音是什麼？)" },
        { word: "not at all", translate: "一點也不", sentence: "It's not noisy at all. (一點也不吵。)" },
        { word: "shape", translate: "外形;形狀", sentence: "Mike made the cake in the shape of a car. (麥克做了一個汽車形狀的蛋糕。)" },
        { word: "neck", translate: "脖子", sentence: "The tall girl has a long neck. (那個高個子女孩有長脖子。)" },
        { word: "hair", translate: "頭髮", sentence: "Tommy has short, black hair. (湯米有著黑色的短髮。)" },
        { word: "sharp", translate: "尖銳的", sentence: "This knife is sharp. Be careful! (這把刀很鋒利。小心！)" },
        { word: "nail", translate: "指甲", sentence: "Lisa is painting her nails. (麗莎正在塗指甲油。)" },
        { word: "lip", translate: "嘴唇", sentence: "Anna painted her lips to make them beautiful. (安娜塗了嘴唇讓它們看起來很漂亮。)" },
        { word: "nose", translate: "鼻子", sentence: "Fred has a small nose. (弗雷德有一個小鼻子。)" },
        { word: "knee", translate: "膝蓋", sentence: "Helen put the cat on her knee. (海倫把貓放在膝蓋上。)" },
        { word: "leg", translate: "腿", sentence: "Eric fell and hurt his leg. (艾瑞克摔倒傷了腿。)" },
        { word: "nature", translate: "大自然", sentence: "We can enjoy clean air in nature. (我們可以在大自然中享受新鮮空氣。)" },
        { word: "reason", translate: "原因", sentence: "Peter got angry for no reason. (彼得無緣無故地生氣了。)" },
        { word: "tooth", translate: "牙齒", sentence: "I need to have a tooth out. (我需要拔一顆牙。)" },
        { word: "cover", translate: "覆蓋", sentence: "Snow is covering the mountains. (雪覆蓋著群山。)" },
        { word: "tip", translate: "頂端;尖端", sentence: "Please touch the tip of your nose. (請碰一下你的鼻尖。)" },
        { word: "borrow", translate: "借用", sentence: "Nina often borrows money from her brother. (妮娜經常向她哥哥借錢。)" },
        { word: "shark", translate: "鯊魚", sentence: "I saw many sharks circling the boat. (我看到很多鯊魚在船周圍盤旋。)" },
        { word: "skin", translate: "皮膚", sentence: "Her skin becomes better every day. (她的皮膚每天都變得更好。)" },
        { word: "scale", translate: "魚鱗", sentence: "Scales cover the skin of many fish. (鱗片覆蓋在許多魚的皮膚上。)" },
        { word: "swimsuit", translate: "泳衣", sentence: "I bought this swimsuit three days ago. (我三天前買了這件泳衣。)" },
        { word: "plant", translate: "植物", sentence: "Biomimicry is about copying from animals and plants. (仿生學是關於模仿動植物。)" }
    ],
    "Lesson 6": [
        { word: "vacation", translate: "假期", sentence: "Julia is on vacation this week. (茱莉亞這週在休假。)" },
        { word: "belong to", translate: "屬於", sentence: "This cap belongs to me, not Penny. (這頂帽子屬於我，不是潘妮的。)" },
        { word: "history", translate: "歷史", sentence: "Jimmy knows a lot about American history. (吉米對美國歷史了解很多。)" },
        { word: "uniform", translate: "制服", sentence: "Eric looks good in uniform. (艾瑞克穿制服看起來很好看。)" },
        { word: "the public", translate: "民眾", sentence: "The museum is not open to the public on Mondays. (這家博物館星期一不對大眾開放。)" },
        { word: "glad", translate: "高興的", sentence: "I'm so glad you came to my party. (我很高興你來參加我的派對。)" },
        { word: "perhaps", translate: "也許", sentence: "Paul: Will Sally come to the party? Emma: Well, perhaps she won't. (保羅：莎莉會來參加派對嗎？艾瑪：嗯，也許她不會。)" },
        { word: "key chain", translate: "鑰匙圈", sentence: "Did you see my key chain? (你有看到我的鑰匙圈嗎？)" },
        { word: "crow", translate: "烏鴉", sentence: "Crows are as smart as a seven-year-old child. (烏鴉和七歲小孩一樣聰明。)" },
        { word: "raven", translate: "渡鴉", sentence: "Many people go to the Tower of London to see the ravens. (許多人去倫敦塔看渡鴉。)" },
        { word: "pretty much", translate: "幾乎完全地", sentence: "Crows and ravens are pretty much the same. (烏鴉和渡鴉幾乎完全一樣。)" },
        { word: "all ears", translate: "洗耳恭聽", sentence: "I'm all ears. (我洗耳恭聽。)" },
        { word: "mail carrier", translate: "郵差", sentence: "The mail carrier is busy collecting letters. (郵差正忙著收信。)" },
        { word: "voice actor", translate: "配音員", sentence: "Danny wants to become a voice actor. (丹尼想成為一名配音員。)" },
        { word: "driver", translate: "駕駛員", sentence: "David's father is a bus driver. (大衛的爸爸是公車司機。)" },
        { word: "engineer", translate: "工程師", sentence: "My father is an engineer. He works late every day. (我爸爸是工程師。他每天工作到很晚。)" },
        { word: "comic", translate: "漫畫", sentence: "Henry loves to read comic books when he has free time. (亨利有空時喜歡看漫畫書。)" },
        { word: "writer", translate: "作家", sentence: "J.K. Rowling is a famous writer. (J.K. 羅琳是位著名的作家。)" },
        { word: "soldier", translate: "士兵;軍人", sentence: "It takes a lot of training to be a good soldier. (要成為一名好士兵需要很多訓練。)" },
        { word: "dark", translate: "深色的", sentence: "My mom has long dark hair. (我媽媽有一頭深色的長髮。)" },
        { word: "ugly", translate: "醜的", sentence: "This couch is expensive and ugly. I won't buy it. (這張沙發又貴又醜。我不會買它。)" },
        { word: "however", translate: "然而", sentence: "Nick wants to buy a new car. However, his wife does not. (尼克想買新車。然而，他妻子不想。)" },
        { word: "follow", translate: "聽從;跟隨", sentence: "It's easy to get to that coffee shop. Just follow me. (去那家咖啡店很容易。跟著我就好。)" },
        { word: "quite", translate: "很;相當", sentence: "The food at this restaurant is quite good. (這家餐廳的食物相當好。)" },
        { word: "healthy", translate: "健康的", sentence: "My father goes hiking every day to keep himself healthy. (我爸爸每天去健行以保持健康。)" },
        { word: "part", translate: "一部分", sentence: "Only a few parts of this movie are interesting. (這部電影只有一小部分很有趣。)" },
        { word: "be able to", translate: "能夠", sentence: "I am able to finish all my homework before dinner. (我能夠在晚餐前做完所有功課。)" },
        { word: "ground", translate: "地面", sentence: "Johnny, don't sit on the ground. (強尼，不要坐在地上。)" },
        { word: "stair", translate: "樓梯", sentence: "Judy fell down from the stairs and broke her arm. (茱蒂從樓梯上摔下來，摔斷了手臂。)" },
        { word: "high", translate: "高的", sentence: "There is a cat sitting on the high wall. (有隻貓坐在高牆上。)" },
        { word: "wall", translate: "牆壁", sentence: "There is a high wall behind the train station. (火車站後面有一堵高牆。)" },
        { word: "legend", translate: "傳說", sentence: "She is writing a book about Chinese legends. (她正在寫一本關於中國傳說的書。)" },
        { word: "kingdom", translate: "王國", sentence: "Denmark is a kingdom. (丹麥是一個王國。)" },
        { word: "keeper", translate: "飼養者", sentence: "Paul is a zoo keeper. (保羅是動物園飼養員。)" },
        { word: "protector", translate: "保護者", sentence: "You need to find a protector. (你需要找個保護者。)" },
        { word: "tradition", translate: "傳統", sentence: "This is an old tradition. (這是一個古老的傳統。)" },
        { word: "honor", translate: "榮譽", sentence: "It's an honor to meet you, sir. (見到您是我的榮幸，先生。)" },
        { word: "safe and sound", translate: "安然無恙", sentence: "Thanks to Ravenmaster, these birds are safe and sound. (多虧了渡鴉官，這些鳥兒安然無恙。)" },
        { word: "leave", translate: "離開", sentence: "If the ravens leave the Tower of London, the kingdom will fall. (如果渡鴉離開倫敦塔，王國就會殞落。)" },
        { word: "order", translate: "命令", sentence: "Because of this legend, King Charles II ordered his people to always keep ravens in the Tower. / Today, the British are still following the king's order. (因為這個傳說，查理二世國王命令他的人民必須一直在倫敦塔裡飼養渡鴉。 / 如今，英國人仍然遵循著國王的命令。)" },
        { word: "full-time", translate: "全職的", sentence: "Ravens have a full-time keeper, Ravenmaster. (渡鴉有一位全職飼養員：渡鴉官。)" }
    ]
};